import type { DbPool } from "../db/types.js";
import type { OfflineCatchUpRound, OfflineLocalAdmissionWatermark } from "./offlineGenerationBarrierModel.js";
import { isCanonicalAddress, isCanonicalOrderHash, isDecimal, isIso } from "./verifier/targetedVerifierPolicy.js";
import { SUPPORTED_CHAIN, SUPPORTED_CONTRACT_ADDRESS } from "./identityScope.js";

export interface GenerationWindowIdentity { readonly orderHashes: ReadonlySet<string>; readonly nftKeys: ReadonlySet<string>; }
export interface GenerationWindowStart { readonly eventHighWaterBefore: OfflineLocalAdmissionWatermark; }
export interface GenerationWindowObservation { readonly observedHighWater: OfflineLocalAdmissionWatermark; readonly round: OfflineCatchUpRound; readonly eventIds: readonly string[]; }
interface EventRow { event_id:string; received_at:string|Date; event_type:string; processing_status:string; order_hash:string|null; chain:string|null; contract_address:string|null; token_id:string|null; }
const statuses=new Set(["pending","processing","applied","reconciliation_required","failed","ignored_duplicate","ignored_older"]);
const orderEvents=new Set(["item_listed","item_sold","item_cancelled","order_invalidate","order_revalidate"]);
function wm(id:string,received:string|Date):OfflineLocalAdmissionWatermark { const r=received instanceof Date?received.toISOString():received; if(!isDecimal(id)||!isIso(r))throw new Error("GENERATION_WINDOW_MALFORMED_WATERMARK"); return {eventId:id,receivedAt:r}; }
function nftKey(c:string,a:string,t:string){return [c,a,t].join("\0");}
export class PostgresGenerationJournalWindowReader {
  constructor(private readonly pool:DbPool){}
  async captureStart():Promise<GenerationWindowStart>{const c=await this.pool.connect();try{await c.query("BEGIN");await c.query("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY");const q=await c.query<{event_id:string;received_at:string|Date}>("SELECT event_id::text,received_at FROM public.opensea_listings_events_v2 ORDER BY event_id DESC LIMIT 1");const out=q.rows[0]?wm(q.rows[0].event_id,q.rows[0].received_at):wm("0",(await c.query<{now:string|Date}>("SELECT transaction_timestamp() now")).rows[0].now);await c.query("COMMIT");return {eventHighWaterBefore:out};}catch(e){try{await c.query("ROLLBACK")}catch{}throw e}finally{c.release();}}
  async observe(start:GenerationWindowStart,identity:GenerationWindowIdentity,roundNumber=1):Promise<GenerationWindowObservation>{const c=await this.pool.connect();try{await c.query("BEGIN");await c.query("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY");const h=await c.query<{event_id:string;received_at:string|Date}>("SELECT event_id::text,received_at FROM public.opensea_listings_events_v2 ORDER BY event_id DESC LIMIT 1");const high=h.rows[0]?wm(h.rows[0].event_id,h.rows[0].received_at):start.eventHighWaterBefore;const rows=await c.query<EventRow>("SELECT event_id::text,received_at,event_type,processing_status,order_hash,chain,contract_address,token_id FROM public.opensea_listings_events_v2 WHERE event_id > $1::bigint AND event_id <= $2::bigint ORDER BY event_id ASC",[start.eventHighWaterBefore.eventId,high.eventId]);let pending=0,processing=0,failed=0,reconciliation=0,unknown=0;const ids:string[]=[];for(const r of rows.rows){let relevant=false;if(orderEvents.has(r.event_type)){if(r.chain!==SUPPORTED_CHAIN||r.contract_address!==SUPPORTED_CONTRACT_ADDRESS||r.order_hash===null||!isCanonicalOrderHash(r.order_hash))throw new Error("GENERATION_WINDOW_MALFORMED_IDENTITY");relevant=true;}else if(r.event_type==="item_transferred"){if(r.chain===null||r.contract_address===null||r.token_id===null||!isCanonicalAddress(r.contract_address)||!isDecimal(r.token_id))throw new Error("GENERATION_WINDOW_MALFORMED_IDENTITY");relevant=identity.nftKeys.has(nftKey(r.chain,r.contract_address,r.token_id));}if(!relevant)continue;if(!statuses.has(r.processing_status)){unknown++;ids.push(r.event_id);continue;}ids.push(r.event_id);if(r.processing_status==="pending")pending++;else if(r.processing_status==="processing")processing++;else if(r.processing_status==="failed")failed++;else if(r.processing_status==="reconciliation_required")reconciliation++;}await c.query("COMMIT");return {observedHighWater:high,eventIds:ids,round:{roundNumber,observedHighWater:high,pendingCount:pending,processingCount:processing,failedCount:failed,reconciliationRequiredCount:reconciliation,unknownStatusCount:unknown}};}catch(e){try{await c.query("ROLLBACK")}catch{}throw e}finally{c.release();}}
}
