import type { DbPool } from "../db/types.js";
import { canonicalEvidence, deepFreeze, sha256Canonical } from "./evidence/canonicalEvidence.js";
import { isTrustedReconstructedEvidence, type IntegratedEvidenceResult } from "./evidence/reconciliationEvidenceIntegration.js";
import { SUPPORTED_CHAIN, SUPPORTED_COLLECTION_SLUG, SUPPORTED_CONTRACT_ADDRESS, ADDRESS_PATTERN } from "./identityScope.js";
import { OFFLINE_CANDIDATE_MODEL_VERSION } from "./offlineCandidateModel.js";
import { OFFLINE_GENERATION_MODEL_VERSION, validateOfflineGenerationResult } from "./offlineGenerationBarrierModel.js";
import { OPENSEA_ORDER_CONTRACT_VERSION, TARGETED_VERIFIER_NORMALIZER_VERSION, TARGETED_VERIFIER_POLICY_VERSION, TARGETED_VERIFIER_SCHEMA_VERSION } from "./verifier/targetedVerifierTypes.js";

export const GENERATION_PUBLICATION_SCHEMA_VERSION = "reconciliation-generation-publication-v1" as const;
export const GENERATION_COMMITMENT_SCHEMA = "reconciliation-generation-commitment-v1" as const;
export const GENERATION_PUBLICATION_ID_SCHEMA = "reconciliation-generation-publication-v1" as const;
export type GenerationPublicationState = "ACCEPTED" | "REJECTED" | "SUPERSEDED";
export interface GenerationPublicationScope { readonly chain: typeof SUPPORTED_CHAIN; readonly collectionSlug: typeof SUPPORTED_COLLECTION_SLUG; readonly contractAddress: typeof SUPPORTED_CONTRACT_ADDRESS; readonly protocolAddress: string; }
export interface GenerationPublicationEvidenceV1 {
  readonly schemaVersion: typeof GENERATION_PUBLICATION_SCHEMA_VERSION;
  readonly publicationSequence: number;
  readonly publicationState: GenerationPublicationState;
  readonly scope: GenerationPublicationScope;
  readonly sweepId: string;
  readonly generationRootHash: string;
  readonly candidateArtifactHash: string;
  readonly barrierArtifactHash: string;
  readonly candidateModelVersion: string;
  readonly generationModelVersion: string;
  readonly verifierSchemaVersion: string;
  readonly verifierPolicyVersion: string;
  readonly providerContractVersion: string;
  readonly normalizerVersion: string;
  readonly sourceEvidenceHash: string;
  readonly sourceArtifactIdentity: Readonly<{ readonly manifestRootContentHash: string; readonly candidateArtifactHash: string; readonly barrierArtifactHash: string; readonly sourceProvenance: Readonly<Record<string, string>> }>;
  readonly generationCommitmentId: string;
  readonly generationPublicationId: string;
  readonly createdAt: string;
}
export interface GenerationPublicationSource { readonly integratedEvidence: IntegratedEvidenceResult; readonly protocolAddress: string; readonly createdAt: string; readonly publicationState?: GenerationPublicationState; }
export type CurrentGenerationResult = { readonly outcome: "CURRENT"; readonly publication: GenerationPublicationEvidenceV1 } | { readonly outcome: "CURRENT_GENERATION_UNPROVEN" | "CURRENT_GENERATION_CONFLICT"; readonly publication: null; };
const allowedKeys = ["schemaVersion","publicationSequence","publicationState","scope","sweepId","generationRootHash","candidateArtifactHash","barrierArtifactHash","candidateModelVersion","generationModelVersion","verifierSchemaVersion","verifierPolicyVersion","providerContractVersion","normalizerVersion","sourceEvidenceHash","sourceArtifactIdentity","generationCommitmentId","generationPublicationId","createdAt"] as const;
const states = new Set<GenerationPublicationState>(["ACCEPTED", "REJECTED", "SUPERSEDED"]);
const record = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === "object" && !Array.isArray(value);
const hash = (value: unknown): value is string => typeof value === "string" && /^[0-9a-f]{64}$/.test(value);
const text = (value: unknown): value is string => typeof value === "string" && value.length > 0;
const iso = (value: unknown): value is string => text(value) && Number.isFinite(Date.parse(value));
const provenance = (value: unknown): value is Readonly<Record<string, string>> => record(value) && Object.keys(value).length > 0 && Object.entries(value).every(([k, v]) => text(k) && text(v));
const scopeValid = (value: unknown): value is GenerationPublicationScope => record(value) && Object.keys(value).every((key) => ["chain","collectionSlug","contractAddress","protocolAddress"].includes(key)) && Object.keys(value).length === 4 && value.chain === SUPPORTED_CHAIN && value.collectionSlug === SUPPORTED_COLLECTION_SLUG && value.contractAddress === SUPPORTED_CONTRACT_ADDRESS && typeof value.protocolAddress === "string" && ADDRESS_PATTERN.test(value.protocolAddress);
const sourceIdentityMaterial = (source: GenerationPublicationSource, manifestRoot: string, candidateHash: string, barrierHash: string) => ({ manifestRootContentHash: manifestRoot, candidateArtifactHash: candidateHash, barrierArtifactHash: barrierHash, sourceProvenance: source.integratedEvidence.manifest!.sourceProvenance });
export function generationCommitmentMaterial(value: Pick<GenerationPublicationEvidenceV1, "scope"|"sweepId"|"generationRootHash"|"candidateArtifactHash"|"barrierArtifactHash"|"candidateModelVersion"|"generationModelVersion"|"verifierSchemaVersion"|"verifierPolicyVersion"|"providerContractVersion"|"normalizerVersion">) { return { schema: GENERATION_COMMITMENT_SCHEMA, scope: value.scope, sweepId: value.sweepId, generationRootHash: value.generationRootHash, candidateArtifactHash: value.candidateArtifactHash, barrierArtifactHash: value.barrierArtifactHash, candidateModelVersion: value.candidateModelVersion, generationModelVersion: value.generationModelVersion, verifierSchemaVersion: value.verifierSchemaVersion, verifierPolicyVersion: value.verifierPolicyVersion, providerContractVersion: value.providerContractVersion, normalizerVersion: value.normalizerVersion }; }
export function generationPublicationMaterial(value: Pick<GenerationPublicationEvidenceV1, "schemaVersion"|"generationCommitmentId"|"publicationSequence"|"publicationState"|"sourceEvidenceHash"|"sourceArtifactIdentity">) { return { schema: GENERATION_PUBLICATION_ID_SCHEMA, schemaVersion: value.schemaVersion, generationCommitmentId: value.generationCommitmentId, publicationSequence: value.publicationSequence, publicationState: value.publicationState, sourceEvidenceHash: value.sourceEvidenceHash, sourceArtifactIdentity: value.sourceArtifactIdentity }; }
export function createGenerationPublicationEvidence(source: GenerationPublicationSource, publicationSequence: number): GenerationPublicationEvidenceV1 {
  if (!isTrustedReconstructedEvidence(source.integratedEvidence) || source.integratedEvidence.status !== "VALID" || !source.integratedEvidence.manifest || !source.integratedEvidence.candidateRef || !source.integratedEvidence.barrierRef || !validateOfflineGenerationResult(source.integratedEvidence.barrier?.payload).valid) throw new Error("INVALID_ACCEPTED_GENERATION_EVIDENCE");
  if (!Number.isSafeInteger(publicationSequence) || publicationSequence < 0 || !ADDRESS_PATTERN.test(source.protocolAddress)) throw new Error("INVALID_GENERATION_PUBLICATION_INPUT");
  const manifest = source.integratedEvidence.manifest; const candidateRef = source.integratedEvidence.candidateRef; const barrierRef = source.integratedEvidence.barrierRef;
  const scope = { chain: SUPPORTED_CHAIN, collectionSlug: SUPPORTED_COLLECTION_SLUG, contractAddress: SUPPORTED_CONTRACT_ADDRESS, protocolAddress: source.protocolAddress } as const;
  const sourceArtifactIdentity = sourceIdentityMaterial(source, manifest.rootContentHash, candidateRef.contentHash, barrierRef.contentHash);
  const base = { schemaVersion: GENERATION_PUBLICATION_SCHEMA_VERSION, publicationSequence, publicationState: source.publicationState ?? "ACCEPTED" as const, scope, sweepId: manifest.sweepId, generationRootHash: manifest.rootContentHash, candidateArtifactHash: candidateRef.contentHash, barrierArtifactHash: barrierRef.contentHash, candidateModelVersion: OFFLINE_CANDIDATE_MODEL_VERSION, generationModelVersion: OFFLINE_GENERATION_MODEL_VERSION, verifierSchemaVersion: TARGETED_VERIFIER_SCHEMA_VERSION, verifierPolicyVersion: TARGETED_VERIFIER_POLICY_VERSION, providerContractVersion: OPENSEA_ORDER_CONTRACT_VERSION, normalizerVersion: TARGETED_VERIFIER_NORMALIZER_VERSION, sourceEvidenceHash: sha256Canonical({ manifest: manifest.rootContentHash, candidate: candidateRef.contentHash, barrier: barrierRef.contentHash, provenance: manifest.sourceProvenance }), sourceArtifactIdentity, createdAt: source.createdAt };
  const generationCommitmentId = sha256Canonical(generationCommitmentMaterial(base)); const generationPublicationId = sha256Canonical(generationPublicationMaterial({ ...base, generationCommitmentId }));
  return deepFreeze({ ...base, generationCommitmentId, generationPublicationId });
}
export function validateGenerationPublicationEvidence(value: unknown): value is GenerationPublicationEvidenceV1 {
  if (!record(value) || Object.keys(value).some((key) => !(allowedKeys as readonly string[]).includes(key)) || allowedKeys.some((key) => !Object.prototype.hasOwnProperty.call(value, key))) return false;
  if (value.schemaVersion !== GENERATION_PUBLICATION_SCHEMA_VERSION || !Number.isSafeInteger(value.publicationSequence) || (value.publicationSequence as number) < 0 || !states.has(value.publicationState as GenerationPublicationState) || !scopeValid(value.scope) || !text(value.sweepId) || !hash(value.generationRootHash) || !hash(value.candidateArtifactHash) || !hash(value.barrierArtifactHash) || value.candidateModelVersion !== OFFLINE_CANDIDATE_MODEL_VERSION || value.generationModelVersion !== OFFLINE_GENERATION_MODEL_VERSION || value.verifierSchemaVersion !== TARGETED_VERIFIER_SCHEMA_VERSION || value.verifierPolicyVersion !== TARGETED_VERIFIER_POLICY_VERSION || value.providerContractVersion !== OPENSEA_ORDER_CONTRACT_VERSION || value.normalizerVersion !== TARGETED_VERIFIER_NORMALIZER_VERSION || !hash(value.sourceEvidenceHash) || !hash(value.generationCommitmentId) || !hash(value.generationPublicationId) || !iso(value.createdAt)) return false;
  if (!record(value.sourceArtifactIdentity) || Object.keys(value.sourceArtifactIdentity).some((key) => !["manifestRootContentHash","candidateArtifactHash","barrierArtifactHash","sourceProvenance"].includes(key)) || Object.keys(value.sourceArtifactIdentity).length !== 4 || !hash(value.sourceArtifactIdentity.manifestRootContentHash) || !hash(value.sourceArtifactIdentity.candidateArtifactHash) || !hash(value.sourceArtifactIdentity.barrierArtifactHash) || !provenance(value.sourceArtifactIdentity.sourceProvenance) || value.sourceArtifactIdentity.manifestRootContentHash !== value.generationRootHash || value.sourceArtifactIdentity.candidateArtifactHash !== value.candidateArtifactHash || value.sourceArtifactIdentity.barrierArtifactHash !== value.barrierArtifactHash || value.sourceEvidenceHash !== sha256Canonical({ manifest: value.generationRootHash, candidate: value.candidateArtifactHash, barrier: value.barrierArtifactHash, provenance: value.sourceArtifactIdentity.sourceProvenance })) return false;
  if (value.generationCommitmentId !== sha256Canonical(generationCommitmentMaterial(value as unknown as GenerationPublicationEvidenceV1))) return false;
  if (value.generationPublicationId !== sha256Canonical(generationPublicationMaterial(value as unknown as GenerationPublicationEvidenceV1))) return false;
  return true;
}
export interface GenerationPublicationStore { publish(source: GenerationPublicationSource): Promise<GenerationPublicationEvidenceV1>; getCurrentAcceptedGeneration(scope: GenerationPublicationScope): Promise<CurrentGenerationResult>; }
export class PostgresGenerationPublicationStore implements GenerationPublicationStore {
  constructor(private readonly pool: DbPool) {}
  async publish(source: GenerationPublicationSource): Promise<GenerationPublicationEvidenceV1> { const c = await this.pool.connect(); try { await c.query("BEGIN"); const probe = createGenerationPublicationEvidence(source, 0); const findExisting = async () => c.query<{payload: unknown}>("SELECT payload FROM public.targeted_verifier_generation_publications WHERE generation_commitment_id=$1 AND source_evidence_hash=$2 AND publication_state=$3 FOR UPDATE", [probe.generationCommitmentId, probe.sourceEvidenceHash, probe.publicationState]); let existing = await findExisting(); if (existing.rows[0]) { const prior = decode(existing.rows[0].payload); await c.query("COMMIT"); return prior; } const seq = await c.query<{publication_sequence:number}>("UPDATE public.targeted_verifier_generation_publication_sequence SET publication_sequence=publication_sequence+1 WHERE sequence_key=$1 RETURNING publication_sequence", ["targeted-verifier-generation"]); const next = Number(seq.rows[0]?.publication_sequence); if (!Number.isSafeInteger(next)) throw new Error("GENERATION_SEQUENCE_ALLOCATION_FAILED"); existing = await findExisting(); if (existing.rows[0]) { const prior = decode(existing.rows[0].payload); await c.query("COMMIT"); return prior; } const publication = createGenerationPublicationEvidence(source, next); await c.query("INSERT INTO public.targeted_verifier_generation_publications (generation_publication_id,generation_commitment_id,publication_sequence,publication_state,sweep_id,generation_root_hash,candidate_artifact_hash,barrier_artifact_hash,candidate_model_version,generation_model_version,verifier_schema_version,verifier_policy_version,provider_contract_version,normalizer_version,scope,payload,source_evidence_hash,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16::jsonb,$17,$18)", [publication.generationPublicationId, publication.generationCommitmentId, publication.publicationSequence, publication.publicationState, publication.sweepId, publication.generationRootHash, publication.candidateArtifactHash, publication.barrierArtifactHash, publication.candidateModelVersion, publication.generationModelVersion, publication.verifierSchemaVersion, publication.verifierPolicyVersion, publication.providerContractVersion, publication.normalizerVersion, JSON.stringify(publication.scope), JSON.stringify(publication), publication.sourceEvidenceHash, publication.createdAt]); await c.query("COMMIT"); return publication; } catch (error) { try { await c.query("ROLLBACK"); } catch {} throw error; } finally { c.release(); } }
  async getCurrentAcceptedGeneration(scope: GenerationPublicationScope): Promise<CurrentGenerationResult> { const result = await this.pool.query<{payload: unknown; publication_sequence?: number|string}>("SELECT payload, publication_sequence FROM public.targeted_verifier_generation_publications WHERE publication_state='ACCEPTED' AND scope->>'chain'=$1 AND scope->>'collectionSlug'=$2 AND scope->>'contractAddress'=$3 ORDER BY publication_sequence DESC", [scope.chain, scope.collectionSlug, scope.contractAddress]); const rows = [...result.rows].sort((a, b) => Number(b.publication_sequence ?? (record(b.payload) ? b.payload.publicationSequence : -1)) - Number(a.publication_sequence ?? (record(a.payload) ? a.payload.publicationSequence : -1))); if (rows.length === 0) return { outcome: "CURRENT_GENERATION_UNPROVEN", publication: null }; try { const top = decode(rows[0].payload); if (canonicalEvidence(top.scope) !== canonicalEvidence(scope)) return { outcome: "CURRENT_GENERATION_UNPROVEN", publication: null }; const valid: GenerationPublicationEvidenceV1[] = []; for (const row of rows) { const publication = decode(row.payload); if (canonicalEvidence(publication.scope) === canonicalEvidence(scope)) valid.push(publication); } const conflicts = valid.filter((item) => item.publicationSequence === top.publicationSequence && item.generationPublicationId !== top.generationPublicationId); if (conflicts.length > 0) return { outcome: "CURRENT_GENERATION_CONFLICT", publication: null }; return { outcome: "CURRENT", publication: top }; } catch { return { outcome: "CURRENT_GENERATION_UNPROVEN", publication: null }; } }
}
function decode(value: unknown): GenerationPublicationEvidenceV1 { const parsed = typeof value === "string" ? JSON.parse(value) as unknown : value; if (!validateGenerationPublicationEvidence(parsed)) throw new Error("INVALID_GENERATION_PUBLICATION"); return deepFreeze(parsed as GenerationPublicationEvidenceV1); }
