import type { DbPool, TransactionClient } from "../db/types.js";
import { importActiveListingsEvidenceObject, type ImportedCompleteEvidence, validateOfflineCandidateBundle } from "./offlineCandidateModel.js";
import type { InitialGenerationBaselineProjection } from "./initialGenerationBaseline.js";
import { createGenerationWindowScopeFromInitialProjection, type GenerationWindowScope } from "./generationJournalWindowReader.js";
import { canonicalEvidence, deepFreeze, sha256Canonical } from "./evidence/canonicalEvidence.js";
import { isTrustedReconstructedEvidence, type IntegratedEvidenceResult } from "./evidence/reconciliationEvidenceIntegration.js";
import { decodeGenerationPublicationRow, validateGenerationPublicationEvidence, type GenerationPublicationDbRow, type GenerationPublicationEvidenceV1 } from "./generationPublication.js";
import { ADDRESS_PATTERN, SUPPORTED_CHAIN, SUPPORTED_COLLECTION_SLUG, SUPPORTED_CONTRACT_ADDRESS, validateCanonicalIdentity } from "./identityScope.js";
import { isDecimal, isIso } from "./verifier/targetedVerifierPolicy.js";

export const INITIAL_BASELINE_SOURCE = "active_listings_initial_baseline" as const;
const PLAN_SCHEMA = "initial-baseline-adoption-v1" as const;
const trustedPlans = new WeakSet<object>();
const trustedPlanMaterial = new WeakMap<object, { scope: GenerationWindowScope }>();

export interface InitialBaselineRowPlan {
  readonly orderHash: string; readonly nftId: string; readonly chain: string; readonly contractAddress: string; readonly tokenId: string; readonly collectionSlug: string; readonly sellerAddress: string; readonly priceRaw: string; readonly priceNormalized: string; readonly paymentTokenAddress: string | null; readonly paymentTokenSymbol: string | null; readonly paymentTokenDecimals: number | null; readonly listingStartAt: string; readonly expirationAt: string; readonly protocolAddress: string; readonly rawBaselineListing: unknown;
}
export interface InitialBaselineAdoptionPlanV1 {
  readonly schemaVersion: typeof PLAN_SCHEMA; readonly adoptionId: string; readonly generationPublicationId: string; readonly publicationSequence: number; readonly sweepId: string; readonly sourceEvidenceHash: string; readonly generationRootHash: string; readonly candidateArtifactHash: string; readonly barrierArtifactHash: string; readonly scope: Readonly<GenerationWindowScope>; readonly scopeFingerprint: string; readonly protocolAddress: string; readonly stableWatermark: Readonly<{ eventId: string; receivedAt: string }>; readonly snapshotStartedAt: string; readonly snapshotCompletedAt: string; readonly expectedOrderCount: number; readonly rowsCommitment: string; readonly rows: readonly InitialBaselineRowPlan[];
}

const record = (v: unknown): v is Record<string, any> => v !== null && typeof v === "object" && !Array.isArray(v);
function fail(code: string): never { throw new Error(code); }
function sameIdentity(a: any, b: any): boolean { return canonicalEvidence(a) === canonicalEvidence(b); }
function rowMaterial(listing: any, protocol: string): InitialBaselineRowPlan {
  if (!record(listing) || typeof listing.orderHash !== "string" || typeof listing.nftId !== "string" || typeof listing.sellerAddress !== "string" || !record(listing.price)) fail("INITIAL_BASELINE_IDENTITY_MISMATCH");
  return { orderHash: listing.orderHash, nftId: listing.nftId, chain: listing.chain, contractAddress: listing.contractAddress, tokenId: listing.tokenId, collectionSlug: listing.collectionSlug, sellerAddress: listing.sellerAddress, priceRaw: listing.price.raw, priceNormalized: listing.price.normalizedDecimalString, paymentTokenAddress: null, paymentTokenSymbol: listing.price.currency ?? null, paymentTokenDecimals: listing.price.decimals ?? null, listingStartAt: listing.listingStartAt, expirationAt: listing.expirationAt, protocolAddress: protocol, rawBaselineListing: listing.rawListing };
}
function validateStable(value: any): { eventId: string; receivedAt: string } { if (!record(value) || !isDecimal(value.eventId) || !isIso(value.receivedAt)) fail("INITIAL_BASELINE_STABLE_WATERMARK_INVALID"); return { eventId: value.eventId, receivedAt: String(value.receivedAt) }; }

export function isTrustedInitialBaselineAdoptionPlan(value: unknown): value is InitialBaselineAdoptionPlanV1 { return value !== null && typeof value === "object" && trustedPlans.has(value); }

export function createInitialBaselineAdoptionPlan(input: { evidence: unknown; projection: InitialGenerationBaselineProjection; integratedEvidence: IntegratedEvidenceResult; publication: GenerationPublicationEvidenceV1 }): InitialBaselineAdoptionPlanV1 {
  const { evidence, projection, integratedEvidence, publication } = input;
  let imported: ImportedCompleteEvidence;
  try { imported = importActiveListingsEvidenceObject(evidence, { sourceEvidencePath: projection.evidence.sourceEvidencePath, sweepId: projection.evidence.manifest.sweepId }); } catch { fail("INITIAL_BASELINE_SNAPSHOT_INVALID"); }
  if (canonicalEvidence(imported.manifest) !== canonicalEvidence(projection.evidence.manifest) || canonicalEvidence(imported.seenOrders) !== canonicalEvidence(projection.evidence.seenOrders)) fail("INITIAL_BASELINE_SNAPSHOT_BINDING_MISMATCH");
  if (!isTrustedReconstructedEvidence(integratedEvidence) || integratedEvidence.status !== "VALID" || !validateGenerationPublicationEvidence(publication) || publication.publicationState !== "ACCEPTED") fail("INITIAL_BASELINE_EVIDENCE_UNTRUSTED");
  if (publication.sweepId !== projection.evidence.manifest.sweepId || publication.sweepId !== imported.manifest.sweepId) fail("INITIAL_BASELINE_SWEEP_MISMATCH");
  const candidate: any = integratedEvidence.candidate?.payload;
  const barrier: any = integratedEvidence.barrier?.payload;
  if (!record(candidate) || !validateOfflineCandidateBundle(candidate).valid || !record(barrier) || barrier.state !== "VERIFIED" || barrier.catchUp?.outcome !== "STABLE" || barrier.catchUp?.stable !== true || barrier.finalFence?.outcome !== "FENCE_ELIGIBLE" || barrier.finalFence?.eligible !== true || barrier.deactivationAuthorityGranted !== false) fail("INITIAL_BASELINE_EVIDENCE_UNACCEPTED");
  if (canonicalEvidence(candidate) !== canonicalEvidence(projection.candidateBundle)) fail("INITIAL_BASELINE_CANDIDATE_MISMATCH");
  const scope = createGenerationWindowScopeFromInitialProjection(projection);
  if (publication.scope.protocolAddress !== projection.protocolAddress || publication.scope.chain !== SUPPORTED_CHAIN || publication.scope.contractAddress !== SUPPORTED_CONTRACT_ADDRESS || publication.scope.collectionSlug !== SUPPORTED_COLLECTION_SLUG) fail("INITIAL_BASELINE_PROTOCOL_MISMATCH");
  if (publication.generationRootHash !== integratedEvidence.manifest?.rootContentHash || publication.candidateArtifactHash !== integratedEvidence.candidateRef?.contentHash || publication.barrierArtifactHash !== integratedEvidence.barrierRef?.contentHash || publication.sourceEvidenceHash !== sha256Canonical({ manifest: integratedEvidence.manifest?.rootContentHash, candidate: integratedEvidence.candidateRef?.contentHash, barrier: integratedEvidence.barrierRef?.contentHash, provenance: integratedEvidence.manifest?.sourceProvenance })) fail("INITIAL_BASELINE_PUBLICATION_BINDING_MISMATCH");
  const listings = (evidence as any)?.snapshot?.listings; if (!Array.isArray(listings) || listings.length !== projection.localOrders.length || imported.seenOrders.length !== listings.length) fail("INITIAL_BASELINE_IDENTITY_MISMATCH");
  const rows = listings.map((listing: any) => rowMaterial(listing, projection.protocolAddress)).sort((a: InitialBaselineRowPlan, b: InitialBaselineRowPlan) => a.orderHash.localeCompare(b.orderHash));
  const localByHash = new Map(projection.localOrders.map((o) => [o.orderHash, o])); const candidateByHash = new Map((projection.candidateBundle.orders as any[]).map((o) => [o.orderHash, o]));
  for (const row of rows) { const local = localByHash.get(row.orderHash); const cand = candidateByHash.get(row.orderHash); if (!local || !cand || validateCanonicalIdentity(local.identity) !== "VALID" || !sameIdentity(local.identity, cand.identity) || cand.classification !== "PRESENT" || cand.seenInSweep !== true || cand.authorityGranted !== false) fail("INITIAL_BASELINE_IDENTITY_MISMATCH"); }
  if (rows.length === 0 || rows.length !== localByHash.size || rows.length !== candidateByHash.size) fail("INITIAL_BASELINE_EMPTY_PROJECTION");
  const protocol = new Set(rows.map((r) => r.protocolAddress)); if (protocol.size !== 1 || !ADDRESS_PATTERN.test(projection.protocolAddress) || !projection.protocolAddress || projection.protocolAddress !== [...protocol][0]) fail("INITIAL_BASELINE_PROTOCOL_MISMATCH");
  const stable = validateStable(barrier.catchUp.stableWatermark);
  const rowsCommitment = sha256Canonical({ schema: PLAN_SCHEMA, generationPublicationId: publication.generationPublicationId, scopeFingerprint: scope.scopeFingerprint, protocolAddress: projection.protocolAddress, rows: rows.map((r) => ({ ...r, rawBaselineListingHash: sha256Canonical(r.rawBaselineListing) })) });
  const adoptionId = sha256Canonical({ schema: PLAN_SCHEMA, generationPublicationId: publication.generationPublicationId, sourceEvidenceHash: publication.sourceEvidenceHash, scopeFingerprint: scope.scopeFingerprint, stableWatermark: stable, rowsCommitment });
  const plan = deepFreeze({ schemaVersion: PLAN_SCHEMA, adoptionId, generationPublicationId: publication.generationPublicationId, publicationSequence: publication.publicationSequence, sweepId: publication.sweepId, sourceEvidenceHash: publication.sourceEvidenceHash, generationRootHash: publication.generationRootHash, candidateArtifactHash: publication.candidateArtifactHash, barrierArtifactHash: publication.barrierArtifactHash, scope, scopeFingerprint: scope.scopeFingerprint, protocolAddress: projection.protocolAddress, stableWatermark: stable, snapshotStartedAt: imported.manifest.snapshotStartedAt, snapshotCompletedAt: imported.manifest.snapshotCompletedAt, expectedOrderCount: rows.length, rowsCommitment, rows });
  trustedPlans.add(plan); trustedPlanMaterial.set(plan, { scope }); return plan;
}
export const buildInitialBaselineAdoptionPlan = createInitialBaselineAdoptionPlan;
export const createInitialBaselineAdoption = createInitialBaselineAdoptionPlan;
export type InitialBaselineAdoptionPlan = InitialBaselineAdoptionPlanV1;

export type InitialBaselineAdoptionResult = { outcome: "ADOPTED" | "ALREADY_ADOPTED"; adoptionId: string; adoptedOrderCount: number };
function publicationColumns(): string { return "generation_publication_id,generation_commitment_id,publication_sequence,publication_state,sweep_id,generation_root_hash,candidate_artifact_hash,barrier_artifact_hash,candidate_model_version,generation_model_version,verifier_schema_version,verifier_policy_version,provider_contract_version,normalizer_version,scope,payload,source_evidence_hash,created_at"; }
export class PostgresInitialBaselineAdoptionStore {
  constructor(private readonly pool: DbPool) {}
  async adopt(plan: InitialBaselineAdoptionPlanV1): Promise<InitialBaselineAdoptionResult> {
    if (!isTrustedInitialBaselineAdoptionPlan(plan)) fail("INITIAL_BASELINE_PLAN_UNTRUSTED");
    const client = await this.pool.connect();
    try {
      await client.query("BEGIN"); await client.query("SET LOCAL lock_timeout = '5000ms'");
      const sequence = await client.query("SELECT sequence_key FROM public.targeted_verifier_generation_publication_sequence WHERE sequence_key=$1 FOR UPDATE", ["targeted-verifier-generation"]);
      if (sequence.rows.length !== 1) fail("INITIAL_BASELINE_PUBLICATION_SEQUENCE_UNAVAILABLE");
      await client.query("LOCK TABLE public.opensea_listings_events_v2 IN SHARE ROW EXCLUSIVE MODE");
      await client.query("LOCK TABLE public.opensea_listings_v2 IN SHARE ROW EXCLUSIVE MODE");
      const receipt = await client.query<any>("SELECT * FROM public.opensea_listings_initial_baseline_adoptions WHERE adoption_id=$1", [plan.adoptionId]);
      if (receipt.rows[0]) { let payload: unknown = receipt.rows[0].payload; try { if (typeof payload === "string") payload = JSON.parse(payload); } catch { fail("INITIAL_BASELINE_DURABLE_CORRUPTION"); } if (receipt.rows[0].generation_publication_id !== plan.generationPublicationId || receipt.rows[0].rows_commitment !== plan.rowsCommitment || Number(receipt.rows[0].expected_order_count) !== plan.expectedOrderCount || Number(receipt.rows[0].adopted_order_count) !== plan.expectedOrderCount || canonicalEvidence(payload) !== canonicalEvidence(plan)) fail("INITIAL_BASELINE_DURABLE_CORRUPTION"); const linked = await client.query<{count:string}>("SELECT count(*)::text AS count FROM public.opensea_listings_v2 WHERE initial_baseline_adoption_id=$1", [plan.adoptionId]); if (Number(linked.rows[0]?.count ?? 0) !== plan.expectedOrderCount) fail("INITIAL_BASELINE_DURABLE_CORRUPTION"); await client.query("COMMIT"); return { outcome: "ALREADY_ADOPTED", adoptionId: plan.adoptionId, adoptedOrderCount: plan.expectedOrderCount }; }
      const pubs = await client.query<GenerationPublicationDbRow>(`SELECT ${publicationColumns()} FROM public.targeted_verifier_generation_publications WHERE publication_state='ACCEPTED' AND scope->>'protocolAddress'=$1 ORDER BY publication_sequence DESC FOR UPDATE`, [plan.protocolAddress]);
      const accepted = pubs.rows.map((r) => decodeGenerationPublicationRow(r)).filter((p) => p.publicationState === "ACCEPTED" && canonicalEvidence(p.scope) === canonicalEvidence({ chain: SUPPORTED_CHAIN, collectionSlug: SUPPORTED_COLLECTION_SLUG, contractAddress: SUPPORTED_CONTRACT_ADDRESS, protocolAddress: plan.protocolAddress }));
      if (accepted.length === 0 || accepted[0].generationPublicationId !== plan.generationPublicationId || accepted.some((p, i) => i > 0 && p.publicationSequence === accepted[0].publicationSequence && p.generationPublicationId !== accepted[0].generationPublicationId)) fail("INITIAL_BASELINE_PUBLICATION_NOT_CURRENT");
      const existing = await client.query<{count:string}>("SELECT count(*)::text AS count FROM public.opensea_listings_v2 WHERE chain=$1 AND contract_address=$2 AND collection_slug=$3", [SUPPORTED_CHAIN, SUPPORTED_CONTRACT_ADDRESS, SUPPORTED_COLLECTION_SLUG]); if (Number(existing.rows[0]?.count ?? 0) !== 0) fail("INITIAL_BASELINE_LOCAL_STATE_NOT_EMPTY");
      const after = await client.query<any>("SELECT event_id::text,event_type,processing_status,order_hash,chain,contract_address,token_id FROM public.opensea_listings_events_v2 WHERE event_id > $1::bigint ORDER BY event_id", [plan.stableWatermark.eventId]);
      const nftKeys = new Set(plan.scope.identities.map((i) => `${i.chain}\u0000${i.contractAddress}\u0000${i.tokenId}`));
      for (const row of after.rows) { let relevant = false; if (["item_listed","item_sold","item_cancelled","order_invalidate","order_revalidate"].includes(row.event_type)) { if (row.chain === SUPPORTED_CHAIN) { if (row.contract_address === null || !ADDRESS_PATTERN.test(row.contract_address)) fail("INITIAL_BASELINE_POST_STABLE_EVENT_MALFORMED"); if (row.contract_address === SUPPORTED_CONTRACT_ADDRESS) { if (!row.order_hash || !/^(0x)?[0-9a-f]{64}$/.test(row.order_hash)) fail("INITIAL_BASELINE_POST_STABLE_EVENT_MALFORMED"); relevant = true; } } } else if (row.event_type === "item_transferred") { if (row.chain === SUPPORTED_CHAIN) { if (row.contract_address === null || !ADDRESS_PATTERN.test(row.contract_address)) fail("INITIAL_BASELINE_POST_STABLE_EVENT_MALFORMED"); if (row.contract_address === SUPPORTED_CONTRACT_ADDRESS) { if (!isDecimal(row.token_id)) fail("INITIAL_BASELINE_POST_STABLE_EVENT_MALFORMED"); relevant = nftKeys.has(`${row.chain}\u0000${row.contract_address}\u0000${row.token_id}`); } } } if (relevant) fail("INITIAL_BASELINE_POST_STABLE_EVENT"); }
      const now = await client.query<{now:string}>("SELECT transaction_timestamp()::text AS now"); const adoptedAt = String(now.rows[0]?.now); if (!isIso(adoptedAt)) fail("INITIAL_BASELINE_TIMESTAMP_INVALID"); for (const row of plan.rows) if (Date.parse(row.expirationAt) <= Date.parse(adoptedAt)) fail("INITIAL_BASELINE_SNAPSHOT_EXPIRED");
      await client.query("INSERT INTO public.opensea_listings_initial_baseline_adoptions (schema_version,adoption_id,generation_publication_id,publication_sequence,sweep_id,source_evidence_hash,generation_root_hash,candidate_artifact_hash,barrier_artifact_hash,scope,scope_fingerprint,protocol_address,stable_event_id,stable_received_at,snapshot_started_at,snapshot_completed_at,expected_order_count,adopted_order_count,rows_commitment,payload,adopted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20::jsonb,$21)", [plan.schemaVersion,plan.adoptionId,plan.generationPublicationId,plan.publicationSequence,plan.sweepId,plan.sourceEvidenceHash,plan.generationRootHash,plan.candidateArtifactHash,plan.barrierArtifactHash,JSON.stringify(plan.scope),plan.scopeFingerprint,plan.protocolAddress,plan.stableWatermark.eventId,plan.stableWatermark.receivedAt,plan.snapshotStartedAt,plan.snapshotCompletedAt,plan.expectedOrderCount,plan.expectedOrderCount,plan.rowsCommitment,JSON.stringify(plan),adoptedAt]);
      for (const row of plan.rows) await client.query("INSERT INTO public.opensea_listings_v2 (order_hash,nft_id,chain,contract_address,token_id,collection_slug,seller_address,price_raw,price_normalized,payment_token_address,payment_token_symbol,payment_token_decimals,listing_start_at,expiration_at,status,is_active,needs_reconciliation,reconciliation_reason,last_order_event_type,last_order_event_timestamp,last_order_event_version,last_nft_event_timestamp,last_nft_event_version,last_transfer_transaction_hash,last_stream_received_at,source,last_reconciled_at,created_at,updated_at,raw_last_event,protocol_address,initial_baseline_adoption_id,raw_baseline_listing) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,'active',true,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,$15,$16,$16,$16,$17::jsonb,$18,$19,$20::jsonb)", [row.orderHash,row.nftId,row.chain,row.contractAddress,row.tokenId,row.collectionSlug,row.sellerAddress,row.priceRaw,row.priceNormalized,row.paymentTokenAddress,row.paymentTokenSymbol,row.paymentTokenDecimals,row.listingStartAt,row.expirationAt, INITIAL_BASELINE_SOURCE, adoptedAt, JSON.stringify(null), row.protocolAddress, plan.adoptionId, JSON.stringify(row.rawBaselineListing)]);
      const count = await client.query<{count:string}>("SELECT count(*)::text AS count FROM public.opensea_listings_v2 WHERE initial_baseline_adoption_id=$1", [plan.adoptionId]); if (Number(count.rows[0]?.count ?? 0) !== plan.expectedOrderCount) fail("INITIAL_BASELINE_INSERT_COUNT_MISMATCH"); await client.query("COMMIT"); return { outcome: "ADOPTED", adoptionId: plan.adoptionId, adoptedOrderCount: plan.expectedOrderCount };
    } catch (error) { try { await client.query("ROLLBACK"); } catch {} throw error; } finally { client.release(); }
  }
}
export async function adoptInitialBaseline(pool: DbPool, plan: InitialBaselineAdoptionPlanV1): Promise<InitialBaselineAdoptionResult> { return new PostgresInitialBaselineAdoptionStore(pool).adopt(plan); }
