import test from "node:test";
import assert from "node:assert/strict";
import { createGenerationPublicationEvidence } from "../src/reconciliation/generationPublication.js";
import { activeEvidenceMaterial, CurrentActiveListingsEvidenceSource, deriveActiveListingsEvidence, validateActiveListingsEvidence, type ActiveListingsEvidenceV1 } from "../src/reconciliation/activeListingsEvidence.js";
import { sha256Canonical } from "../src/reconciliation/evidence/canonicalEvidence.js";
import { disposeTrustedContexts, makeTrustedContexts } from "./helpers/trustedVerifierContexts.js";

const identity = (protocolAddress: string, orderHash = "0x" + "a".repeat(64)) => ({ orderHash, chain: "gunzilla" as const, contractAddress: "0x9ed98e159be43a8d42b64053831fcae5e4d7d271", tokenId: "1", collectionSlug: "off-the-grid" as const, protocolAddress });
async function fixture(options: { present?: boolean; blocked?: boolean; protocolAddress?: string; sequence?: number } = {}) { const f = await makeTrustedContexts({ present: options.present, blocked: options.blocked, protocolAddress: options.protocolAddress, skipContexts: true }); const publication = createGenerationPublicationEvidence({ integratedEvidence: f.evidence, protocolAddress: f.protocolAddress, createdAt: "2026-09-14T00:00:00.000Z" }, options.sequence ?? 10); return { ...f, publication, expected: identity(f.protocolAddress) }; }

test("PRESENT derives canonical ACTIVE evidence from trusted reconstructed artifacts", async () => {
  const f = await fixture({ present: true }); try { const result = deriveActiveListingsEvidence({ generationPublication: f.publication, integratedEvidence: f.evidence, expectedIdentity: f.expected }); assert.equal(result.outcome, "VALID"); if (result.outcome === "VALID") { assert.equal(result.evidence.presence, "PRESENT"); assert.equal(result.evidence.status, "ACTIVE"); assert.equal(result.evidence.publicationId, f.publication.generationPublicationId); assert.equal(result.evidence.publicationSequence, 10); assert.equal(result.evidence.sourceArtifactHash, f.publication.candidateArtifactHash); assert.equal(validateActiveListingsEvidence(result.evidence), true); } } finally { await disposeTrustedContexts(f.root); }
});
test("ABSENT_CANDIDATE derives ABSENT/null and BLOCKED never becomes absent", async () => {
  const absent = await fixture(); const blocked = await fixture({ blocked: true }); try { const a = deriveActiveListingsEvidence({ generationPublication: absent.publication, integratedEvidence: absent.evidence, expectedIdentity: absent.expected }); assert.equal(a.outcome, "VALID"); if (a.outcome === "VALID") { assert.equal(a.evidence.presence, "ABSENT"); assert.equal(a.evidence.status, null); } const b = deriveActiveListingsEvidence({ generationPublication: blocked.publication, integratedEvidence: blocked.evidence, expectedIdentity: blocked.expected }); assert.deepEqual(b, { outcome: "UNPROVEN", evidence: null, reasonCodes: ["ACTIVE_EVIDENCE_BLOCKED"] }); } finally { await disposeTrustedContexts(absent.root); await disposeTrustedContexts(blocked.root); }
});
test("publication, identity and trusted-source mismatches fail closed", async () => {
  const current = await fixture({ present: true, protocolAddress: "0x" + "2".repeat(40) }); const old = await fixture({ present: true, protocolAddress: "0x" + "1".repeat(40) }); try { const mismatch = deriveActiveListingsEvidence({ generationPublication: current.publication, integratedEvidence: old.evidence, expectedIdentity: current.expected }); assert.deepEqual(mismatch, { outcome: "UNPROVEN", evidence: null, reasonCodes: ["ACTIVE_EVIDENCE_PUBLICATION_MISMATCH"] }); const missing = deriveActiveListingsEvidence({ generationPublication: current.publication, integratedEvidence: null, expectedIdentity: current.expected }); assert.deepEqual(missing, { outcome: "UNPROVEN", evidence: null, reasonCodes: ["ACTIVE_EVIDENCE_SOURCE_UNAVAILABLE"] }); const wrongToken = deriveActiveListingsEvidence({ generationPublication: current.publication, integratedEvidence: current.evidence, expectedIdentity: { ...current.expected, tokenId: "2" } }); assert.deepEqual(wrongToken, { outcome: "UNPROVEN", evidence: null, reasonCodes: ["ACTIVE_EVIDENCE_IDENTITY_MISMATCH"] }); const wrongProtocol = deriveActiveListingsEvidence({ generationPublication: current.publication, integratedEvidence: current.evidence, expectedIdentity: { ...current.expected, protocolAddress: "0x" + "3".repeat(40) } }); assert.deepEqual(wrongProtocol, { outcome: "UNPROVEN", evidence: null, reasonCodes: ["ACTIVE_EVIDENCE_PUBLICATION_MISMATCH"] }); } finally { await disposeTrustedContexts(current.root); await disposeTrustedContexts(old.root); }
});
test("strict ActiveListingsEvidenceV1 rejects self-consistent semantic tampering", async () => {
  const f = await fixture({ present: true }); try { const result = deriveActiveListingsEvidence({ generationPublication: f.publication, integratedEvidence: f.evidence, expectedIdentity: f.expected }); assert.equal(result.outcome, "VALID"); if (result.outcome !== "VALID") return; const base = result.evidence; const changed = [
      { ...base, presence: "ABSENT" as const, status: null, activeEvidenceId: "" },
      { ...base, presence: "PRESENT" as const, status: "ACTIVE" as const, publicationSequence: base.publicationSequence + 1, activeEvidenceId: "" },
      { ...base, status: null, activeEvidenceId: "" },
      { ...base, tokenId: "2", activeEvidenceId: "" },
      { ...base, sourceScope: { ...base.sourceScope, protocolAddress: "0x" + "3".repeat(40) }, activeEvidenceId: "" }
    ];
    for (const item of changed) { item.activeEvidenceId = sha256Canonical(activeEvidenceMaterial(item)); if (item.tokenId === "2" || item.sourceScope.protocolAddress === "0x" + "3".repeat(40)) { const rejected = deriveActiveListingsEvidence({ generationPublication: f.publication, integratedEvidence: f.evidence, expectedIdentity: { ...f.expected, ...(item.tokenId === "2" ? { tokenId: "2" } : { protocolAddress: "0x" + "3".repeat(40) }) } }); assert.equal(rejected.outcome, "UNPROVEN"); } else if ((item.presence === "ABSENT" && item.status === null) || item.publicationSequence !== base.publicationSequence) { assert.equal(validateActiveListingsEvidence(item), true); } else { assert.equal(validateActiveListingsEvidence(item), false); } }
  } finally { await disposeTrustedContexts(f.root); }
});
test("current source uses only current accepted publication and rejects a mismatching resolver", async () => {
  const current = await fixture({ present: true, protocolAddress: "0x" + "2".repeat(40) }); const historical = await fixture({ present: false, protocolAddress: "0x" + "1".repeat(40) }); try { const store = { getCurrentAcceptedGeneration: async () => ({ outcome: "CURRENT" as const, publication: current.publication }) }; const source = new CurrentActiveListingsEvidenceSource(store, { resolve: async () => historical.evidence }); const result = await source.resolve(current.expected); assert.deepEqual(result, { outcome: "ACTIVE_EVIDENCE_UNPROVEN", evidence: null, reasonCodes: ["ACTIVE_EVIDENCE_PUBLICATION_MISMATCH"] }); const good = new CurrentActiveListingsEvidenceSource(store, { resolve: async () => current.evidence }); const accepted = await good.resolve(current.expected); assert.equal(accepted.outcome, "CURRENT_ACTIVE_EVIDENCE"); if (accepted.outcome === "CURRENT_ACTIVE_EVIDENCE") assert.equal(accepted.evidence.publicationSequence, current.publication.publicationSequence); } finally { await disposeTrustedContexts(current.root); await disposeTrustedContexts(historical.root); }
});
test("current generation unproven and conflict remain closed result states", async () => {
  const f = await fixture({ present: true }); try { const unavailable = new CurrentActiveListingsEvidenceSource({ getCurrentAcceptedGeneration: async () => ({ outcome: "CURRENT_GENERATION_UNPROVEN" as const, publication: null }) }, { resolve: async () => f.evidence }); assert.deepEqual(await unavailable.resolve(f.expected), { outcome: "CURRENT_GENERATION_UNPROVEN", evidence: null, reasonCodes: ["CURRENT_GENERATION_UNPROVEN"] }); const conflict = new CurrentActiveListingsEvidenceSource({ getCurrentAcceptedGeneration: async () => ({ outcome: "CURRENT_GENERATION_CONFLICT" as const, publication: null }) }, { resolve: async () => f.evidence }); assert.deepEqual(await conflict.resolve(f.expected), { outcome: "CURRENT_GENERATION_CONFLICT", evidence: null, reasonCodes: ["CURRENT_GENERATION_CONFLICT"] }); } finally { await disposeTrustedContexts(f.root); }
});
test("strict validator rejects unknown fields and malformed watermark", async () => {
  const f = await fixture({ present: true }); try { const result = deriveActiveListingsEvidence({ generationPublication: f.publication, integratedEvidence: f.evidence, expectedIdentity: f.expected }); assert.equal(result.outcome, "VALID"); if (result.outcome !== "VALID") return; assert.equal(validateActiveListingsEvidence({ ...result.evidence, unexpected: true }), false); const malformed = { ...result.evidence, observationWatermark: { eventId: "01", receivedAt: result.evidence.observationWatermark.receivedAt }, activeEvidenceId: "" }; malformed.activeEvidenceId = sha256Canonical(activeEvidenceMaterial(malformed)); assert.equal(validateActiveListingsEvidence(malformed), false); } finally { await disposeTrustedContexts(f.root); }
});
test("strict validator rejects non-string orderHash values without coercion", async () => {
  const f = await fixture({ present: true }); try { const result = deriveActiveListingsEvidence({ generationPublication: f.publication, integratedEvidence: f.evidence, expectedIdentity: f.expected }); assert.equal(result.outcome, "VALID"); if (result.outcome !== "VALID") return; const candidates: readonly unknown[] = [42, { toString: () => f.expected.orderHash }, [f.expected.orderHash], null]; for (const candidate of candidates) { const malformed = { ...result.evidence, orderHash: candidate } as unknown as ActiveListingsEvidenceV1; try { malformed.activeEvidenceId = sha256Canonical(activeEvidenceMaterial(malformed)); } catch { /* unsupported canonical runtime values are rejected before hashing */ } assert.equal(validateActiveListingsEvidence(malformed), false); } } finally { await disposeTrustedContexts(f.root); }
});
test("current source returns newer same-scope PRESENT over historical ABSENT", async () => {
  const historical = await fixture({ present: false, sequence: 10 }); const current = await fixture({ present: true, sequence: 11 }); try { assert.equal(historical.expected.orderHash, current.expected.orderHash); assert.equal(historical.publication.scope.protocolAddress, current.publication.scope.protocolAddress); const store = { getCurrentAcceptedGeneration: async () => ({ outcome: "CURRENT" as const, publication: current.publication }) }; const byPublication = new Map([[historical.publication.generationPublicationId, historical.evidence], [current.publication.generationPublicationId, current.evidence]]); const source = new CurrentActiveListingsEvidenceSource(store, { resolve: async (publication) => byPublication.get(publication.generationPublicationId) ?? null }); const result = await source.resolve(current.expected); assert.equal(result.outcome, "CURRENT_ACTIVE_EVIDENCE"); if (result.outcome === "CURRENT_ACTIVE_EVIDENCE") { assert.equal(result.evidence.publicationId, current.publication.generationPublicationId); assert.equal(result.evidence.publicationSequence, 11); assert.equal(result.evidence.presence, "PRESENT"); assert.equal(result.evidence.status, "ACTIVE"); assert.notEqual(result.evidence.publicationId, historical.publication.generationPublicationId); assert.notEqual(result.evidence.publicationSequence, 10); assert.notEqual(result.evidence.presence, "ABSENT"); } } finally { await disposeTrustedContexts(historical.root); await disposeTrustedContexts(current.root); }
});
test("same-scope historical resolver evidence fails publication binding", async () => {
  const historical = await fixture({ present: false, sequence: 10 }); const current = await fixture({ present: true, sequence: 11 }); try { const store = { getCurrentAcceptedGeneration: async () => ({ outcome: "CURRENT" as const, publication: current.publication }) }; const source = new CurrentActiveListingsEvidenceSource(store, { resolve: async () => historical.evidence }); assert.deepEqual(await source.resolve(current.expected), { outcome: "ACTIVE_EVIDENCE_UNPROVEN", evidence: null, reasonCodes: ["ACTIVE_EVIDENCE_PUBLICATION_MISMATCH"] }); } finally { await disposeTrustedContexts(historical.root); await disposeTrustedContexts(current.root); }
});
test("missing valid canonical order is rejected as ORDER_NOT_FOUND", async () => {
  const f = await fixture({ present: true }); try { const missing = deriveActiveListingsEvidence({ generationPublication: f.publication, integratedEvidence: f.evidence, expectedIdentity: identity(f.protocolAddress, "0x" + "c".repeat(64)) }); assert.deepEqual(missing, { outcome: "UNPROVEN", evidence: null, reasonCodes: ["ACTIVE_EVIDENCE_ORDER_NOT_FOUND"] }); } finally { await disposeTrustedContexts(f.root); }
});
