import assert from "node:assert/strict";
import { access, constants, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { runProbe } from "../scripts/runActiveListingsProbe.ts";
import { sha256File } from "../src/activeListings.js";

const root = fileURLToPath(new URL("../", import.meta.url));
const sourceFiles = [path.join(root, "src/activeListings.ts"), path.join(root, "scripts/runActiveListingsProbe.ts"), path.join(root, "package.json")];
const base = ["--output-file", "placeholder", "--limit", "10", "--max-pages", "2", "--max-listings", "10", "--timeout-ms", "1000", "--max-retries", "0", "--inter-page-delay-ms", "0", "--confirm-read-only", "--confirm-no-database", "--confirm-one-shot"];
const snapshot = (result: "COMPLETE" | "PARTIAL" | "FAILED" | "UNSAFE") => ({ result, startedAt: "2026-08-22T00:00:00.000Z", completedAt: "2026-08-22T00:00:01.000Z", endpoint: "https://api.opensea.io/api/v2/listings/collection/off-the-grid/all", collectionSlug: "off-the-grid" as const, expectedChain: "gunzilla" as const, expectedContract: "0x9ed98e159be43a8d42b64053831fcae5e4d7d271" as const, pageAttempts: 1, pagesFetched: 1, httpAttempts: 1, retryAttempts: 0, counters: { observed: 1, normalized: 1, malformed: 0, unsupported: 0, duplicates: 0, conflicts: 0 }, paginationExhausted: result === "COMPLETE", cursorCycleDetected: false, repeatedPageDetected: false, truncatedByPageLimit: false, truncatedByListingLimit: false, listings: [], rawPages: [{ safe: true }], nextCursor: null, warnings: [], errors: [], responseHashes: [], sourceProvenance: {} });

async function fixture(): Promise<{ directory: string; output: string; argv: string[]; env: NodeJS.ProcessEnv }> {
  const directory = await mkdtemp(path.join(os.tmpdir(), "otg-probe-"));
  const output = path.join(directory, "evidence.json");
  return { directory, output, argv: base.map((value) => value === "placeholder" ? output : value), env: { OPENSEA_API_KEY: "test-secret-key" } };
}
function deps(fetchResult: ReturnType<typeof snapshot>, calls: { count: number }, logs: string[] = []) {
  return { sourceFiles, clientFactory: () => ({ fetchSnapshot: async () => { calls.count += 1; return fetchResult; } }), log: (line: string) => logs.push(line) };
}

for (const [name, arg] of [["missing output", "--output-file"], ["unknown arg", "--unknown"], ["missing read-only gate", "--confirm-read-only"], ["missing database gate", "--confirm-no-database"], ["missing one-shot gate", "--confirm-one-shot"]] as const) {
  test(`preflight rejects ${name} before network`, async () => {
    const f = await fixture(); const calls = { count: 0 }; const argv = arg === "--unknown" ? [...depsArgs(f), arg] : depsArgs(f).filter((value) => value !== arg);
    const result = await runProbe(argv, f.env, deps(snapshot("COMPLETE"), calls)); assert.equal(result.status, "PREFLIGHT_FAILED"); assert.equal(calls.count, 0); await rm(f.directory, { recursive: true, force: true });
  });
}
function depsArgs(f: { argv: string[] }) { return f.argv; }

test("missing API key fails before network and CLI key is unknown", async () => { const f = await fixture(); const calls = { count: 0 }; const missing = await runProbe(f.argv, {}, deps(snapshot("COMPLETE"), calls)); assert.equal(missing.exitCode, 1); assert.equal(calls.count, 0); const cli = await runProbe([...f.argv, "--api-key", "secret"], f.env, deps(snapshot("COMPLETE"), calls)); assert.equal(cli.status, "PREFLIGHT_FAILED"); assert.equal(calls.count, 0); await rm(f.directory, { recursive: true, force: true }); });
for (const [name, flag, value] of [["limit", "--limit", "0"], ["maxPages", "--max-pages", "1001"], ["maxListings", "--max-listings", "100001"], ["timeout", "--timeout-ms", "999"], ["retries", "--max-retries", "11"], ["inter-page-delay", "--inter-page-delay-ms", "60001"], ["inter-page-delay-fraction", "--inter-page-delay-ms", "1.5"]] as const) {
  test(`invalid ${name} fails before network`, async () => { const f = await fixture(); const argv = [...f.argv]; argv[argv.indexOf(flag) + 1] = value; const calls = { count: 0 }; const result = await runProbe(argv, f.env, deps(snapshot("COMPLETE"), calls)); assert.equal(result.status, "PREFLIGHT_FAILED"); assert.equal(calls.count, 0); await rm(f.directory, { recursive: true, force: true }); });
}

for (const resultKind of ["COMPLETE", "PARTIAL", "FAILED", "UNSAFE"] as const) {
  test(`${resultKind} maps exit and writes one evidence document`, async () => { const f = await fixture(); const calls = { count: 0 }; const logs: string[] = []; const result = await runProbe(f.argv, f.env, deps(snapshot(resultKind), calls, logs)); assert.equal(calls.count, 1); assert.equal(result.status, `PROBE_${resultKind}`); assert.equal(result.exitCode, resultKind === "COMPLETE" ? 0 : resultKind === "PARTIAL" ? 2 : resultKind === "FAILED" ? 3 : 4); const evidence = JSON.parse(await readFile(f.output, "utf8")); assert.equal(evidence.operatorVersion, "1.0.0"); assert.equal(evidence.snapshot.result, resultKind); assert.equal(evidence.requestConfiguration.interPageDelayMs, 0); assert.deepEqual(Object.keys(evidence.sourceProvenance).sort(), sourceFiles.slice().sort()); assert.ok(logs[0].includes("PROBE_")); await rm(f.directory, { recursive: true, force: true }); });
}

test("existing output is rejected before network and second use is safe", async () => { const f = await fixture(); await writeFile(f.output, "existing", "utf8"); const calls = { count: 0 }; const result = await runProbe(f.argv, f.env, deps(snapshot("COMPLETE"), calls)); assert.equal(result.status, "PREFLIGHT_FAILED"); assert.equal(calls.count, 0); await rm(f.directory, { recursive: true, force: true }); });
for (const relativePath of ["evidence.json", ".\\evidence.json", "..\\evidence.json"] as const) {
  test(`relative output path ${JSON.stringify(relativePath)} fails before normalization and network`, async () => {
    const f = await fixture(); const calls = { count: 0 }; const argv = [...f.argv]; argv[argv.indexOf(f.output)] = relativePath;
    const resolvedRelativePath = path.resolve(relativePath); const result = await runProbe(argv, f.env, deps(snapshot("COMPLETE"), calls));
    assert.equal(result.status, "PREFLIGHT_FAILED"); assert.equal(result.exitCode, 1); assert.equal(calls.count, 0); await assert.rejects(() => access(resolvedRelativePath, constants.F_OK)); await rm(f.directory, { recursive: true, force: true });
  });
}
test("absolute output path reaches the fake client and preserves evidence path", async () => { const f = await fixture(); const calls = { count: 0 }; const result = await runProbe(f.argv, f.env, deps(snapshot("COMPLETE"), calls)); assert.equal(result.status, "PROBE_COMPLETE"); assert.equal(result.evidencePath, f.output); assert.equal(calls.count, 1); await rm(f.directory, { recursive: true, force: true }); });
test("missing absolute output parent is rejected before network", async () => { const f = await fixture(); const missingParentOutput = path.join(f.directory, "missing-parent", "evidence.json"); const argv = [...f.argv]; argv[argv.indexOf(f.output)] = missingParentOutput; const calls = { count: 0 }; const result = await runProbe(argv, f.env, deps(snapshot("COMPLETE"), calls)); assert.equal(result.status, "PREFLIGHT_FAILED"); assert.equal(calls.count, 0); await assert.rejects(() => access(missingParentOutput, constants.F_OK)); await rm(f.directory, { recursive: true, force: true }); });
test("evidence writer failure is nonzero", async () => { const f = await fixture(); const calls = { count: 0 }; const result = await runProbe(f.argv, f.env, { ...deps(snapshot("COMPLETE"), calls), writeEvidence: async () => { throw new Error("write_failed"); } }); assert.equal(result.status, "EVIDENCE_FAILED"); assert.equal(result.exitCode, 5); assert.equal(calls.count, 1); await rm(f.directory, { recursive: true, force: true }); });
for (const resultKind of ["COMPLETE", "PARTIAL", "FAILED", "UNSAFE"] as const) {
  test(`client cleanup runs after ${resultKind}`, async () => { const f = await fixture(); let closed = 0; const result = await runProbe(f.argv, f.env, { ...deps(snapshot(resultKind), { count: 0 }), clientFactory: () => ({ fetchSnapshot: async () => snapshot(resultKind), close: async () => { closed += 1; } }) }); assert.equal(result.status, `PROBE_${resultKind}`); assert.equal(closed, 1); await rm(f.directory, { recursive: true, force: true }); });
}
test("client cleanup runs when snapshot throws and evidence is still deterministic", async () => { const f = await fixture(); let closed = 0; const result = await runProbe(f.argv, f.env, { ...deps(snapshot("COMPLETE"), { count: 0 }), clientFactory: () => ({ fetchSnapshot: async () => { throw new Error("transport_failed"); }, close: async () => { closed += 1; } }) }); assert.equal(result.status, "PROBE_FAILED"); assert.equal(closed, 1); assert.equal(JSON.parse(await readFile(f.output, "utf8")).snapshot.result, "FAILED"); await rm(f.directory, { recursive: true, force: true }); });
test("cleanup failure is non-success and does not overwrite evidence", async () => { const f = await fixture(); const result = await runProbe(f.argv, f.env, { ...deps(snapshot("COMPLETE"), { count: 0 }), clientFactory: () => ({ fetchSnapshot: async () => snapshot("COMPLETE"), close: async () => { throw new Error("close_failed"); } }) }); assert.equal(result.status, "EVIDENCE_FAILED"); assert.equal(result.exitCode, 5); assert.equal(JSON.parse(await readFile(f.output, "utf8")).snapshot.result, "COMPLETE"); await rm(f.directory, { recursive: true, force: true }); });
test("unexpected evidence construction failure still closes client exactly once", async () => { const f = await fixture(); const raw = snapshot("COMPLETE") as any; const circular: any = {}; circular.self = circular; raw.rawPages = [circular]; let closed = 0; const result = await runProbe(f.argv, f.env, { ...deps(raw, { count: 0 }), clientFactory: () => ({ fetchSnapshot: async () => raw, close: async () => { closed += 1; } }) }); assert.equal(result.status, "EVIDENCE_FAILED"); assert.equal(result.exitCode, 5); assert.equal(closed, 1); await assert.rejects(() => access(f.output, constants.F_OK)); await rm(f.directory, { recursive: true, force: true }); });
test("main failure and cleanup failure remain deterministic", async () => { const f = await fixture(); let closed = 0; const result = await runProbe(f.argv, f.env, { ...deps(snapshot("COMPLETE"), { count: 0 }), clientFactory: () => ({ fetchSnapshot: async () => { throw new Error("main_failed"); }, close: async () => { closed += 1; throw new Error("close_failed"); } }) }); assert.equal(result.status, "EVIDENCE_FAILED"); assert.equal(result.exitCode, 5); assert.equal(closed, 1); const evidence = JSON.parse(await readFile(f.output, "utf8")); assert.equal(evidence.snapshot.result, "FAILED"); await rm(f.directory, { recursive: true, force: true }); });
test("provenance failure blocks network", async () => { const f = await fixture(); const calls = { count: 0 }; const result = await runProbe(f.argv, f.env, { ...deps(snapshot("COMPLETE"), calls), hashFile: async () => { throw new Error("unreadable"); } }); assert.equal(result.status, "PREFLIGHT_FAILED"); assert.equal(calls.count, 0); await rm(f.directory, { recursive: true, force: true }); });
test("secret is absent from evidence, summary and errors", async () => { const f = await fixture(); const calls = { count: 0 }; const logs: string[] = []; const raw = snapshot("FAILED"); raw.rawPages = [{ "x-api-key": "test-secret-key", value: "test-secret-key" }]; raw.errors = ["authorization: test-secret-key"]; const result = await runProbe(f.argv, f.env, deps(raw, calls, logs)); const evidence = await readFile(f.output, "utf8"); assert.equal(result.exitCode, 3); assert.ok(!evidence.includes("test-secret-key")); assert.ok(!logs.join("\n").includes("test-secret-key")); await rm(f.directory, { recursive: true, force: true }); });
test("source provenance manifest is deterministic and exclusive-create rejects reuse", async () => { const f = await fixture(); const calls = { count: 0 }; const first = await runProbe(f.argv, f.env, deps(snapshot("COMPLETE"), calls)); assert.equal(first.exitCode, 0); const second = await runProbe(f.argv, f.env, deps(snapshot("COMPLETE"), calls)); assert.equal(second.status, "PREFLIGHT_FAILED"); assert.equal(calls.count, 1); for (const file of sourceFiles) assert.match(await sha256File(file), /^[0-9a-f]{64}$/); await rm(f.directory, { recursive: true, force: true }); });

test("operator source has no forbidden runtime systems, SQL, timers, or import-time network", async () => { const source = await readFile(path.join(root, "scripts/runActiveListingsProbe.ts"), "utf8"); assert.doesNotMatch(source, /from ["'].*(?:pg|repository|worker|stream|backfill|reconciliation|Tx)/i); assert.doesNotMatch(source, /\b(?:INSERT\s+INTO|UPDATE\s+\w|DELETE\s+FROM|setInterval|setTimeout|fetch\s*\()/i); });
test("package command is isolated and lifecycle commands are unchanged", async () => { const pkg = JSON.parse(await readFile(path.join(root, "package.json"), "utf8")); assert.equal(pkg.scripts["probe:active-listings"], "tsx scripts/runActiveListingsProbe.ts"); assert.ok(!String(pkg.scripts.build).includes("probe:active-listings")); assert.ok(!String(pkg.scripts.test).includes("probe:active-listings")); assert.ok(!String(pkg.scripts.start).includes("probe:active-listings")); });
