import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { performance } from "node:perf_hooks";
import { ACTIVE_LISTINGS_CONTRACT, ACTIVE_LISTINGS_ENDPOINT, ActiveListingsClient, normalizeActiveListing, sha256File, writeActiveListingsEvidenceExclusive } from "../src/activeListings.js";

class HeadersMap { constructor(private readonly values: Record<string, string> = {}) {} get(name: string): string | null { return this.values[name] ?? this.values[name.toLowerCase()] ?? null; } }
function response(body: unknown, status = 200, headers: Record<string, string> = {}) { return { ok: status >= 200 && status < 300, status, headers: new HeadersMap(headers), async text() { return JSON.stringify(body); } }; }
const TOKEN = "9007199254740993";
const SELLER = "0x2222222222222222222222222222222222222222";
const FEE_ONE = "0x3333333333333333333333333333333333333333";
const FEE_TWO = "0x4444444444444444444444444444444444444444";
function listing(overrides: Record<string, unknown> = {}): any { const base = { order_hash: "0x1111111111111111111111111111111111111111111111111111111111111111", chain: "gunzilla", protocol_data: { parameters: { offerer: SELLER, offer: [{ itemType: 2, token: ACTIVE_LISTINGS_CONTRACT, identifierOrCriteria: TOKEN, startAmount: "1", endAmount: "1" }], consideration: [{ itemType: 0, token: "0x0000000000000000000000000000000000000000", identifierOrCriteria: "0", startAmount: "1150000000000000000", endAmount: "1150000000000000000", recipient: SELLER }, { itemType: 0, token: "0x0000000000000000000000000000000000000000", identifierOrCriteria: "0", startAmount: "50000000000000000", endAmount: "50000000000000000", recipient: FEE_ONE }, { itemType: 0, token: "0x0000000000000000000000000000000000000000", identifierOrCriteria: "0", startAmount: "34500000000000000", endAmount: "34500000000000000", recipient: FEE_TWO }], startTime: "1787323440", endTime: "1789915440", orderType: 0 }, signature: null }, protocol_address: "0x00000000006687982678b03100b9bdc8be440814", asset: { identifier: TOKEN, contract: ACTIVE_LISTINGS_CONTRACT }, remaining_quantity: 1, order_created_at: 1787323444, price: { current: { currency: "GUN", decimals: 18, value: "1234500000000000000" } }, type: "basic", status: "ACTIVE" }; return { ...base, ...overrides }; }
function changed(mutator: (value: any) => void): any { const value = structuredClone(listing()); mutator(value); return value; }
function makeClient(fetch: (url: string, init: any) => Promise<any>, options: any = {}, dependencies: any = {}) { const { maxRetries = 2, ...policyOptions } = options; return new ActiveListingsClient({ apiKey: "secret-api-key", dependencies: { fetch, sleep: async () => undefined, ...dependencies }, policy: { maxPages: 5, maxListings: 10, ...policyOptions }, retryPolicy: { maxRetries } }); }
async function unsafe(row: any, options: any = {}) { return makeClient(async () => response({ listings: [row], next: null }), options).fetchSnapshot(); }

test("exact endpoint, header-only API key, and fixed public-listing query", async () => { let url = ""; let init: any; const result = await makeClient(async (requestUrl, requestInit) => { url = requestUrl; init = requestInit; return response({ listings: [], next: null }); }).fetchSnapshot(); assert.equal(result.result, "COMPLETE"); const parsed = new URL(url); assert.equal(`${parsed.origin}${parsed.pathname}`, ACTIVE_LISTINGS_ENDPOINT); assert.equal(parsed.searchParams.get("limit"), "200"); assert.equal(parsed.searchParams.get("include_private_listings"), "false"); assert.equal(parsed.searchParams.get("api_key"), null); assert.equal(init.method, "GET"); assert.equal(init.headers["X-API-KEY"], "secret-api-key"); assert.equal(url.includes("secret-api-key"), false); });
test("bounds are finite and slug cannot be overridden", () => { assert.throws(() => makeClient(async () => response({ listings: [], next: null }), { pageLimit: 0 }), /pageLimit/); assert.throws(() => makeClient(async () => response({ listings: [], next: null }), { pageLimit: 201 }), /pageLimit/); assert.throws(() => makeClient(async () => response({ listings: [], next: null }), { maxPages: 0 }), /maxPages/); assert.throws(() => makeClient(async () => response({ listings: [], next: null }), { maxListings: 0 }), /maxListings/); });
test("real OTG one-page shape normalizes completely", () => { const value = normalizeActiveListing(listing()); assert.equal(value.tokenId, TOKEN); assert.equal(value.contractAddress, ACTIVE_LISTINGS_CONTRACT); assert.equal(value.sellerAddress, SELLER); assert.equal(value.price.raw, "1234500000000000000"); assert.equal(value.price.normalizedDecimalString, "1.2345"); assert.equal(value.listingStartAt, "2026-08-21T14:44:00.000Z"); assert.equal(value.expirationAt, "2026-09-20T14:44:00.000Z"); assert.equal(value.orderCreatedAt, "2026-08-21T14:44:04.000Z"); });
test("real OTG shape reaches COMPLETE and preserves raw listing", async () => { const result = await makeClient(async () => response({ listings: [listing()], next: null })).fetchSnapshot(); assert.equal(result.result, "COMPLETE"); assert.equal(result.counters.normalized, 1); assert.deepEqual(result.listings[0].rawListing, listing()); });

for (const [name, mutate] of [["missing asset", (v: any) => { delete v.asset; }], ["missing asset identifier", (v: any) => { delete v.asset.identifier; }], ["missing asset contract", (v: any) => { delete v.asset.contract; }], ["wrong asset contract", (v: any) => { v.asset.contract = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"; }], ["wrong chain", (v: any) => { v.chain = "ethereum"; }], ["missing offer", (v: any) => { delete v.protocol_data.parameters.offer; }], ["empty offer", (v: any) => { v.protocol_data.parameters.offer = []; }], ["multiple offers", (v: any) => { v.protocol_data.parameters.offer.push(structuredClone(v.protocol_data.parameters.offer[0])); }], ["wrong itemType", (v: any) => { v.protocol_data.parameters.offer[0].itemType = 1; }], ["offer token mismatch", (v: any) => { v.protocol_data.parameters.offer[0].token = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"; }], ["offer identifier mismatch", (v: any) => { v.protocol_data.parameters.offer[0].identifierOrCriteria = "123"; }], ["wildcard criteria", (v: any) => { v.protocol_data.parameters.offer[0].identifierOrCriteria = "*"; }], ["offer start amount mismatch", (v: any) => { v.protocol_data.parameters.offer[0].startAmount = "2"; }], ["offer end amount mismatch", (v: any) => { v.protocol_data.parameters.offer[0].endAmount = "2"; }], ["missing offerer", (v: any) => { delete v.protocol_data.parameters.offerer; }], ["invalid offerer", (v: any) => { v.protocol_data.parameters.offerer = "not-an-address"; }], ["invalid price value", (v: any) => { v.price.current.value = "1.2"; }], ["invalid decimals", (v: any) => { v.price.current.decimals = 17; }], ["invalid currency", (v: any) => { v.price.current.currency = "USD"; }], ["invalid start epoch", (v: any) => { v.protocol_data.parameters.startTime = "1787.5"; }], ["invalid end epoch", (v: any) => { v.protocol_data.parameters.endTime = "not-an-epoch"; }], ["unsafe created epoch", (v: any) => { v.order_created_at = Number.MAX_SAFE_INTEGER + 1; }], ["start after end", (v: any) => { v.protocol_data.parameters.startTime = "1789915441"; }], ["non-active status", (v: any) => { v.status = "CANCELLED"; }], ["unsupported type", (v: any) => { v.type = "criteria"; }], ["remaining quantity not one", (v: any) => { v.remaining_quantity = 2; }], ["consideration mismatch", (v: any) => { v.protocol_data.parameters.consideration[0].startAmount = "1"; }], ["consideration range mismatch", (v: any) => { v.protocol_data.parameters.consideration[0].endAmount = "2"; }]] as const) { test(`${name} fails closed`, async () => { const result = await unsafe(changed(mutate)); assert.equal(result.result, "UNSAFE"); assert.equal(result.counters.normalized, 0); }); }
test("numeric identifierOrCriteria without asset proof remains blocked", async () => { const value = changed((v) => { delete v.asset; v.protocol_data.parameters.offer[0].identifierOrCriteria = "48804193"; }); const result = await unsafe(value); assert.equal(result.result, "UNSAFE"); assert.equal(result.counters.normalized, 0); });
test("missing and invalid order hash fail closed", async () => { assert.equal((await unsafe(changed((v) => { delete v.order_hash; }))).result, "UNSAFE"); assert.equal((await unsafe(changed((v) => { v.order_hash = 123; }))).result, "UNSAFE"); });
test("private listing remains fail closed", async () => { assert.equal((await unsafe(changed((v) => { v.is_private = true; }))).result, "UNSAFE"); });

test("one-page and multi-page cursor exhaustion are COMPLETE", async () => { const one = await makeClient(async () => response({ listings: [listing()], next: null })).fetchSnapshot("2026-08-22T12:00:00.000Z"); assert.equal(one.result, "COMPLETE"); assert.equal(one.paginationExhausted, true); let calls = 0; const urls: string[] = []; const many = await makeClient(async (url) => { urls.push(url); calls += 1; const second = listing({ order_hash: "0x3333333333333333333333333333333333333333333333333333333333333333", asset: { identifier: "2", contract: ACTIVE_LISTINGS_CONTRACT } }); second.protocol_data.parameters.offer[0].identifierOrCriteria = "2"; return response(calls === 1 ? { listings: [listing()], next: "cursor-1" } : { listings: [second], next: null }); }).fetchSnapshot(); assert.equal(many.result, "COMPLETE"); assert.equal(many.pagesFetched, 2); assert.equal(new URL(urls[1]).searchParams.get("next"), "cursor-1"); });
test("max pages, max listings and cursor cycle never become COMPLETE", async () => { const limitedPages = await makeClient(async () => response({ listings: [], next: "next" }), { maxPages: 1 }).fetchSnapshot(); assert.equal(limitedPages.result, "PARTIAL"); assert.equal(limitedPages.truncatedByPageLimit, true); const limitedListings = await makeClient(async () => response({ listings: [listing()], next: "next" }), { maxListings: 1 }).fetchSnapshot(); assert.equal(limitedListings.result, "PARTIAL"); assert.equal(limitedListings.truncatedByListingLimit, true); let calls = 0; const cycle = await makeClient(async () => { calls += 1; return response(calls === 1 ? { listings: [], next: "same" } : { listings: [listing()], next: "same" }); }).fetchSnapshot(); assert.equal(cycle.result, "PARTIAL"); assert.equal(cycle.cursorCycleDetected, true); });
test("transport failures and bounded retries preserve result semantics", async () => { const failed = await makeClient(async () => response({ error: "down" }, 503), { maxRetries: 0 }).fetchSnapshot(); assert.equal(failed.result, "FAILED"); let calls = 0; const partial = await makeClient(async () => { calls += 1; return calls === 1 ? response({ listings: [listing()], next: "next" }) : response({ error: "down" }, 503); }, { maxRetries: 0 }).fetchSnapshot(); assert.equal(partial.result, "PARTIAL"); assert.equal(partial.counters.normalized, 1); });
test("pacing occurs only between successful pages", async () => { let calls = 0; const waits: number[] = []; const client = makeClient(async () => { calls += 1; const row = changed((v) => { v.order_hash = `0x${String(calls).padStart(64, "0")}`; v.asset.identifier = String(calls); v.protocol_data.parameters.offer[0].identifierOrCriteria = String(calls); }); return response({ listings: [row], next: calls === 1 ? "cursor-1" : null }); }, { interPageDelayMs: 25 }, { sleep: async (ms: number) => { waits.push(ms); } }); const result = await client.fetchSnapshot(); assert.equal(result.result, "COMPLETE"); assert.deepEqual(waits, [25]); assert.equal(result.pageAttempts, 2); assert.equal(result.pagesFetched, 2); });
test("production default sleep is a real awaitable timer", async () => { let calls = 0; const client = new ActiveListingsClient({ apiKey: "secret-api-key", dependencies: { fetch: async () => { calls += 1; const row = changed((v) => { v.order_hash = `0x${String(calls).padStart(64, "0")}`; v.asset.identifier = String(calls); v.protocol_data.parameters.offer[0].identifierOrCriteria = String(calls); }); return response({ listings: [row], next: calls === 1 ? "cursor-1" : null }); } }, policy: { maxPages: 2, maxListings: 10, interPageDelayMs: 50 }, retryPolicy: { maxRetries: 0 } }); const started = performance.now(); const result = await client.fetchSnapshot(); const elapsed = performance.now() - started; await client.close(); assert.equal(result.result, "COMPLETE"); assert.equal(calls, 2); assert.ok(elapsed >= 35, `expected real default delay, observed ${elapsed.toFixed(1)}ms`); });
test("production default sleep applies exactly two real waits across three pages", async () => { let calls = 0; const client = new ActiveListingsClient({ apiKey: "secret-api-key", dependencies: { fetch: async () => { calls += 1; const row = changed((v) => { v.order_hash = `0x${String(calls).padStart(64, "0")}`; v.asset.identifier = String(calls); v.protocol_data.parameters.offer[0].identifierOrCriteria = String(calls); }); return response({ listings: [row], next: calls < 3 ? `cursor-${calls}` : null }); } }, policy: { maxPages: 3, maxListings: 10, interPageDelayMs: 40 }, retryPolicy: { maxRetries: 0 } }); const started = performance.now(); const result = await client.fetchSnapshot(); const elapsed = performance.now() - started; await client.close(); assert.equal(result.result, "COMPLETE"); assert.equal(calls, 3); assert.ok(elapsed >= 65, `expected two real waits, observed ${elapsed.toFixed(1)}ms`); });
test("429 retry honors Retry-After and preserves the same cursor", async () => { let calls = 0; const urls: string[] = []; const waits: number[] = []; const client = makeClient(async (url) => { calls += 1; urls.push(url); return calls === 1 ? response({ error: "rate" }, 429, { "retry-after": "2" }) : response({ listings: [listing()], next: null }); }, { maxRetries: 1 }, { sleep: async (ms: number) => { waits.push(ms); } }); const result = await client.fetchSnapshot(); assert.equal(result.result, "COMPLETE"); assert.equal(result.pageAttempts, 1); assert.equal(result.pagesFetched, 1); assert.equal(result.httpAttempts, 2); assert.equal(result.retryAttempts, 1); assert.deepEqual(waits, [2000]); assert.equal(urls[0], urls[1]); assert.equal(result.pageAttemptDetails[0].retryAfterUsed, true); });
test("invalid Retry-After uses bounded fallback and 5xx retry remains same cursor", async () => { let calls = 0; const urls: string[] = []; const waits: number[] = []; const client = makeClient(async (url) => { calls += 1; urls.push(url); return calls === 1 ? response({ error: "down" }, 503, { "retry-after": "invalid" }) : response({ listings: [listing()], next: null }); }, { maxRetries: 1 }, { sleep: async (ms: number) => { waits.push(ms); }, random: () => 0 }); const result = await client.fetchSnapshot(); assert.equal(result.result, "COMPLETE"); assert.deepEqual(waits, [1000]); assert.equal(urls[0], urls[1]); assert.equal(result.pageAttemptDetails[0].retryAfterUsed, false); });
test("network transient retry preserves the same cursor", async () => { let calls = 0; const urls: string[] = []; const client = makeClient(async (url) => { calls += 1; urls.push(url); if (calls === 1) throw new Error("socket_reset"); return response({ listings: [listing()], next: null }); }, { maxRetries: 1 }, { sleep: async () => undefined }); const result = await client.fetchSnapshot(); assert.equal(result.result, "COMPLETE"); assert.equal(result.httpAttempts, 2); assert.equal(result.retryAttempts, 1); assert.equal(urls[0], urls[1]); });
test("retry exhaustion preserves the last successful cursor and failed response is not normalized", async () => { let calls = 0; const result = await makeClient(async () => { calls += 1; return calls === 1 ? response({ listings: [listing()], next: "cursor-1" }) : response({ error: "rate" }, 429); }, { maxRetries: 1 }).fetchSnapshot(); assert.equal(result.result, "PARTIAL"); assert.equal(result.pagesFetched, 1); assert.equal(result.pageAttempts, 2); assert.equal(result.httpAttempts, 3); assert.equal(result.retryAttempts, 1); assert.equal(result.nextCursor, "cursor-1"); assert.equal(result.rawPages.length, 1); assert.equal(result.counters.normalized, 1); });
test("all page and HTTP accounting invariants are explicit", async () => { let calls = 0; const result = await makeClient(async () => { calls += 1; const row = changed((v) => { v.order_hash = `0x${String(calls).padStart(64, "0")}`; v.asset.identifier = String(calls); v.protocol_data.parameters.offer[0].identifierOrCriteria = String(calls); }); return response({ listings: [row], next: calls === 1 ? "cursor-1" : null }); }, { maxRetries: 0 }).fetchSnapshot(); assert.equal(result.pageAttempts, 2); assert.equal(result.pagesFetched, 2); assert.equal(result.httpAttempts, 2); assert.equal(result.retryAttempts, 0); assert.equal(result.pagesFetched, result.rawPages.length); assert.equal(result.pagesFetched, result.responseHashes.length); });
test("owned transport lifecycle close is idempotent without a network request", async () => { const client = new ActiveListingsClient({ apiKey: "secret-api-key", policy: { maxPages: 1, maxListings: 1, interPageDelayMs: 0 } }); await client.close(); await client.close(); });
test("malformed JSON and response shape are not complete", async () => { const malformed = await makeClient(async () => ({ ok: true, status: 200, headers: new HeadersMap(), async text() { return "not-json"; } })).fetchSnapshot(); assert.equal(malformed.result, "FAILED"); const shape = await makeClient(async () => response({ events: [], next: null })).fetchSnapshot(); assert.equal(shape.result, "FAILED"); });

test("same NFT with five distinct order hashes preserves all orders", async () => { const rows = Array.from({ length: 5 }, (_, index) => changed((v) => { v.order_hash = `0x${String(index + 1).padStart(64, "0")}`; })); const result = await makeClient(async () => response({ listings: rows, next: null }), { maxListings: 10 }).fetchSnapshot(); assert.equal(result.result, "COMPLETE"); assert.equal(result.listings.length, 5); assert.deepEqual(result.listings.map((v) => v.orderHash), rows.map((v) => v.order_hash)); });
test("same order hash equivalent duplicate and material conflict semantics remain", async () => { const equivalent = listing(); const duplicate = await makeClient(async () => response({ listings: [equivalent, structuredClone(equivalent)], next: null })).fetchSnapshot(); assert.equal(duplicate.result, "COMPLETE"); assert.equal(duplicate.counters.duplicates, 1); const conflicting = changed((v) => { v.price.current.value = "1234500000000000001"; v.protocol_data.parameters.consideration[0].startAmount = "1150000000000000001"; v.protocol_data.parameters.consideration[0].endAmount = "1150000000000000001"; }); const conflict = await makeClient(async () => response({ listings: [listing(), conflicting], next: null })).fetchSnapshot(); assert.equal(conflict.result, "UNSAFE"); assert.equal(conflict.counters.conflicts, 1); });
test("criteria safety and real asset identity are intentionally distinct", () => { assert.throws(() => normalizeActiveListing(changed((v) => { v.asset.identifier = "*"; v.protocol_data.parameters.offer[0].identifierOrCriteria = "*"; })), /token_id_invalid/); assert.equal(normalizeActiveListing(listing()).tokenId, TOKEN); });

test("evidence is exclusive-create, preserves raw pages, verifies provenance and contains no secret", async () => { const evidence = await makeClient(async () => response({ listings: [listing()], next: null })).fetchSnapshot("2026-08-22T12:00:00.000Z", { "src/activeListings.ts": "hash" }); const directory = await mkdtemp(path.join(os.tmpdir(), "active-listings-")); const output = path.join(directory, "evidence.json"); const outputReversed = path.join(directory, "evidence-reversed.json"); const a = path.join(directory, "a.ts"); const z = path.join(directory, "z.ts"); try { await writeFile(a, "a-source", "utf8"); await writeFile(z, "z-source", "utf8"); const files = [{ path: z, sha256: await sha256File(z) }, { path: a, sha256: await sha256File(a) }]; await writeActiveListingsEvidenceExclusive(output, evidence, files); await writeActiveListingsEvidenceExclusive(outputReversed, evidence, [...files].reverse()); const text = await readFile(output, "utf8"); const reversedText = await readFile(outputReversed, "utf8"); assert.ok(text.includes("rawPages")); assert.ok(!text.includes("secret-api-key")); const parsed = JSON.parse(text); const reversed = JSON.parse(reversedText); assert.deepEqual(Object.keys(parsed.sourceProvenance), [a, z]); assert.deepEqual(parsed.sourceProvenance, reversed.sourceProvenance); await assert.rejects(() => writeActiveListingsEvidenceExclusive(output, evidence, files)); } finally { await rm(directory, { recursive: true, force: true }); } });
test("module surface has no database, SQL, worker, stream or event-backfill imports", async () => { const source = await readFile(new URL("../src/activeListings.ts", import.meta.url), "utf8"); assert.doesNotMatch(source, /from ["'](?:pg|.*(?:db|repository|worker|stream|backfill))/i); assert.doesNotMatch(source, /\b(?:INSERT\s+INTO|UPDATE\s+\w|DELETE\s+FROM|CREATE\s+TABLE|FOR\s+(?:UPDATE|SHARE))\b/i); });
