import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { canonicalEvidence, canonicalBytes, canonicalDecimal, sha256Canonical } from "../src/reconciliation/evidence/canonicalEvidence.js";
import { createGenerationEvidenceWriter, readGenerationDirectory } from "../src/reconciliation/evidence/fileEvidenceStore.js";
import type { GenerationIdentity } from "../src/reconciliation/evidence/evidenceTypes.js";

const identity: GenerationIdentity = { sweepId: "123e4567-e89b-12d3-a456-426614174000", modelVersion: "generation-v1", scope: { chain: "gunzilla", collection: "off-the-grid", contract: "0x9ed98e159be43a8d42b64053831fcae5e4d7d271", endpoint: "https://api.opensea.io/api/v2/listings/collection/off-the-grid/all" }, snapshotStartedAt: "2026-08-23T13:00:00.000Z", sourceProvenance: { b: "b".repeat(64), a: "a".repeat(64) }, policyHash: "c".repeat(64) };
const transitions = { sweepId: identity.sweepId, sequence: 1, fromState: "OPEN", toState: "ABORTED", reasonCodes: ["TEST"], evidenceRootHash: "d".repeat(64), modelVersion: identity.modelVersion, recordedAt: "2026-08-23T13:01:00.000Z", writerInstance: "test" };
async function fixture() { const root = await mkdtemp(path.join(os.tmpdir(), "evidence-store-")); const writer = await createGenerationEvidenceWriter(root, identity); await writer.writeArtifact({ artifactType: "transitions", artifactId: "history", relativePath: "transitions.jsonl", payload: transitions }); return { root, directory: path.join(root, identity.sweepId), writer }; }

test("canonicalization sorts keys, preserves arrays and distinguishes null/missing", () => { assert.equal(canonicalEvidence({ b: 2, a: 1 }), "{\"a\":1,\"b\":2}"); assert.equal(canonicalEvidence(["b", "a"]), "[\"b\",\"a\"]"); assert.notEqual(canonicalEvidence({ value: null }), canonicalEvidence({})); assert.equal(canonicalDecimal("9007199254740993"), "9007199254740993"); assert.throws(() => canonicalDecimal("01")); assert.throws(() => canonicalDecimal("1.0")); });
test("same logical artifact is deterministic and idempotent, different bytes conflict", async () => { const f = await fixture(); try { const a = await f.writer.writeArtifact({ artifactType: "custom", artifactId: "x", relativePath: "x.json", payload: { b: 2, a: 1 } }); const b = await f.writer.writeArtifact({ artifactType: "custom", artifactId: "x", relativePath: "x.json", payload: { a: 1, b: 2 } }); assert.deepEqual(a, b); await assert.rejects(() => f.writer.writeArtifact({ artifactType: "custom", artifactId: "x", relativePath: "x.json", payload: { a: 9 } }), /ARTIFACT_CONFLICT/); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("root manifest and graph reopen deterministically", async () => { const f = await fixture(); try { const ref = await f.writer.writeArtifact({ artifactType: "custom", artifactId: "x", relativePath: "x.json", payload: { a: 1 } }); const manifest = await f.writer.finalizeManifest({ writerProvenance: { instance: "test" } }); assert.equal(manifest.artifacts.length, 2); const result = await readGenerationDirectory(f.directory, identity.sweepId); assert.equal(result.status, "COMPLETE"); assert.equal(result.transitions.length, 1); assert.equal(ref.contentHash.length, 64); assert.equal(Object.isFrozen(result), true); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("missing root or child never infers complete state", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "evidence-store-")); try { const missing = await readGenerationDirectory(path.join(root, identity.sweepId), identity.sweepId); assert.equal(missing.status, "INCOMPLETE"); const f = await fixture(); await f.writer.writeArtifact({ artifactType: "custom", artifactId: "x", relativePath: "x.json", payload: { a: 1 } }); await f.writer.finalizeManifest(); await rm(path.join(f.directory, "x.json")); const corrupt = await readGenerationDirectory(f.directory, identity.sweepId); assert.equal(corrupt.status, "CORRUPT"); await rm(f.root, { recursive: true, force: true }); } finally { await rm(root, { recursive: true, force: true }); } });
test("tampering, byte length and temp files fail closed", async () => { const f = await fixture(); try { await f.writer.writeArtifact({ artifactType: "custom", artifactId: "x", relativePath: "x.json", payload: { a: 1 } }); await f.writer.finalizeManifest(); await writeFile(path.join(f.directory, "x.json"), "tampered", "utf8"); const bad = await readGenerationDirectory(f.directory, identity.sweepId); assert.equal(bad.status, "CORRUPT"); } finally { await rm(f.root, { recursive: true, force: true }); } const g = await fixture(); try { await writeFile(path.join(g.directory, "orphan.tmp"), "partial", "utf8"); const result = await readGenerationDirectory(g.directory, identity.sweepId); assert.equal(result.status, "INCOMPLETE"); } finally { await rm(g.root, { recursive: true, force: true }); } });
test("path traversal is rejected", async () => { const f = await fixture(); try { for (const relativePath of ["../outside.json", "..\\outside.json", "C:\\outside.json", "\\\\server\\share\\file.json"]) await assert.rejects(() => f.writer.writeArtifact({ artifactType: "custom", artifactId: "bad", relativePath, payload: {} }), /INVALID_ARTIFACT_PATH/); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("read output is frozen and does not expose mutable artifact bytes", async () => { const f = await fixture(); try { await f.writer.finalizeManifest(); const result = await f.writer.readGeneration(); assert.equal(Object.isFrozen(result), true); assert.equal(Object.isFrozen(result.manifest), true); assert.throws(() => (result as any).status = "COMPLETE"); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("manifest conflict and unregistered artifacts are rejected", async () => { const f = await fixture(); try { await f.writer.finalizeManifest(); await writeFile(path.join(f.directory, "unregistered.json"), "{}", "utf8"); const result = await readGenerationDirectory(f.directory, identity.sweepId); assert.equal(result.status, "CORRUPT"); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("large decimal watermark retains exact bytes", () => { const value = { eventId: "90071992547409931234567890", receivedAt: "2026-08-23T13:00:00.000Z" }; assert.equal(new TextDecoder().decode(canonicalBytes(value)), "{\"eventId\":\"90071992547409931234567890\",\"receivedAt\":\"2026-08-23T13:00:00.000Z\"}"); assert.equal(sha256Canonical(value).length, 64); });
test("seen-order artifact is exact-hash identity and rejects duplicates", async () => { const row = { sweepId: identity.sweepId, orderHash: "0x" + "a".repeat(64), pageNumber: 1, rawPageHash: "b".repeat(64), normalizedMaterialHash: "c".repeat(64) }; const f = await fixture(); try { await f.writer.writeArtifact({ artifactType: "seen-orders", artifactId: "set", relativePath: "seen-orders.jsonl", payload: [row, { ...row, orderHash: "0x" + "b".repeat(64), pageNumber: 2 }] }); await f.writer.finalizeManifest(); assert.equal((await f.writer.getSeenOrders()).length, 2); } finally { await rm(f.root, { recursive: true, force: true }); } const g = await fixture(); try { await g.writer.writeArtifact({ artifactType: "seen-orders", artifactId: "set", relativePath: "seen-orders.jsonl", payload: [row, row] }); await g.writer.finalizeManifest(); await assert.rejects(() => g.writer.getSeenOrders(), /INVALID_SEEN_ORDERS/); } finally { await rm(g.root, { recursive: true, force: true }); } });
test("catch-up artifact preserves large decimal IDs and rejects non-canonical IDs", async () => { const f = await fixture(); try { const row = { sweepId: identity.sweepId, roundNumber: 1, eventId: "90071992547409931234567890", receivedAt: "2026-08-23T13:01:00.000Z", pendingCount: 0, processingCount: 0, failedCount: 0, reconciliationRequiredCount: 0, unknownCount: 0, observationProvenance: { source: "fixture" } }; await f.writer.writeArtifact({ artifactType: "catchup-rounds", artifactId: "rounds", relativePath: "catchup-rounds.jsonl", payload: row }); await f.writer.finalizeManifest(); assert.equal((await f.writer.getCatchUpRounds())[0].eventId, row.eventId); } finally { await rm(f.root, { recursive: true, force: true }); } });
