import assert from "node:assert/strict";
import test from "node:test";
import type { DbPool, QueryResult, TransactionClient } from "../src/db/types.js";
import { PostgresGenerationJournalWindowReader } from "../src/reconciliation/generationJournalWindowReader.js";
const CONTRACT="0x9ed98e159be43a8d42b64053831fcae5e4d7d271";const HASH=(n:number)=>"0x"+n.toString(16).padStart(64,"0");
const makeRow=(id:number,type:string,status:string,token="7")=>({event_id:String(id),received_at:"2026-09-14T00:00:00.000Z",event_type:type,processing_status:status,order_hash:HASH(id),chain:"gunzilla",contract_address:CONTRACT,token_id:token});
class Client implements TransactionClient{constructor(private db:Pool,private id:number){}async query<T=unknown>(sql:string,values?:readonly unknown[]):Promise<QueryResult<T>>{this.db.calls.push([this.id,sql]);const l=sql.toLowerCase();if(/^(begin|set transaction|commit|rollback)/.test(l))return{rows:[],rowCount:0};if(l.includes("transaction_timestamp"))return{rows:[{now:"2026-09-14T00:00:00.000Z"} as T],rowCount:1};if(l.includes("order by event_id desc")){const h=this.db.high[this.id-1]??0;return h===0?{rows:[],rowCount:0}:{rows:[{event_id:String(h),received_at:"2026-09-14T00:00:00.000Z"} as T],rowCount:1};}if(l.includes("where event_id >")){const lo=Number(values?.[0]),hi=Number(values?.[1]);return{rows:this.db.rows.filter(x=>Number(x.event_id)>lo&&Number(x.event_id)<=hi) as T[],rowCount:1};}throw new Error("unexpected query");}release(){this.db.released.push(this.id);}}
class Pool implements DbPool{rows:any[]=[];calls:[number,string][]=[];released:number[]=[];high=[1233,1257];private n=0;constructor(){for(let i=1;i<=1233;i++)this.rows.push(makeRow(i,"item_transferred","reconciliation_required"));for(let i=1234;i<=1246;i++)this.rows.push(makeRow(i,"item_transferred","pending","999"));this.rows.push(makeRow(1247,"item_transferred","pending"),makeRow(1248,"item_transferred","processing"),makeRow(1249,"item_transferred","failed"),makeRow(1250,"item_transferred","reconciliation_required"),makeRow(1251,"item_listed","applied"),makeRow(1252,"item_sold","ignored_duplicate"),makeRow(1253,"item_cancelled","ignored_older"),makeRow(1254,"order_invalidate","pending"),makeRow(1255,"order_revalidate","processing"),makeRow(1256,"item_listed","mystery"));}async connect(){return new Client(this,++this.n);}async query(){return{rows:[],rowCount:0};}async end(){}}
const identity={orderHashes:new Set<string>(),nftKeys:new Set([["gunzilla","\0",CONTRACT,"\0","7"].join("")])};
test("empty journal uses deterministic zero watermark",async()=>{const p=new Pool();p.rows=[];p.high=[0,0];const s=await new PostgresGenerationJournalWindowReader(p).captureStart();assert.equal(s.eventHighWaterBefore.eventId,"0");assert.equal(s.eventHighWaterBefore.receivedAt,"2026-09-14T00:00:00.000Z");});
test("historical rows are excluded and in-window lifecycle is counted in one snapshot",async()=>{const p=new Pool();const r=new PostgresGenerationJournalWindowReader(p);const s=await r.captureStart();const o=await r.observe(s,identity);assert.equal(o.observedHighWater.eventId,"1257");assert.equal(o.round.pendingCount,2);assert.equal(o.round.processingCount,2);assert.equal(o.round.failedCount,1);assert.equal(o.round.reconciliationRequiredCount,1);assert.equal(o.round.unknownStatusCount,1);assert.ok(!o.eventIds.includes("1233"));assert.ok(o.eventIds.includes("1247"));const q=p.calls.filter(x=>x[1].toLowerCase().includes("order by event_id")||x[1].toLowerCase().includes("where event_id"));assert.equal(q[1][0],q[2][0]);});
test("unrelated transfer is excluded while matching transfer blocks",async()=>{const p=new Pool();const r=new PostgresGenerationJournalWindowReader(p);const s=await r.captureStart();const o=await r.observe(s,identity);assert.ok(!o.eventIds.includes("1234"));assert.ok(o.eventIds.includes("1247"));});
test("malformed in-window order identity rolls back",async()=>{const p=new Pool();p.high[1]=1257;const bad=makeRow(1257,"item_listed","pending");bad.chain="ethereum";p.rows[p.rows.length-1]=bad;const r=new PostgresGenerationJournalWindowReader(p);const s=await r.captureStart();await assert.rejects(async()=>r.observe(s,identity),/GENERATION_WINDOW_MALFORMED_IDENTITY/);assert.ok(p.calls.some(x=>x[1].toLowerCase().startsWith("rollback")));});
