import assert from "node:assert/strict";import test from "node:test";import{ActiveListingsClient,ACTIVE_LISTINGS_CONTRACT}from"../src/activeListings.js";import{validateCanonicalIdentity}from"../src/reconciliation/identityScope.js";import{projectInitialGenerationBaseline}from"../src/reconciliation/initialGenerationBaseline.js";
const SWEEP="123e4567-e89b-12d3-a456-426614174000",SELLER="0x2222222222222222222222222222222222222222",PROTOCOL="0x"+"1".repeat(40),opts={sourceEvidencePath:"fixture",sweepId:SWEEP};
function listing(index=1):any{const t=String(index);return{order_hash:"0x"+String(index).padStart(64,"0"),chain:"gunzilla",protocol_address:PROTOCOL,asset:{identifier:t,contract:ACTIVE_LISTINGS_CONTRACT},remaining_quantity:1,protocol_data:{parameters:{offerer:SELLER,offer:[{itemType:2,token:ACTIVE_LISTINGS_CONTRACT,identifierOrCriteria:t,startAmount:"1",endAmount:"1"}],consideration:[{itemType:0,token:"0x0000000000000000000000000000000000000000",identifierOrCriteria:"0",startAmount:"1234500000000000000",endAmount:"1234500000000000000",recipient:SELLER}],startTime:"1787323440",endTime:"1789915440",orderType:0},signature:null},price:{current:{currency:"GUN",decimals:18,value:"1234500000000000000"}},order_created_at:1787323444,type:"basic",status:"ACTIVE"};}
async function evidence(rows:any[]){const c=new ActiveListingsClient({apiKey:"x",dependencies:{fetch:async()=>({ok:true,status:200,headers:{get:()=>null},text:async()=>JSON.stringify({listings:rows,next:null})})as any,sleep:async()=>undefined},policy:{maxPages:1,maxListings:100},retryPolicy:{maxRetries:0}});const snapshot=await c.fetchSnapshot("2026-08-21T00:00:00.000Z",{fixture:"a".repeat(64)});return{sourceProvenance:{fixture:"a".repeat(64)},snapshot};}
test("complete snapshot projects PRESENT ephemeral orders",async()=>{const out=projectInitialGenerationBaseline(await evidence([listing()]),opts);assert.equal(out.localOrders.length,1);assert.equal(out.candidateBundle.counts.present,1);const o=out.localOrders[0];assert.equal(o.status,"active");assert.equal(o.isActive,true);assert.equal(o.needsReconciliation,false);assert.equal(o.lastOrderEventTimestamp,null);assert.equal(o.lastOrderEventVersion,null);assert.equal(o.createdAt,null);assert.equal(o.updatedAt,null);assert.equal(validateCanonicalIdentity(o.identity),"VALID");});
test("N orders are deterministic and one-to-one",async()=>{const out=projectInitialGenerationBaseline(await evidence([listing(2),listing(1)]),opts);assert.deepEqual(out.localOrders.map(x=>x.orderHash),["0x"+"0".repeat(63)+"1","0x"+"0".repeat(63)+"2"]);assert.equal(out.candidateBundle.counts.present,2);assert.equal(out.candidateBundle.counts.absentCandidate,0);assert.equal(out.candidateBundle.counts.blocked,0);});
for(const [name,mutate]of[["null protocol",(x:any)=>x.protocol_address=null],["malformed protocol",(x:any)=>x.protocol_address="bad"],["uppercase protocol",(x:any)=>x.protocol_address=PROTOCOL.toUpperCase()],["unsupported contract",(x:any)=>x.asset.contract="0x"+"a".repeat(40)],["unsupported chain",(x:any)=>x.chain="ethereum"],["invalid token",(x:any)=>x.asset.identifier="-1"]]as const)test(`${name} fails closed`,async()=>{const v=listing();mutate(v);await assert.rejects(async()=>projectInitialGenerationBaseline(await evidence([v]),opts));});
test("ambiguous protocol fails closed",async()=>{const v=listing(2);v.protocol_address="0x"+"2".repeat(40);await assert.rejects(async()=>projectInitialGenerationBaseline(await evidence([listing(),v]),opts));});
test("empty snapshot fails closed",async()=>{await assert.rejects(async()=>projectInitialGenerationBaseline(await evidence([]),opts));});
test("duplicate order hash fails closed",async()=>{await assert.rejects(async()=>projectInitialGenerationBaseline(await evidence([listing(),listing()]),opts));});
test("SeenOrder mismatch fails closed",async()=>{const v=await evidence([listing()]);v.snapshot.listings[0].orderHash="0x"+"f".repeat(64);await assert.rejects(async()=>projectInitialGenerationBaseline(v,opts));});
