import test from "node:test";
import assert from "node:assert/strict";
import { runInitialGenerationBootstrap, type BootstrapDependencies } from "../src/runtime/initialGenerationBootstrapRuntime.js";

const hash = "a".repeat(64);
function snapshot(result: "COMPLETE" | "PARTIAL" = "COMPLETE"): any { return { result, startedAt: "2026-09-15T00:00:00.000Z", completedAt: "2026-09-15T00:00:01.000Z", endpoint: "https://api.opensea.io/api/v2/listings/collection/off-the-grid/all", collectionSlug: "off-the-grid", expectedChain: "gunzilla", expectedContract: "0x9ed98e159be43a8d42b64053831fcae5e4d7d271", pageAttempts: 1, pagesFetched: 1, httpAttempts: 1, retryAttempts: 0, pageAttemptDetails: [{ logicalPage: 1, httpAttempts: 1, retryAttempts: 0, successful: true, finalStatus: 200, error: null, retryAfterUsed: false, waitMs: [] }], counters: { observed: result === "COMPLETE" ? 1 : 0, normalized: result === "COMPLETE" ? 1 : 0, malformed: 0, unsupported: 0, duplicates: 0, conflicts: 0 }, paginationExhausted: result === "COMPLETE", cursorCycleDetected: false, repeatedPageDetected: false, truncatedByPageLimit: false, truncatedByListingLimit: false, listings: [], rawPages: [], nextCursor: null, warnings: [], errors: [], responseHashes: [hash], sourceProvenance: {} }; }
function projection(): any { const identity = { orderHash: "0x" + "1".repeat(64), chain: "gunzilla", contractAddress: "0x9ed98e159be43a8d42b64053831fcae5e4d7d271", tokenId: "7", collectionSlug: "off-the-grid", protocolAddress: "0x" + "a".repeat(40) }; return { evidence: { manifest: { sweepId: "123e4567-e89b-12d3-a456-426614174000", snapshotStartedAt: "2026-09-15T00:00:00.000Z", scope: { contract: identity.contractAddress } } }, protocolAddress: identity.protocolAddress, localOrders: [{ orderHash: identity.orderHash, identity }], candidateBundle: { orders: [{ orderHash: identity.orderHash, identity, classification: "PRESENT", seenInSweep: true, authorityGranted: false, reasons: [] }], counts: { present: 1, absentCandidate: 0, blocked: 0 }, sweepId: "123e4567-e89b-12d3-a456-426614174000" } }; }
function generation(stable = true): any { return { state: stable ? "VERIFIED" : "ABORTED", catchUp: { outcome: stable ? "STABLE" : "BUDGET_EXHAUSTED", stable, stableWatermark: stable ? { eventId: "2", receivedAt: "2026-09-15T00:00:02.000Z" } : null }, finalFence: { outcome: stable ? "FENCE_ELIGIBLE" : "FENCE_BLOCKED", eligible: stable }, abortReasons: stable ? [] : ["CATCH_UP_BUDGET_EXHAUSTED"], deactivationAuthorityGranted: false }; }
function pub(): any { return { generationPublicationId: hash, publicationState: "ACCEPTED" }; }
function plan(): any { return { adoptionId: hash, expectedOrderCount: 1 }; }
function deps(overrides: Partial<BootstrapDependencies> = {}): BootstrapDependencies & { calls: string[] } {
  const calls: string[] = []; let observations = 0;
  const reader: any = { captureStart: async () => { calls.push("start"); return { eventHighWaterBefore: { eventId: "0", receivedAt: "2026-09-15T00:00:00.000Z" } }; }, observe: async (_s: any, _scope: any, round: number) => { calls.push(`observe:${round}`); observations += 1; return { observedHighWater: { eventId: "2", receivedAt: "2026-09-15T00:00:02.000Z" }, round: { roundNumber: round, observedHighWater: { eventId: "2", receivedAt: "2026-09-15T00:00:02.000Z" }, pendingCount: 0, processingCount: 0, failedCount: 0, reconciliationRequiredCount: 0, unknownStatusCount: 0 }, eventIds: [], scopeFingerprint: hash }; } };
  const writer: any = { writeArtifact: async (input: any) => { calls.push(`artifact:${input.artifactId}`); return { ...input, artifactType: input.artifactType, sweepId: "123e4567-e89b-12d3-a456-426614174000", relativePath: input.relativePath, schemaVersion: input.schemaVersion ?? "x", contentHash: hash, byteLength: 1 }; }, finalizeManifest: async () => ({}), readGeneration: async () => ({ status: "COMPLETE" }), listArtifacts: async () => [], readArtifact: async () => [], getSeenOrders: async () => [], getCatchUpRounds: async () => [], getTransitions: async () => [] };
  const base: BootstrapDependencies = { pool: {} as any, evidenceRoot: "C:\\evidence-root", apiKey: "test-key", sweepId: "123e4567-e89b-12d3-a456-426614174000", sourceFiles: [], preflight: async () => calls.push("preflight"), healthProbe: async () => { calls.push("health"); return true; }, activeListingsClient: { fetchSnapshot: async () => { calls.push("snapshot"); return snapshot(); }, close: async () => { calls.push("client-close"); } } as any, journalReader: reader, project: (() => { calls.push("project"); return projection(); }) as any, scopeFactory: (() => { calls.push("scope"); return {}; }) as any, writerFactory: async () => writer, persistSnapshotArtifact: async () => { calls.push("snapshot-artifact"); return { contentHash: hash }; }, persistIntegrated: async () => { calls.push("integrated"); return {}; }, reconstruct: async () => { calls.push("reconstruct"); return { status: "VALID" } as any; }, evaluate: (() => { calls.push("evaluate"); return generation(); }) as any, publicationStore: { publish: async () => { calls.push("publish"); return pub(); } } as any, planFactory: (() => { calls.push("plan"); return plan(); }) as any, isTrustedPlan: () => true, adoptionStore: { adopt: async () => { calls.push("adopt"); return { outcome: "ADOPTED", adoptionId: hash, adoptedOrderCount: 1 }; } } as any };
  return Object.assign(base, overrides, { calls });
}

test("full bootstrap flow publishes and adopts once without stopping external ingestion", async () => { const d = deps(); const r = await runInitialGenerationBootstrap(d); assert.equal(r.status, "VERIFIED_ADOPTED"); assert.equal(d.calls.filter((x) => x === "publish").length, 1); assert.equal(d.calls.filter((x) => x === "adopt").length, 1); assert.equal(d.calls.includes("stop"), false); assert.ok(d.calls.indexOf("snapshot-artifact") < d.calls.indexOf("integrated")); });
test("migration, ingestion, and local-state preflight failures precede any snapshot request", async () => { for (const preflight of [async () => { throw new Error("MIGRATION_009_PREFLIGHT_FAILED"); }, async () => { throw new Error("INITIAL_BASELINE_LOCAL_STATE_NOT_EMPTY"); }]) { const d = deps({ preflight }); await assert.rejects(() => runInitialGenerationBootstrap(d)); assert.equal(d.calls.includes("snapshot"), false); } const absent = deps({ healthProbe: async () => false }); await assert.rejects(() => runInitialGenerationBootstrap(absent), /PRODUCTION_INGESTION_CONTINUITY_LOST/); assert.equal(absent.calls.includes("snapshot"), false); });
test("snapshot and projection failures cannot publish or adopt", async () => { const partial = deps({ activeListingsClient: { fetchSnapshot: async () => snapshot("PARTIAL"), close: async () => {} } as any }); await assert.rejects(() => runInitialGenerationBootstrap(partial), /SNAPSHOT_NOT_COMPLETE/); assert.equal(partial.calls.includes("publish"), false); const bad = deps({ project: (() => { throw new Error("INITIAL_GENERATION_PROTOCOL_UNPROVEN"); }) as any }); await assert.rejects(() => runInitialGenerationBootstrap(bad), /PROTOCOL_UNPROVEN/); assert.equal(bad.calls.includes("adopt"), false); });
test("settling retries pending work, while reconciliation and unsafe official rounds fail closed", async () => { let n = 0; const settling = deps({ journalReader: { captureStart: async () => ({ eventHighWaterBefore: { eventId: "0", receivedAt: "2026-09-15T00:00:00.000Z" } }), observe: async (_s: any, _scope: any, round: number) => { n += 1; const pending = n === 1; return { observedHighWater: { eventId: "2", receivedAt: "2026-09-15T00:00:02.000Z" }, round: { roundNumber: round, observedHighWater: { eventId: "2", receivedAt: "2026-09-15T00:00:02.000Z" }, pendingCount: pending ? 1 : 0, processingCount: 0, failedCount: 0, reconciliationRequiredCount: 0, unknownStatusCount: 0 }, eventIds: [], scopeFingerprint: hash }; } } as any }); assert.equal((await runInitialGenerationBootstrap(settling)).status, "VERIFIED_ADOPTED"); const unsafe = deps({ evaluate: (() => generation(false)) as any }); await assert.rejects(() => runInitialGenerationBootstrap(unsafe), /CATCH_UP_BUDGET_EXHAUSTED|GENERATION_NOT_VERIFIED/); assert.equal(unsafe.calls.includes("publish"), false); });
test("invalid reconstruction and publication failure prevent adoption; published-not-adopted is retained", async () => { const invalid = deps({ reconstruct: async () => ({ status: "CORRUPT" } as any) }); await assert.rejects(() => runInitialGenerationBootstrap(invalid), /RECONSTRUCTION_FAILED/); assert.equal(invalid.calls.includes("publish"), false); const pubFail = deps({ publicationStore: { publish: async () => { throw new Error("publication_failed"); } } as any }); await assert.rejects(() => runInitialGenerationBootstrap(pubFail), /publication_failed/); assert.equal(pubFail.calls.includes("adopt"), false); const blocked = deps({ adoptionStore: { adopt: async () => { throw new Error("INITIAL_BASELINE_POST_STABLE_EVENT"); } } as any }); const result = await runInitialGenerationBootstrap(blocked); assert.equal(result.status, "PUBLISHED_NOT_ADOPTED"); assert.ok(blocked.calls.includes("publish")); });
