import test from "node:test";
import assert from "node:assert/strict";
import { PostgresJournalFenceSnapshotReader, applyProductionJournalFence } from "../src/reconciliation/verifier/journalFenceSnapshotReader.js";
import { applyJournalFence } from "../src/reconciliation/verifier/targetedVerifierArtifact.js";
import type { DbPool, QueryResult, TransactionClient } from "../src/db/types.js";
import { adaptOpenSeaExactOrder } from "../src/reconciliation/verifier/openSeaExactOrderAdapter.js";
import { interpretOpenSeaExactOrderObservation } from "../src/reconciliation/verifier/targetedVerifierNormalizer.js";
import { eventFingerprint } from "../src/reconciliation/verifier/targetedVerifierPolicy.js";
import { encodeCanonicalOrder, makeCanonicalOfficialOrder } from "./helpers/openSeaCanonicalOrder.js";
import { disposeTrustedContexts, makeTrustedContexts } from "./helpers/trustedVerifierContexts.js";

const ORDER = "0x" + "a".repeat(64), CONTRACT = "0x" + "b".repeat(40), OTHER = "0x" + "c".repeat(64);
type Row = { event_id: string; event_type: string; event_version: string | null; order_hash: string | null; chain: string | null; contract_address: string | null; token_id: string | null; received_at: string | Date };
class Sim implements DbPool {
  rows: Row[] = []; private snap: Row[] | null = null; beforeRelevant?: () => void; failRelevant = false; begins = 0; commits = 0; rollbacks = 0; releases = 0;
  async connect(): Promise<TransactionClient> { const self=this; return { release(){self.releases++;}, query: async <T>(sql:string, values?:readonly unknown[]) => self.queryTx<T>(sql, values) }; }
  async end() {}
  private async queryTx<T>(sql:string, values?:readonly unknown[]): Promise<QueryResult<T>> {
    if (/^BEGIN/.test(sql)) { this.begins++; this.snap=this.rows.map(r=>({...r})); return {rows:[],rowCount:0}; }
    if (/SET TRANSACTION/.test(sql)) return {rows:[],rowCount:0};
    if (/ROLLBACK/.test(sql)) { this.rollbacks++; this.snap=null; return {rows:[],rowCount:0}; }
    if (/COMMIT/.test(sql)) { this.commits++; this.snap=null; return {rows:[],rowCount:0}; }
    const data=this.snap ?? this.rows;
    if (/transaction_timestamp/.test(sql)) return {rows:[{now:new Date("2026-01-01T00:00:00.000Z")} as T],rowCount:1};
    if (/ORDER BY event_id DESC/.test(sql)) { const r=[...data].sort((a,b)=>BigInt(a.event_id)<BigInt(b.event_id)?1:BigInt(a.event_id)>BigInt(b.event_id)?-1:0)[0]; return {rows:r?[{event_id:r.event_id,received_at:r.received_at} as T]:[],rowCount:r?1:0}; }
    if (/SELECT event_id::text AS event_id,event_type/.test(sql)) { this.beforeRelevant?.(); this.beforeRelevant=undefined; const hi=String(values?.[0]); const [,ord,chain,contract,token]=values ?? []; const out=data.filter(r=>BigInt(r.event_id)<=BigInt(hi!) && (r.order_hash===ord || (r.chain===chain&&r.contract_address===contract&&r.token_id===token))).sort((a,b)=>BigInt(a.event_id)<BigInt(b.event_id)?-1:BigInt(a.event_id)>BigInt(b.event_id)?1:0); return {rows:out.map(r=>({...r}) as T),rowCount:out.length}; }
    throw new Error(`UNSUPPORTED_SIM_SQL:${sql}`);
  }
  async query<T>(sql:string, values?:readonly unknown[]):Promise<QueryResult<T>> { return this.queryTx<T>(sql,values); }
  insert(row:Row){this.rows.push(row);}
}
const id={orderHash:ORDER,chain:"gunzilla",contractAddress:CONTRACT,tokenId:"6394148"};
const row=(event_id:string, event_type:string, order_hash:string|null=ORDER, chain:string|null="gunzilla", contract_address:string|null=CONTRACT, token_id:string|null="6394148"):Row=>({event_id,event_type,event_version:"1",order_hash,chain,contract_address,token_id,received_at:new Date("2026-01-01T00:01:00.000Z")});

test("reader uses coherent high-water and subsequent snapshot sees insertion", async()=>{const db=new Sim();db.insert(row("1","item_listed"));db.beforeRelevant=()=>db.insert(row("2","item_transferred",null));const reader=new PostgresJournalFenceSnapshotReader(db);const first=await reader.readSnapshot(id);const second=await reader.readSnapshot(id);assert.deepEqual(first.watermark.eventId,"1");assert.deepEqual(first.relevantOrderFingerprint.eventIds,["1"]);assert.deepEqual(second.relevantOrderFingerprint.eventIds,["1","2"]);});
test("direct order and same-NFT events are relevant while unrelated rows are excluded", async()=>{const db=new Sim();db.insert(row("1","item_listed"));db.insert(row("2","item_sold",OTHER,"gunzilla",CONTRACT,"6394148"));db.insert(row("3","item_transferred",null,"gunzilla",CONTRACT,"6394148"));db.insert(row("4","item_sold",OTHER,"gunzilla",CONTRACT,"999"));db.insert(row("5","item_sold",OTHER,"other",CONTRACT,"6394148"));const s=await new PostgresJournalFenceSnapshotReader(db).readSnapshot(id);assert.deepEqual(s.relevantOrderFingerprint.eventIds,["1","2","3"]);assert.equal(s.relevantOrderFingerprint.orderingAmbiguous,false);});
test("empty journal returns deterministic valid snapshot", async()=>{const s=await new PostgresJournalFenceSnapshotReader(new Sim()).readSnapshot(id);assert.equal(s.watermark.eventId,"0");assert.equal(s.relevantOrderFingerprint.eventIds.length,0);assert.equal(s.relevantOrderFingerprint.orderingAmbiguous,false);});
test("malformed relevant row fails closed", async()=>{const db=new Sim();db.insert(row("1","unknown"));await assert.rejects(()=>new PostgresJournalFenceSnapshotReader(db).readSnapshot(id),/MALFORMED_JOURNAL_EVENT/);const badId=new Sim();badId.insert(row("not-decimal","item_listed"));await assert.rejects(()=>new PostgresJournalFenceSnapshotReader(badId).readSnapshot(id),/INVALID_JOURNAL_WATERMARK/);});
test("malformed identities fail before SQL", async()=>{const reader=new PostgresJournalFenceSnapshotReader(new Sim());for(const bad of [{...id,orderHash:"bad"},{...id,contractAddress:"bad"},{...id,tokenId:"-1"},{...id,chain:"ethereum"}])await assert.rejects(()=>reader.readSnapshot(bad),/INVALID_JOURNAL_SNAPSHOT_IDENTITY/);});
test("invalid event version fails closed", async()=>{const db=new Sim();const bad={...row("1","item_listed"),event_version:"-1"};db.insert(bad);await assert.rejects(()=>new PostgresJournalFenceSnapshotReader(db).readSnapshot(id),/MALFORMED_JOURNAL_EVENT/);});
test("invalid high-water timestamp fails closed", async()=>{const db=new Sim();db.insert({...row("1","item_listed"),received_at:"not-a-time"});await assert.rejects(()=>new PostgresJournalFenceSnapshotReader(db).readSnapshot(id),/INVALID_JOURNAL_TIMESTAMP/);});
test("reader rolls back and releases on bounded query failure", async()=>{const db=new Sim();db.insert(row("1","item_listed"));db.beforeRelevant=()=>{throw new Error("INJECTED_RELEVANT_FAILURE")};await assert.rejects(()=>new PostgresJournalFenceSnapshotReader(db).readSnapshot(id),/INJECTED_RELEVANT_FAILURE/);assert.equal(db.rollbacks,1);assert.equal(db.releases,1);assert.equal(db.commits,0);});

test("production fence bridge executes accepted fence algorithm", async()=>{const graph=await makeTrustedContexts();try{const context=graph.contexts[0];const body=encodeCanonicalOrder(makeCanonicalOfficialOrder(context));const observation=adaptOpenSeaExactOrder({context,httpStatus:200,body,headers:[{name:"Date",value:"Tue, 01 Jan 2030 00:00:00 GMT"},{name:"Content-Type",value:"application/json"},{name:"Content-Encoding",value:"identity"}],timing:{requestStartedAt:"2030-01-01T00:00:00.000Z",responseHeadersAt:"2030-01-01T00:00:00.100Z",responseCompletedAt:"2030-01-01T00:00:00.200Z",elapsedMs:10,overallDeadlineMs:1000,deadlineExceeded:false}});const provider=interpretOpenSeaExactOrderObservation({context,observation});const db=new Sim();db.insert(row("100","item_sold",OTHER,"other","0x"+"d".repeat(40),"999"));const bridge=await applyProductionJournalFence({providerResult:provider,context,snapshotReader:new PostgresJournalFenceSnapshotReader(db)});assert.equal(bridge.status,provider.status);assert.equal(bridge.reasonCodes.includes("RELEVANT_ORDER_EVENT_ACROSS_FENCE"),false);assert.equal(bridge.authorityGranted,false);assert.equal(bridge.deactivationAuthorityGranted,false);}finally{await disposeTrustedContexts(graph.root);}});

test("fence matrix uses production reader and bridge end-to-end", async()=>{const graph=await makeTrustedContexts();try{const context=graph.contexts[0];const body=encodeCanonicalOrder(makeCanonicalOfficialOrder(context));const observation=adaptOpenSeaExactOrder({context,httpStatus:200,body,headers:[{name:"Date",value:"Tue, 01 Jan 2030 00:00:00 GMT"},{name:"Content-Type",value:"application/json"},{name:"Content-Encoding",value:"identity"}],timing:{requestStartedAt:"2030-01-01T00:00:00.000Z",responseHeadersAt:"2030-01-01T00:00:00.100Z",responseCompletedAt:"2030-01-01T00:00:00.200Z",elapsedMs:10,overallDeadlineMs:1000,deadlineExceeded:false}});const provider=interpretOpenSeaExactOrderObservation({context,observation});const ei=context.expectedIdentity;const unrelatedBase=row("100","item_sold",OTHER,"other","0x"+"d".repeat(40),"999");const run=async(extra:Row[])=>{const db=new Sim();db.insert(unrelatedBase);for(const r of extra)db.insert(r);return db;};const runBridge=async(extra:Row[])=>applyProductionJournalFence({providerResult:provider,context,snapshotReader:new PostgresJournalFenceSnapshotReader(await run(extra))});const unchanged=await runBridge([]);assert.equal(unchanged.status,provider.status);assert.equal(unchanged.reasonCodes.includes("RELEVANT_ORDER_EVENT_ACROSS_FENCE"),false);assert.equal(unchanged.authorityGranted,false);assert.equal(unchanged.deactivationAuthorityGranted,false);const unrelatedDb=await run([row("101","item_sold",OTHER,"other","0x"+"d".repeat(40),"999")]);const unrelatedPost=await new PostgresJournalFenceSnapshotReader(unrelatedDb).readSnapshot(ei);assert.equal(unrelatedPost.watermark.eventId,"101");assert.equal(unrelatedPost.relevantOrderFingerprint.eventIds.length,0);const unrelated=await applyProductionJournalFence({providerResult:provider,context,snapshotReader:new PostgresJournalFenceSnapshotReader(unrelatedDb)});assert.equal(unrelated.status,provider.status);assert.equal(unrelated.reasonCodes.includes("RELEVANT_ORDER_EVENT_ACROSS_FENCE"),false);assert.equal(unrelated.authorityGranted,false);assert.equal(unrelated.deactivationAuthorityGranted,false);for(const event of [row("101","item_sold",ei.orderHash,ei.chain,ei.contractAddress,ei.tokenId),row("101","item_transferred",null,ei.chain,ei.contractAddress,ei.tokenId),row("101","item_sold",OTHER,ei.chain,ei.contractAddress,ei.tokenId)]){const result=await runBridge([event]);assert.equal(result.status,"RECONCILIATION_REQUIRED");assert.ok(result.reasonCodes.includes("RELEVANT_ORDER_EVENT_ACROSS_FENCE"));assert.equal(result.authorityGranted,false);assert.equal(result.deactivationAuthorityGranted,false);}}finally{await disposeTrustedContexts(graph.root);}});
