import test from "node:test";
import assert from "node:assert/strict";
import type { DbPool, QueryResult, TransactionClient } from "../src/db/types.js";
import { makeTrustedContexts, disposeTrustedContexts } from "./helpers/trustedVerifierContexts.js";
import { createGenerationPublicationEvidence } from "../src/reconciliation/generationPublication.js";
import { deriveActiveListingsEvidence } from "../src/reconciliation/activeListingsEvidence.js";
import { evaluateShadowDeactivation, type ShadowDecisionV2 } from "../src/reconciliation/shadowDeactivationEvaluator.js";
import { PostgresShadowDecisionStore, decodeShadowDecisionRow } from "../src/reconciliation/shadowDecisionStore.js";
import { adaptOpenSeaExactOrder } from "../src/reconciliation/verifier/openSeaExactOrderAdapter.js";
import { __createTargetedVerifierOperationalWorkerForTest, InMemoryTargetedVerifierAttemptStore, type TargetedVerifierOperationalWorkerOptions } from "../src/reconciliation/verifier/targetedVerifierOperationalWorker.js";
import type { TargetedVerifierContext } from "../src/reconciliation/verifier/targetedVerifierTypes.js";

const NOW = "2026-01-01T00:00:00.000Z";
function inactiveObservation(context: TargetedVerifierContext): ReturnType<typeof adaptOpenSeaExactOrder> { const order = { order_hash: context.orderHash, chain: context.chain, protocol_address: context.protocolAddress, status: "INACTIVE", type: "basic", price: { current: { currency: "ETH", decimals: 18, value: "1" } }, asset: { contract: context.contractAddress, identifier: context.expectedIdentity.tokenId }, remaining_quantity: 1, protocol_data: { parameters: { offerer: "0x" + "2".repeat(40), consideration: [{ itemType: 2, token: context.contractAddress, identifierOrCriteria: context.expectedIdentity.tokenId, startAmount: "1", endAmount: "1", recipient: "0x" + "2".repeat(40) }], zone: "0x" + "3".repeat(40), zoneHash: "0x" + "0".repeat(64), salt: "1", conduitKey: "0x" + "0".repeat(64), totalOriginalConsiderationItems: 0, counter: 0, orderType: 0, startTime: "1760000000", endTime: "1760001000", offer: [{ itemType: 2, token: context.contractAddress, identifierOrCriteria: context.expectedIdentity.tokenId, startAmount: "1", endAmount: "1" }] } } }; return adaptOpenSeaExactOrder({ context, httpStatus: 200, body: new TextEncoder().encode(JSON.stringify({ order })), headers: [{ name: "Content-Type", value: "application/json" }, { name: "Content-Encoding", value: "identity" }, { name: "Date", value: "Thu, 01 Jan 2026 00:00:00 GMT" }], timing: { requestStartedAt: NOW, responseHeadersAt: "2026-01-01T00:00:00.100Z", responseCompletedAt: "2026-01-01T00:00:00.200Z", elapsedMs: 200, overallDeadlineMs: 1000, deadlineExceeded: false } }); }
type ShadowRow = Record<string, unknown>;
class ShadowDb implements DbPool {
  readonly shadowRows: ShadowRow[] = [];
  readonly sql: string[] = [];
  constructor(readonly attempt: unknown, readonly generation: ShadowRow, private readonly failInsert = false) {}
  async query<T = unknown>(query: string, values?: readonly unknown[]): Promise<QueryResult<T>> { this.sql.push(query); const lower = query.toLowerCase(); if (lower.includes("from public.targeted_verifier_shadow_decisions") && lower.includes("where shadow_decision_id")) return { rows: this.shadowRows.filter((row) => row.shadow_decision_id === values?.[0]) as T[], rowCount: 1 }; if (lower.includes("from public.targeted_verifier_shadow_decisions") && lower.includes("where attempt_id")) return { rows: this.shadowRows.filter((row) => row.attempt_id === values?.[0]).sort((a, b) => Number(a.persist_sequence) - Number(b.persist_sequence)) as T[], rowCount: this.shadowRows.length }; return { rows: [], rowCount: 0 }; }
  async connect(): Promise<TransactionClient> { let began = false; return { release() {}, query: async <T = unknown>(query: string, values?: readonly unknown[]) => { this.sql.push(query); const lower = query.toLowerCase(); if (lower === "begin") { began = true; return { rows: [], rowCount: 0 } as QueryResult<T>; } if (lower === "commit" || lower === "rollback") { began = false; return { rows: [], rowCount: 0 } as QueryResult<T>; } if (lower.includes("from public.targeted_verifier_attempts")) return { rows: [{ payload: this.attempt }] as T[], rowCount: 1 } as QueryResult<T>; if (lower.includes("from public.targeted_verifier_generation_publications")) return { rows: [this.generation] as T[], rowCount: 1 } as QueryResult<T>; if (lower.includes("from public.targeted_verifier_shadow_decisions") && lower.includes("where shadow_decision_id")) return { rows: this.shadowRows.filter((row) => row.shadow_decision_id === values?.[0]) as T[], rowCount: 1 } as QueryResult<T>; if (lower.includes("from public.targeted_verifier_shadow_decisions") && lower.includes("where attempt_id")) return { rows: this.shadowRows.filter((row) => row.attempt_id === values?.[0]).sort((a, b) => Number(a.persist_sequence) - Number(b.persist_sequence)).slice(-1) as T[], rowCount: 1 } as QueryResult<T>; if (lower.startsWith("insert into public.targeted_verifier_shadow_decisions")) { if (this.failInsert) throw new Error("TEST_INSERT_FAILURE"); const v = values ?? []; const row: ShadowRow = { shadow_decision_id: v[0], shadow_evaluation_id: v[1], shadow_evidence_hash: v[2], attempt_id: v[3], order_hash: v[4], generation_publication_id: v[5], generation_commitment_id: v[6], active_evidence_id: v[7], state: v[8], previous_decision_id: v[9], payload: JSON.parse(String(v[10])), persist_sequence: this.shadowRows.length + 1, persisted_at: NOW }; this.shadowRows.push(row); return { rows: [row] as T[], rowCount: 1 } as QueryResult<T>; } if (!began) throw new Error("TEST_TRANSACTION_REQUIRED"); return { rows: [], rowCount: 0 } as QueryResult<T>; } }; }
  async end(): Promise<void> {}
}
function generationRow(publication: ReturnType<typeof createGenerationPublicationEvidence>): ShadowRow { return { generation_publication_id: publication.generationPublicationId, generation_commitment_id: publication.generationCommitmentId, publication_sequence: publication.publicationSequence, publication_state: publication.publicationState, sweep_id: publication.sweepId, generation_root_hash: publication.generationRootHash, candidate_artifact_hash: publication.candidateArtifactHash, barrier_artifact_hash: publication.barrierArtifactHash, candidate_model_version: publication.candidateModelVersion, generation_model_version: publication.generationModelVersion, verifier_schema_version: publication.verifierSchemaVersion, verifier_policy_version: publication.verifierPolicyVersion, provider_contract_version: publication.providerContractVersion, normalizer_version: publication.normalizerVersion, scope: publication.scope, payload: publication, source_evidence_hash: publication.sourceEvidenceHash, created_at: publication.createdAt }; }
async function fixture(): Promise<{ root: string; decision: ShadowDecisionV2; db: ShadowDb }> { const f = await makeTrustedContexts(); const context = f.contexts[0]; const publication = createGenerationPublicationEvidence({ integratedEvidence: f.evidence, protocolAddress: f.protocolAddress, createdAt: NOW }, 10); const active = deriveActiveListingsEvidence({ generationPublication: publication, integratedEvidence: f.evidence, expectedIdentity: context.expectedIdentity }); assert.equal(active.outcome, "VALID"); const attemptStore = new InMemoryTargetedVerifierAttemptStore(); const worker = __createTargetedVerifierOperationalWorkerForTest({ store: attemptStore, workerId: "shadow-store", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "test-key", execute: async () => inactiveObservation(context), postFence: async ({ providerResult }) => ({ valid: true, status: providerResult.status, postVerification: context.preVerification, reasonCodes: [] }) } satisfies Partial<TargetedVerifierOperationalWorkerOptions>); const created = await worker.createAttempt({ context, preVerification: context.preVerification, createdAt: NOW }); await worker.runOnce(created.attemptId); const attempt = await attemptStore.get(created.attemptId); assert.ok(attempt && active.outcome === "VALID"); const decision = evaluateShadowDeactivation({ candidateAttempt: attempt, currentGeneration: publication, activeEvidence: active.evidence, currentJournal: context.preVerification, laterProviderEvidence: { schemaVersion: "shadow-later-provider-evidence-v1", orderHash: context.orderHash, complete: true, entries: [] } }); assert.ok("shadowDecisionId" in decision); return { root: f.root, decision, db: new ShadowDb(attempt, generationRow(publication)) }; }

test("append, replay, and ordered listing are immutable", async () => { const f = await fixture(); try { const store = new PostgresShadowDecisionStore(f.db); const first = await store.append(f.decision); const replay = await store.append(f.decision); assert.equal(replay.shadowDecisionId, first.shadowDecisionId); assert.equal(replay.persistSequence, first.persistSequence); assert.equal(f.db.shadowRows.length, 1); const listed = await store.listForAttempt(f.decision.attemptId); assert.deepEqual(listed.map((row) => row.shadowDecisionId), [first.shadowDecisionId]); } finally { await disposeTrustedContexts(f.root); } });
test("missing source attempt fails before insert", async () => { const f = await fixture(); try { const store = new PostgresShadowDecisionStore(new ShadowDb(null, f.db.generation)); await assert.rejects(() => store.append(f.decision), /SHADOW_SOURCE_ATTEMPT_MISMATCH/); } finally { await disposeTrustedContexts(f.root); } });
test("row decoder rejects SQL/payload mismatch", async () => { const f = await fixture(); try { const store = new PostgresShadowDecisionStore(f.db); const persisted = await store.append(f.decision); const row = f.db.shadowRows[0]; assert.throws(() => decodeShadowDecisionRow({ ...row, state: "SHADOW_INELIGIBLE" }), /SHADOW_DECISION_DURABLE_CORRUPTION/); assert.equal(persisted.decision.shadowDecisionId, f.decision.shadowDecisionId); } finally { await disposeTrustedContexts(f.root); } });
test("migration is append-only and has no mutation authority columns", async () => { const source = await (await import("node:fs/promises")).readFile("sql/008_create_shadow_decisions.sql", "utf8"); assert.match(source, /CREATE TABLE IF NOT EXISTS public\.targeted_verifier_shadow_decisions/); assert.doesNotMatch(source, /\bUPDATE\b|\bDELETE\b|deactivated_at|mutation_status|applied/i); });
