import test from "node:test";
import assert from "node:assert/strict";
import { makeTrustedContexts, disposeTrustedContexts } from "./helpers/trustedVerifierContexts.js";
import { createGenerationPublicationEvidence } from "../src/reconciliation/generationPublication.js";
import { deriveActiveListingsEvidence } from "../src/reconciliation/activeListingsEvidence.js";
import { evaluateShadowDeactivation, validateShadowDecision } from "../src/reconciliation/shadowDeactivationEvaluator.js";
import { adaptOpenSeaExactOrder } from "../src/reconciliation/verifier/openSeaExactOrderAdapter.js";
import { __createTargetedVerifierOperationalWorkerForTest, InMemoryTargetedVerifierAttemptStore, type TargetedVerifierOperationalWorkerOptions } from "../src/reconciliation/verifier/targetedVerifierOperationalWorker.js";
import type { TargetedVerifierContext } from "../src/reconciliation/verifier/targetedVerifierTypes.js";

const NOW = "2026-01-01T00:00:00.000Z";
function inactiveObservation(context: TargetedVerifierContext): ReturnType<typeof adaptOpenSeaExactOrder> { const order = { order_hash: context.orderHash, chain: context.chain, protocol_address: context.protocolAddress, status: "INACTIVE", type: "basic", price: { current: { currency: "ETH", decimals: 18, value: "1" } }, asset: { contract: context.contractAddress, identifier: context.expectedIdentity.tokenId }, remaining_quantity: 1, protocol_data: { parameters: { offerer: "0x" + "2".repeat(40), consideration: [{ itemType: 2, token: context.contractAddress, identifierOrCriteria: context.expectedIdentity.tokenId, startAmount: "1", endAmount: "1", recipient: "0x" + "2".repeat(40) }], zone: "0x" + "3".repeat(40), zoneHash: "0x" + "0".repeat(64), salt: "1", conduitKey: "0x" + "0".repeat(64), totalOriginalConsiderationItems: 0, counter: 0, orderType: 0, startTime: "1760000000", endTime: "1760001000", offer: [{ itemType: 2, token: context.contractAddress, identifierOrCriteria: context.expectedIdentity.tokenId, startAmount: "1", endAmount: "1" }] } } }; return adaptOpenSeaExactOrder({ context, httpStatus: 200, body: new TextEncoder().encode(JSON.stringify({ order })), headers: [{ name: "Content-Type", value: "application/json" }, { name: "Content-Encoding", value: "identity" }, { name: "Date", value: "Thu, 01 Jan 2026 00:00:00 GMT" }], timing: { requestStartedAt: NOW, responseHeadersAt: "2026-01-01T00:00:00.100Z", responseCompletedAt: "2026-01-01T00:00:00.200Z", elapsedMs: 200, overallDeadlineMs: 1000, deadlineExceeded: false } }); }
async function positiveFixture() { const f = await makeTrustedContexts(); const context = f.contexts[0]; const publication = createGenerationPublicationEvidence({ integratedEvidence: f.evidence, protocolAddress: f.protocolAddress, createdAt: NOW }, 10); const active = deriveActiveListingsEvidence({ generationPublication: publication, integratedEvidence: f.evidence, expectedIdentity: context.expectedIdentity }); assert.equal(active.outcome, "VALID"); const store = new InMemoryTargetedVerifierAttemptStore(); const options: Partial<TargetedVerifierOperationalWorkerOptions> = { now: () => NOW, nowMs: () => 0, credentialProvider: async () => "test-key", execute: async () => inactiveObservation(context), postFence: async ({ providerResult }) => ({ valid: true, status: providerResult.status, postVerification: context.preVerification, reasonCodes: [] }) }; const worker = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "shadow-test", ...options }); const created = await worker.createAttempt({ context, preVerification: context.preVerification, createdAt: NOW }); const run = await worker.runOnce(created.attemptId); assert.equal(run.outcome, "COMPLETE"); const candidate = await store.get(created.attemptId); assert.ok(candidate); return { f, publication, active: active.outcome === "VALID" ? active.evidence : null, candidate, journal: context.preVerification }; }

test("pure evaluator emits deterministic audit-only SHADOW_ELIGIBLE", async () => { const fixture = await positiveFixture(); try { assert.ok(fixture.candidate && fixture.active); const input = { candidateAttempt: fixture.candidate, currentGeneration: fixture.publication, activeEvidence: fixture.active, currentJournal: fixture.journal, laterProviderEvidence: { schemaVersion: "shadow-later-provider-evidence-v1" as const, orderHash: fixture.candidate!.orderHash, complete: true, entries: [] } }; const first = evaluateShadowDeactivation(input); const second = evaluateShadowDeactivation(input); assert.equal(first.state, "SHADOW_ELIGIBLE"); assert.deepEqual(first, second); assert.equal(first.authorityGranted, false); assert.equal(first.deactivationAuthorityGranted, false); assert.equal(first.mutationAuthorityGranted, false); assert.equal(validateShadowDecision(first), true); } finally { await disposeTrustedContexts(fixture.f.root); } });
