import test from "node:test";
import assert from "node:assert/strict";
import { makeTrustedContexts, disposeTrustedContexts } from "./helpers/trustedVerifierContexts.js";
import { createGenerationPublicationEvidence } from "../src/reconciliation/generationPublication.js";
import { deriveActiveListingsEvidence, CurrentActiveListingsEvidenceSource } from "../src/reconciliation/activeListingsEvidence.js";
import { __createTargetedVerifierOperationalWorkerForTest, InMemoryTargetedVerifierAttemptStore, type TargetedVerifierOperationalWorkerOptions } from "../src/reconciliation/verifier/targetedVerifierOperationalWorker.js";
import { adaptOpenSeaExactOrder } from "../src/reconciliation/verifier/openSeaExactOrderAdapter.js";
import { ShadowProductionOrchestrator } from "../src/reconciliation/shadowProductionOrchestrator.js";

const NOW = "2026-01-01T00:00:00.000Z";
function observation(context: any) { const order = { order_hash: context.orderHash, chain: context.chain, protocol_address: context.protocolAddress, status: "INACTIVE", type: "basic", price: { current: { currency: "ETH", decimals: 18, value: "1" } }, asset: { contract: context.contractAddress, identifier: context.expectedIdentity.tokenId }, remaining_quantity: 1, protocol_data: { parameters: { offerer: "0x" + "2".repeat(40), consideration: [{ itemType: 2, token: context.contractAddress, identifierOrCriteria: context.expectedIdentity.tokenId, startAmount: "1", endAmount: "1", recipient: "0x" + "2".repeat(40) }], zone: "0x" + "3".repeat(40), zoneHash: "0x" + "0".repeat(64), salt: "1", conduitKey: "0x" + "0".repeat(64), totalOriginalConsiderationItems: 0, counter: 0, orderType: 0, startTime: "1760000000", endTime: "1760001000", offer: [{ itemType: 2, token: context.contractAddress, identifierOrCriteria: context.expectedIdentity.tokenId, startAmount: "1", endAmount: "1" }] } } }; return adaptOpenSeaExactOrder({ context, httpStatus: 200, body: new TextEncoder().encode(JSON.stringify({ order })), headers: [{ name: "Content-Type", value: "application/json" }, { name: "Content-Encoding", value: "identity" }, { name: "Date", value: "Thu, 01 Jan 2026 00:00:00 GMT" }], timing: { requestStartedAt: NOW, responseHeadersAt: "2026-01-01T00:00:00.100Z", responseCompletedAt: "2026-01-01T00:00:00.200Z", elapsedMs: 200, overallDeadlineMs: 1000, deadlineExceeded: false } }); }
async function fixture() { const f = await makeTrustedContexts(); const context = f.contexts[0]; const publication = createGenerationPublicationEvidence({ integratedEvidence: f.evidence, protocolAddress: f.protocolAddress, createdAt: NOW }, 10); const active = deriveActiveListingsEvidence({ generationPublication: publication, integratedEvidence: f.evidence, expectedIdentity: context.expectedIdentity }); assert.equal(active.outcome, "VALID"); const store = new InMemoryTargetedVerifierAttemptStore(); const worker = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "shadow-production", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "test", execute: async () => observation(context), postFence: async ({ providerResult }) => ({ valid: true, status: providerResult.status, postVerification: context.preVerification, reasonCodes: [] }) } satisfies Partial<TargetedVerifierOperationalWorkerOptions>); const made = await worker.createAttempt({ context, preVerification: context.preVerification, createdAt: NOW }); await worker.runOnce(made.attemptId); const attempt = await store.get(made.attemptId); assert.ok(attempt && active.outcome === "VALID"); return { f, context, publication, active: active.evidence, attempt, journal: context.preVerification }; }
function deps(f: any, overrides: any = {}) { const generationStore = { getCurrentAcceptedGeneration: async () => ({ outcome: "CURRENT" as const, publication: f.publication }) }; const activeSource = new CurrentActiveListingsEvidenceSource(generationStore, { resolve: async () => f.f.evidence }); const defaults = { pool: {} as any, generationStore, activeSource, journalReader: { readSnapshot: async () => f.journal }, laterReader: { read: async () => ({ outcome: "COMPLETE" as const, snapshot: { schemaVersion: "shadow-later-provider-evidence-v1", orderHash: f.attempt.orderHash, complete: true, entries: [] } }) }, decisionStore: { append: async (decision: any) => ({ shadowDecisionId: decision.shadowDecisionId, persistSequence: 1, previousDecisionId: null, persistedAt: NOW, decision }), get: async () => null, listForAttempt: async () => [] }, attemptReader: { get: async () => f.attempt, listCandidates: async () => [f.attempt] } }; return { ...defaults, ...overrides }; }
test("real inactive attempt reaches eligible and stable persist", async () => { const f = await fixture(); try { let appends = 0; const d = deps(f, { decisionStore: { ...deps(f).decisionStore, append: async (decision: any) => { appends++; return { shadowDecisionId: decision.shadowDecisionId, persistSequence: 1, previousDecisionId: null, persistedAt: NOW, decision }; } } }); const result = await new ShadowProductionOrchestrator(d).runAttempt(f.attempt.attemptId, { persist: true }); assert.equal(result.outcome, "PERSISTED"); assert.equal(result.decision?.state, "SHADOW_ELIGIBLE"); assert.equal(appends, 1); } finally { await disposeTrustedContexts(f.f.root); } });
test("dry run performs no insert", async () => { const f = await fixture(); try { let count = 0; const d = deps(f, { decisionStore: { ...deps(f).decisionStore, append: async () => { count++; throw new Error("unexpected"); } } }); const result = await new ShadowProductionOrchestrator(d).runAttempt(f.attempt.attemptId); assert.equal(result.outcome, "EVALUATED"); assert.equal(count, 0); } finally { await disposeTrustedContexts(f.f.root); } });
test("generation/active race suppresses persistence", async () => { const f = await fixture(); try { let calls = 0, appends = 0; const generationStore = { getCurrentAcceptedGeneration: async () => { calls++; return { outcome: "CURRENT" as const, publication: f.publication }; } }; const activeSource = { resolve: async () => calls > 1 ? ({ outcome: "ACTIVE_EVIDENCE_UNPROVEN" as const, evidence: null, reasonCodes: ["CURRENT_GENERATION_CONFLICT"] }) : ({ outcome: "CURRENT_ACTIVE_EVIDENCE" as const, evidence: f.active }) }; const d = deps(f, { generationStore, activeSource, decisionStore: { ...deps(f).decisionStore, append: async () => { appends++; throw new Error("unexpected"); } } }); const result = await new ShadowProductionOrchestrator(d).runAttempt(f.attempt.attemptId, { persist: true }); assert.notEqual(result.outcome, "PERSISTED"); assert.equal(appends, 0); } finally { await disposeTrustedContexts(f.f.root); } });
test("retry exhausted candidate is not processed", async () => { const f = await fixture(); try { const candidate = { ...f.attempt, lifecycle: "COMPLETE", failureClassification: "RETRY_EXHAUSTED", retry: { ...f.attempt.retry, retryable: true } }; const d = deps(f, { attemptReader: { get: async () => candidate, listCandidates: async () => [] } }); const result = await new ShadowProductionOrchestrator(d).runAttempt(candidate.attemptId); assert.equal(result.outcome, "NOT_A_SHADOW_CANDIDATE"); } finally { await disposeTrustedContexts(f.f.root); } });
