import test from "node:test";
import assert from "node:assert/strict";
import type { DbPool, QueryResult, TransactionClient } from "../src/db/types.js";
import { PostgresTargetedVerifierAttemptStore, type OperationalAttemptRecord } from "../src/reconciliation/verifier/targetedVerifierOperationalWorker.js";

type Row={payload:OperationalAttemptRecord;lifecycle:string;claimedAt:string|null;leaseExpiresAt:string|null;leaseToken:string|null;nextAttemptAt:string|null;failureClassification:string|null};
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
const rec=(id="a",lifecycle:OperationalAttemptRecord["lifecycle"]="NOT_STARTED"):OperationalAttemptRecord=>({attemptId:id,attemptNumber:0,idempotencyKey:"i-"+id,sweepId:"s",orderHash:"0x"+"a".repeat(64),candidateArtifactHash:"a".repeat(64),barrierArtifactHash:"b".repeat(64),generationRootHash:"c".repeat(64),candidateModelVersion:"c",generationModelVersion:"g",verifierSchemaVersion:"s",verifierPolicyVersion:"p",providerContractVersion:"v",normalizerVersion:"n",expectedIdentity:{orderHash:"0x"+"a".repeat(64),chain:"gunzilla",contractAddress:"0x"+"b".repeat(40),tokenId:"1",collectionSlug:"x",protocolAddress:"0x"+"d".repeat(40)},requestIdentity:{method:"GET",endpointPath:"/orders",chain:"gunzilla",protocolAddress:"0x"+"d".repeat(40),orderHash:"0x"+"a".repeat(64)},lifecycle,leaseToken:null,createdAt:"2026-01-01T00:00:00.000Z",claimedAt:null,leaseExpiresAt:null,verificationStartedAt:null,verificationCompletedAt:null,providerObservedAt:null,httpStatus:null,transportOutcome:null,responseBodySha256:null,rawResponseArtifactHash:null,normalizedProviderStatus:null,providerResultStatus:null,providerResultReasonCodes:[],normalizedOrder:null,reasonCodes:[],retry:{retryable:false,retryReason:"NONE",recommendedPolicyClass:"NONE"},preVerificationWatermark:{eventId:"0",receivedAt:"2026-01-01T00:00:00.000Z"},postVerificationWatermark:null,preRelevantFingerprint:{orderHash:"0x"+"a".repeat(64),eventIds:[],events:[],digest:"0".repeat(64),orderingAmbiguous:false},postRelevantFingerprint:null,semanticEvidenceHash:null,authorityGranted:false,deactivationAuthorityGranted:false,failureClassification:null,nextAttemptAt:null});
class AttemptDb implements DbPool{
 rows=new Map<string,Row>(); sql:string[]=[];
 async end(){} async connect():Promise<TransactionClient>{return {release(){},query:(q,v)=>this.query(q,v)}}
 private out<T>(rows:T[],rowCount=rows.length):QueryResult<T>{return {rows,rowCount};}
 async query<T=unknown>(q:string,v?:readonly unknown[]):Promise<QueryResult<T>>{const l=q.toLowerCase();this.sql.push(q);
  if(l.startsWith("insert into public.targeted_verifier_attempts")){const p=JSON.parse(String(v?.[11])) as OperationalAttemptRecord;const old=[...this.rows.values()].find(x=>x.payload.idempotencyKey===p.idempotencyKey);if(old)return this.out([{payload:clone(old.payload)} as T]);this.rows.set(p.attemptId,{payload:clone(p),lifecycle:p.lifecycle,claimedAt:p.claimedAt,leaseExpiresAt:p.leaseExpiresAt,leaseToken:p.leaseToken,nextAttemptAt:p.nextAttemptAt,failureClassification:p.failureClassification});return this.out([{payload:clone(p)} as T]);}
  if(l.startsWith("select payload from public.targeted_verifier_attempts where ((")){const now=Date.parse(String(v?.[0]));const rows=[...this.rows.values()].filter(r=>{const leaseFree=!r.leaseToken||!r.leaseExpiresAt||Date.parse(r.leaseExpiresAt)<=now;if(r.lifecycle==="NOT_STARTED")return (!r.nextAttemptAt||Date.parse(r.nextAttemptAt)<=now)&&leaseFree;if(r.lifecycle==="RESPONSE_OBSERVED"||r.lifecycle==="PENDING_FENCE")return leaseFree;return false;}).slice(0,Number(v?.[1]??99)).map(r=>({payload:clone(r.payload)} as T));return this.out(rows);}
  if(l.startsWith("select payload")){const r=this.rows.get(String(v?.[0]));return this.out(r?[{payload:clone(r.payload)} as T]:[]);}
  if(l.startsWith("update public.targeted_verifier_attempts set lifecycle=case when lifecycle='request_pending'")){let n=0;const now=Date.parse(String(v?.[0]));for(const r of this.rows.values()){if(!r.leaseExpiresAt||Date.parse(r.leaseExpiresAt)>now||!["REQUEST_PENDING","RESPONSE_OBSERVED","PENDING_FENCE"].includes(r.lifecycle))continue;const old=r.lifecycle;r.lifecycle=old==="REQUEST_PENDING"?"FAILED":old;r.failureClassification=old==="REQUEST_PENDING"?"REQUEST_OUTCOME_UNCERTAIN":r.failureClassification;r.leaseToken=null;r.leaseExpiresAt=null;r.payload={...r.payload,lifecycle:r.lifecycle as OperationalAttemptRecord["lifecycle"],failureClassification:r.failureClassification,leaseToken:null,leaseExpiresAt:null};n++;}return this.out([],n);}
  if(l.startsWith("update public.targeted_verifier_attempts set lifecycle=case")){const r=this.rows.get(String(v?.[0]));if(!r)return this.out([]);const now=Date.parse(String(v?.[1]));const dueNow=(!r.nextAttemptAt||Date.parse(r.nextAttemptAt)<=now);const leaseFree=!r.leaseToken||!r.leaseExpiresAt||Date.parse(r.leaseExpiresAt)<=now;const runnable=(r.lifecycle==="NOT_STARTED"&&dueNow&&leaseFree)||( (r.lifecycle==="RESPONSE_OBSERVED"||r.lifecycle==="PENDING_FENCE")&&leaseFree);if(!runnable)return this.out([]);const token=String(v?.[3]);r.lifecycle=r.lifecycle==="NOT_STARTED"?"REQUEST_PENDING":r.lifecycle;r.claimedAt=String(v?.[1]);r.leaseExpiresAt=String(v?.[2]);r.leaseToken=token;r.payload={...r.payload,lifecycle:r.lifecycle as OperationalAttemptRecord["lifecycle"],claimedAt:r.claimedAt,leaseExpiresAt:r.leaseExpiresAt,leaseToken:token,verificationStartedAt:r.payload.verificationStartedAt??r.claimedAt};return this.out([{payload:clone(r.payload)} as T]);}
  if(l.startsWith("update public.targeted_verifier_attempts set lifecycle=$3")){const r=this.rows.get(String(v?.[0]));const now=Date.parse(String(v?.[9]));if(!r||!(r.lifecycle==="REQUEST_PENDING"||r.lifecycle==="RESPONSE_OBSERVED"||r.lifecycle==="PENDING_FENCE")||r.leaseToken!==String(v?.[1])||!r.leaseExpiresAt||Date.parse(r.leaseExpiresAt)<=now)return this.out([],0);const p=JSON.parse(String(v?.[3])) as OperationalAttemptRecord;r.payload=clone(p);r.lifecycle=p.lifecycle;r.claimedAt=p.claimedAt;r.leaseExpiresAt=p.leaseExpiresAt;r.leaseToken=p.leaseToken;r.nextAttemptAt=p.nextAttemptAt;r.failureClassification=p.failureClassification;return this.out([],1);}
  throw new Error("UNSUPPORTED_SQL:"+q);
 }}
const parity=(db:AttemptDb,id:string)=>{const r=db.rows.get(id);assert.ok(r);assert.equal(r.lifecycle,r.payload.lifecycle);assert.equal(r.claimedAt,r.payload.claimedAt);assert.equal(r.leaseExpiresAt,r.payload.leaseExpiresAt);assert.equal(r.leaseToken,r.payload.leaseToken);assert.equal(r.nextAttemptAt,r.payload.nextAttemptAt);assert.equal(r.failureClassification,r.payload.failureClassification);};
const evidence=(r:OperationalAttemptRecord)=>({providerObservedAt:r.providerObservedAt,httpStatus:r.httpStatus,transportOutcome:r.transportOutcome,responseBodySha256:r.responseBodySha256,rawResponseArtifactHash:r.rawResponseArtifactHash,normalizedProviderStatus:r.normalizedProviderStatus,providerResultStatus:r.providerResultStatus,providerResultReasonCodes:r.providerResultReasonCodes,normalizedOrder:r.normalizedOrder,retry:r.retry});
test("Postgres attempt store create/get/claim/CAS parity",async()=>{const db=new AttemptDb();const s=new PostgresTargetedVerifierAttemptStore(db);const r=rec();assert.deepEqual(await s.createOrGet(r),r);assert.deepEqual(await s.createOrGet({...r,providerResultStatus:"MUTATED"}),r);parity(db,"a");const c=await s.claim("a","w","2026-01-01T00:00:00.000Z",1000);assert.ok(c);parity(db,"a");const before=clone(await s.get("a"));assert.equal(await s.complete("a","wrong",{...c.record,lifecycle:"COMPLETE"},"2026-01-01T00:00:00.100Z"),false);assert.deepEqual(await s.get("a"),before);assert.equal(await s.complete("a",c.leaseToken,{...c.record,lifecycle:"COMPLETE",leaseToken:null,leaseExpiresAt:null},"2026-01-01T00:00:00.100Z"),true);parity(db,"a");});
test("Postgres recovery/reclaim/CAS transitions preserve evidence and retry",async()=>{const db=new AttemptDb();const s=new PostgresTargetedVerifierAttemptStore(db);const o=rec("o","RESPONSE_OBSERVED");const rich={...o,leaseToken:"old",leaseExpiresAt:"2025-12-31T23:59:00.000Z",claimedAt:"2025-12-31T23:58:00.000Z",verificationStartedAt:"2025-12-31T23:00:00.000Z",providerObservedAt:"2025-12-31T23:01:00.000Z",httpStatus:429,transportOutcome:"HTTP_ERROR",responseBodySha256:"r",rawResponseArtifactHash:"a",normalizedProviderStatus:"INACTIVE",providerResultStatus:"INACTIVE_CONFIRMED",providerResultReasonCodes:["RATE_LIMITED"],retry:{retryable:true,retryReason:"RATE_LIMITED",recommendedPolicyClass:"RATE_LIMITED"}};await s.createOrGet(rich);const ev=evidence(rich);const c=await s.claim("o","new","2026-01-01T00:00:00.000Z",1000);assert.ok(c);assert.deepEqual(evidence((await s.get("o"))!),ev);parity(db,"o");assert.equal(await s.saveResponse("o","bad",rich,"2026-01-01T00:00:00.100Z"),false);assert.equal(await s.saveResponse("o",c.leaseToken,{...c.record,lifecycle:"RESPONSE_OBSERVED"},"2026-01-01T00:00:00.100Z"),true);parity(db,"o");assert.deepEqual((await s.get("o"))?.retry,rich.retry);const p=rec("p","PENDING_FENCE");p.leaseToken="p";p.leaseExpiresAt="2026-01-01T00:00:10.000Z";p.retry={retryable:true,retryReason:"TRANSIENT_TRANSPORT",recommendedPolicyClass:"TRANSIENT_TRANSPORT"};await s.createOrGet(p);assert.equal(await s.reclaimExpired("2026-01-01T00:00:11.000Z"),2);parity(db,"o");parity(db,"p");assert.equal((await s.get("p"))?.lifecycle,"PENDING_FENCE");assert.deepEqual((await s.get("p"))?.retry,p.retry);});
test("Postgres recovery claims preserve lifecycle, evidence and original verification time",async()=>{const db=new AttemptDb();const s=new PostgresTargetedVerifierAttemptStore(db);for(const [id,lifecycle] of [["ro","RESPONSE_OBSERVED"],["pf","PENDING_FENCE"]] as const){const r={...rec(id,lifecycle),verificationStartedAt:"2025-12-31T23:00:00.000Z",providerObservedAt:"2025-12-31T23:01:00.000Z",providerResultStatus:"INACTIVE_CONFIRMED",retry:{retryable:true,retryReason:"RATE_LIMITED",recommendedPolicyClass:"RATE_LIMITED"},leaseToken:null,leaseExpiresAt:null};await s.createOrGet(r);const c=await s.claim(id,"recover","2026-01-01T00:00:00.000Z",1000);assert.ok(c);assert.equal(c.record.lifecycle,lifecycle);assert.equal(c.record.verificationStartedAt,r.verificationStartedAt);assert.equal(c.record.providerResultStatus,r.providerResultStatus);assert.deepEqual(c.record.retry,r.retry);parity(db,id);}});
test("Postgres listDue excludes active recovery leases",async()=>{const db=new AttemptDb();const s=new PostgresTargetedVerifierAttemptStore(db);await s.createOrGet(rec("n"));await s.createOrGet(rec("o","RESPONSE_OBSERVED"));await s.createOrGet(rec("p","PENDING_FENCE"));assert.ok(await s.claim("o","w","2026-01-01T00:00:00.000Z",100000));const ids=(await s.listDue("2026-01-01T00:00:01.000Z",10)).map(x=>x.attemptId).sort();assert.deepEqual(ids,["n","p"]);});
test("Postgres listDue full lifecycle matrix",async()=>{const db=new AttemptDb();const s=new PostgresTargetedVerifierAttemptStore(db);const rows=[{id:"n-due",l:"NOT_STARTED" as const},{id:"n-future",l:"NOT_STARTED" as const,next:"2026-01-02T00:00:00.000Z"},{id:"n-active",l:"NOT_STARTED" as const,token:"a",expiry:"2026-01-01T01:00:00.000Z"},{id:"n-expired",l:"NOT_STARTED" as const,token:"b",expiry:"2025-12-31T23:00:00.000Z"},{id:"o-free",l:"RESPONSE_OBSERVED" as const},{id:"o-active",l:"RESPONSE_OBSERVED" as const,token:"c",expiry:"2026-01-01T01:00:00.000Z"},{id:"o-expired",l:"RESPONSE_OBSERVED" as const,token:"d",expiry:"2025-12-31T23:00:00.000Z"},{id:"o-future",l:"RESPONSE_OBSERVED" as const,next:"2026-01-02T00:00:00.000Z"},{id:"p-free",l:"PENDING_FENCE" as const},{id:"p-active",l:"PENDING_FENCE" as const,token:"e",expiry:"2026-01-01T01:00:00.000Z"},{id:"p-expired",l:"PENDING_FENCE" as const,token:"f",expiry:"2025-12-31T23:00:00.000Z"},{id:"p-future",l:"PENDING_FENCE" as const,next:"2026-01-02T00:00:00.000Z"}];for(const x of rows){await s.createOrGet({...rec(x.id,x.l),nextAttemptAt:x.next??null,leaseToken:x.token??null,leaseExpiresAt:x.expiry??null});}const ids=(await s.listDue("2026-01-01T00:00:00.000Z",20)).map(x=>x.attemptId).sort();assert.deepEqual(ids,["n-due","n-expired","o-expired","o-free","o-future","p-expired","p-free","p-future"]);});
test("REQUEST_PENDING expiry fails closed in indexed and payload state",async()=>{const db=new AttemptDb();const s=new PostgresTargetedVerifierAttemptStore(db);const r=rec("u","REQUEST_PENDING");r.leaseToken="u-token";r.leaseExpiresAt="2026-01-01T00:00:00.100Z";r.claimedAt="2026-01-01T00:00:00.000Z";await s.createOrGet(r);assert.equal(await s.reclaimExpired("2026-01-01T00:00:01.000Z"),1);const got=await s.get("u");assert.equal(got?.lifecycle,"FAILED");assert.equal(got?.failureClassification,"REQUEST_OUTCOME_UNCERTAIN");assert.equal(got?.leaseToken,null);assert.equal(got?.leaseExpiresAt,null);parity(db,"u");});
test("Postgres CAS expiry, takeover, fail and retry parity",async()=>{const db=new AttemptDb();const s=new PostgresTargetedVerifierAttemptStore(db);await s.createOrGet(rec("x","RESPONSE_OBSERVED"));const a=await s.claim("x","a","2026-01-01T00:00:00.000Z",1000);assert.ok(a);const before=clone(await s.get("x"));assert.equal(await s.fail("x",a.leaseToken,{...a.record,lifecycle:"FAILED",failureClassification:"TEST_FAILURE"},"2026-01-01T00:00:01.000Z"),false);assert.deepEqual(await s.get("x"),before);const b=await s.claim("x","b","2026-01-01T00:00:01.001Z",1000);assert.ok(b);assert.equal(await s.complete("x",a.leaseToken,{...b.record,lifecycle:"COMPLETE"},"2026-01-01T00:00:01.100Z"),false);assert.equal(await s.scheduleRetry("x",b.leaseToken,{...b.record,nextAttemptAt:"2026-01-01T00:10:00.000Z"},"2026-01-01T00:00:01.100Z"),true);parity(db,"x");});
test("Postgres successful fail clears both lease representations",async()=>{const db=new AttemptDb();const s=new PostgresTargetedVerifierAttemptStore(db);await s.createOrGet(rec("f"));const c=await s.claim("f","w","2026-01-01T00:00:00.000Z",1000);assert.ok(c);const rich={...c.record,providerResultStatus:"INACTIVE_CONFIRMED",retry:{retryable:true,retryReason:"RATE_LIMITED",recommendedPolicyClass:"RATE_LIMITED"},failureClassification:"TEST_FAILURE"};assert.equal(await s.fail("f",c.leaseToken,{...rich,lifecycle:"FAILED",leaseToken:null,leaseExpiresAt:null},"2026-01-01T00:00:00.100Z"),true);const got=await s.get("f");assert.equal(got?.lifecycle,"FAILED");assert.equal(got?.failureClassification,"TEST_FAILURE");assert.equal(got?.leaseToken,null);assert.equal(got?.leaseExpiresAt,null);assert.equal(got?.providerResultStatus,"INACTIVE_CONFIRMED");assert.deepEqual(got?.retry,rich.retry);parity(db,"f");});
test("Postgres rejects future NOT_STARTED and terminal claims",async()=>{const db=new AttemptDb();const s=new PostgresTargetedVerifierAttemptStore(db);const future={...rec("future"),nextAttemptAt:"2026-01-02T00:00:00.000Z"};await s.createOrGet(future);assert.equal(await s.claim("future","w","2026-01-01T00:00:00.000Z",1000),null);for(const lifecycle of ["COMPLETE","FAILED"] as const){const r={...rec(lifecycle.toLowerCase(),lifecycle),leaseToken:"x",leaseExpiresAt:"2026-01-01T01:00:00.000Z"};await s.createOrGet(r);assert.equal(await s.claim(r.attemptId,"w","2026-01-01T00:00:00.000Z",1000),null);}});
