import assert from "node:assert/strict";
import test from "node:test";
import { makeTrustedContexts, disposeTrustedContexts } from "./helpers/trustedVerifierContexts.js";
import {
  InMemoryTargetedVerifierAttemptStore, __createTargetedVerifierOperationalWorkerForTest,
  createTargetedVerifierOperationalWorker,
  type TargetedVerifierOperationalProductionOptions,
  type TargetedVerifierOperationalWorkerOptions,
  operationalSemanticEvidenceHash, type OperationalAttemptRecord
} from "../src/reconciliation/verifier/targetedVerifierOperationalWorker.js";
import type { ProviderResult, TargetedVerifierContext } from "../src/reconciliation/verifier/targetedVerifierTypes.js";
import { adaptOpenSeaExactOrder } from "../src/reconciliation/verifier/openSeaExactOrderAdapter.js";
import { interpretOpenSeaExactOrderObservation } from "../src/reconciliation/verifier/targetedVerifierNormalizer.js";
import { operationalIdempotencyKey } from "../src/reconciliation/verifier/targetedVerifierOperationalWorker.js";

const NOW = "2026-01-01T00:00:00.000Z";
// @ts-expect-error production construction requires a reader and rejects arbitrary postFence
const productionSurfaceTypeGuard: TargetedVerifierOperationalProductionOptions = { postFence: async () => undefined };
const retryNone = { retryable: false, retryReason: "NONE", recommendedPolicyClass: "NONE" as const };
const retryRate = { retryable: true, retryReason: "RATE_LIMITED", recommendedPolicyClass: "RATE_LIMITED" as const };
const retryTransient = { retryable: true, retryReason: "TRANSIENT_TRANSPORT", recommendedPolicyClass: "TRANSIENT_TRANSPORT" as const };

function result(status: ProviderResult["status"], retry = retryNone, providerStatus: ProviderResult["providerStatus"] = null): ProviderResult {
  return { status, reasonCodes: status === "RATE_LIMITED" ? ["HTTP_429"] : status === "TRANSPORT_FAILED" ? ["REQUEST_TIMEOUT"] : [], providerStatus, normalizedOrder: null, observedAt: NOW, responseBodySha256: null, rawResponseArtifactHash: null, httpStatus: status === "RATE_LIMITED" ? 429 : status === "TRANSPORT_FAILED" ? null : 200, retry, authorityGranted: false, deactivationAuthorityGranted: false } as ProviderResult;
}
function observation(context: TargetedVerifierContext, status: ProviderResult["status"]): ReturnType<typeof adaptOpenSeaExactOrder> {
  if (status === "RATE_LIMITED") return adaptOpenSeaExactOrder({ context, httpStatus: 429, body: null });
  if (status === "TRANSPORT_FAILED") return adaptOpenSeaExactOrder({ context, transportOutcome: "TIMEOUT", httpStatus: null, body: null });
  if (status === "MALFORMED_RESPONSE") return adaptOpenSeaExactOrder({ context, httpStatus: 200, body: new TextEncoder().encode("{}"), headers: [{ name: "Content-Type", value: "application/json" }] });
  const order = { order_hash: context.orderHash, chain: context.chain, protocol_address: context.protocolAddress, status: "INACTIVE", type: "basic", price: { current: { currency: "ETH", decimals: 18, value: "1" } }, asset: { contract: context.contractAddress, identifier: context.expectedIdentity.tokenId }, remaining_quantity: 1, protocol_data: { parameters: { offerer: "0x" + "2".repeat(40), consideration: [{ itemType: 2, token: context.contractAddress, identifierOrCriteria: context.expectedIdentity.tokenId, startAmount: "1", endAmount: "1", recipient: "0x" + "2".repeat(40) }], zone: "0x" + "3".repeat(40), zoneHash: "0x" + "0".repeat(64), salt: "1", conduitKey: "0x" + "0".repeat(64), totalOriginalConsiderationItems: 0, counter: 0, orderType: 0, startTime: "1760000000", endTime: "1760001000", offer: [{ itemType: 2, token: context.contractAddress, identifierOrCriteria: context.expectedIdentity.tokenId, startAmount: "1", endAmount: "1" }] } } };
  return adaptOpenSeaExactOrder({ context, httpStatus: 200, body: new TextEncoder().encode(JSON.stringify({ order })), headers: [{ name: "Content-Type", value: "application/json" }, { name: "Content-Encoding", value: "identity" }, { name: "Date", value: "Thu, 01 Jan 2026 00:00:00 GMT" }], timing: { requestStartedAt: "2026-01-01T00:00:00.000Z", responseHeadersAt: "2026-01-01T00:00:00.100Z", responseCompletedAt: "2026-01-01T00:00:00.200Z", elapsedMs: 200, overallDeadlineMs: 1000, deadlineExceeded: false } });
}
function fence(valid = true, status: "STABLE" | "STALE" | "RECONCILIATION_REQUIRED" = "STABLE") { return { valid, status, postVerification: { watermark: { eventId: "100", receivedAt: NOW }, relevantOrderFingerprint: { orderHash: "0x" + "a".repeat(64), eventIds: [], digest: "0".repeat(64), orderingAmbiguous: false } }, reasonCodes: valid ? [] : [status === "STALE" ? "HTTP_STATUS_OR_BODY_UNPROVEN" : "RECONCILIATION_REQUIRED"] }; }
async function setup() { const x = await makeTrustedContexts(); return x; }
function worker(store: InMemoryTargetedVerifierAttemptStore, context: TargetedVerifierContext, execution: ProviderResult, options: Partial<TargetedVerifierOperationalWorkerOptions> = {}) {
  return __createTargetedVerifierOperationalWorkerForTest({ store, workerId: options.workerId ?? "w1", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "TEST_ONLY_FAKE_OPENSEA_KEY", execute: async () => observation(context, execution.status), postFence: async () => fence(), ...options });
}
async function create(w: TargetedVerifierOperationalWorker, c: TargetedVerifierContext) { return w.createAttempt({ context: c, preVerification: c.preVerification, createdAt: NOW }); }

test("confirmed provider status families remain read-only", async () => { const { root, contexts } = await setup(); try { for (const [status, provider] of [["ACTIVE_CONFIRMED", "ACTIVE"], ["INACTIVE_CONFIRMED", "INACTIVE"], ["EXPIRED_CONFIRMED", "EXPIRED"], ["TERMINAL_CONFIRMED", "FULFILLED"]] as const) { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result(status, retryNone, provider)); const a = await create(w, contexts[0]); const r = await w.runOnce(a.attemptId); assert.equal(r.outcome, "COMPLETE"); assert.equal(r.record?.authorityGranted, false); assert.equal(r.record?.deactivationAuthorityGranted, false); } } finally { await disposeTrustedContexts(root); } });

test("idempotent attempts, lifecycle completion and authority invariants", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("INACTIVE_CONFIRMED", retryNone, "INACTIVE")); const a = await create(w, contexts[0]); const b = await create(w, contexts[0]); assert.equal(a.attemptId, b.attemptId); const run = await w.runOnce(a.attemptId); assert.equal(run.outcome, "COMPLETE"); assert.equal(run.record?.lifecycle, "COMPLETE"); assert.equal(run.record?.authorityGranted, false); assert.equal(run.record?.deactivationAuthorityGranted, false); } finally { await disposeTrustedContexts(root); } });

test("exclusive claim and stale lease completion", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const a = await create(w, contexts[0]); const [x, y] = await Promise.all([store.claim(a.attemptId, "a", NOW, 1000), store.claim(a.attemptId, "b", NOW, 1000)]); assert.equal(Boolean(x) !== Boolean(y), true); const owner = x ?? y!; assert.equal(await store.complete(a.attemptId, "stale", owner.record), false); } finally { await disposeTrustedContexts(root); } });

test("expired lease is reclaimed fail-closed", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const a = await create(w, contexts[0]); await store.claim(a.attemptId, "a", NOW, 1); assert.equal(await store.reclaimExpired("2026-01-01T00:00:01.000Z"), 1); assert.equal((await store.get(a.attemptId))?.failureClassification, "REQUEST_OUTCOME_UNCERTAIN"); } finally { await disposeTrustedContexts(root); } });

test("retryable results are delayed and bounded", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("RATE_LIMITED", retryRate), { policy: { maxAttempts: 2, rateLimitedDelayMs: 60_000 } }); const a = await create(w, contexts[0]); const run = await w.runOnce(a.attemptId); assert.equal(run.outcome, "RETRY_SCHEDULED"); assert.notEqual(run.attemptId, a.attemptId); assert.ok(run.record?.nextAttemptAt); assert.equal((await store.get(a.attemptId))?.failureClassification, "RETRY_SCHEDULED"); } finally { await disposeTrustedContexts(root); } });

test("transient timeout is retryable but malformed is terminal", async () => { const { root, contexts } = await setup(); try { const s1 = new InMemoryTargetedVerifierAttemptStore(); const w1 = worker(s1, contexts[0], result("TRANSPORT_FAILED", retryTransient), { policy: { maxAttempts: 1 } }); const a1 = await create(w1, contexts[0]); assert.equal((await w1.runOnce(a1.attemptId)).outcome, "COMPLETE"); const s2 = new InMemoryTargetedVerifierAttemptStore(); const w2 = worker(s2, contexts[0], result("MALFORMED_RESPONSE")); const a2 = await create(w2, contexts[0]); assert.equal((await w2.runOnce(a2.attemptId)).outcome, "COMPLETE"); } finally { await disposeTrustedContexts(root); } });

test("post-fence invalidation and context reconstruction fail closed", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("ACTIVE_CONFIRMED", retryNone, "ACTIVE"), { postFence: async () => fence(false, "STALE") }); const a = await create(w, contexts[0]); const r = await w.runOnce(a.attemptId); assert.equal(r.outcome, "FAILED"); assert.equal(r.record?.failureClassification, "STALE"); const store2 = new InMemoryTargetedVerifierAttemptStore(); const w2 = worker(store2, contexts[0], result("UNKNOWN")); const a2 = await create(w2, contexts[0]); const restarted = __createTargetedVerifierOperationalWorkerForTest({ store: store2, workerId: "restart", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "x", execute: async () => observation(contexts[0], "UNKNOWN"), postFence: async () => fence() }); assert.equal((await restarted.runOnce(a2.attemptId)).outcome, "FAILED"); } finally { await disposeTrustedContexts(root); } });

test("new generation has distinct idempotency identity and semantic hashes bind fields", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const a = await create(w, contexts[0]); const b = await create(w, contexts[1]); assert.notEqual(a.idempotencyKey, b.idempotencyKey); assert.notEqual(a.attemptId, b.attemptId); assert.notEqual(operationalSemanticEvidenceHash(a), operationalSemanticEvidenceHash({ ...a, responseBodySha256: "a".repeat(64) })); } finally { await disposeTrustedContexts(root); } });

test("eligibility blocks execution and cadence/concurrency are bounded", async () => { const { root, contexts } = await setup(); try { const blocked = { ...contexts[0], targetedVerifierEligible: false } as TargetedVerifierContext; const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); await assert.rejects(() => create(w, blocked), /VERIFIER_NOT_ELIGIBLE/); let calls = 0; let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const store2 = new InMemoryTargetedVerifierAttemptStore(); const w2 = __createTargetedVerifierOperationalWorkerForTest({ store: store2, workerId: "bound", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "x", execute: async () => { calls++; await gate; return observation(contexts[0], "UNKNOWN"); }, postFence: async () => fence(), policy: { maxConcurrent: 1 } }); const a = await create(w2, contexts[0]); const b = await create(w2, contexts[1]); const first = w2.runOnce(a.attemptId); await new Promise((resolve) => setImmediate(resolve)); const second = await w2.runOnce(b.attemptId); assert.equal(second.outcome, "CADENCE_BLOCKED"); release(); await first; assert.equal(calls, 1); } finally { await disposeTrustedContexts(root); } });

test("crash recovery stages preserve durable lifecycle without mutation authority", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const a = await create(w, contexts[0]); assert.equal((await store.get(a.attemptId))?.lifecycle, "NOT_STARTED"); const c = await store.claim(a.attemptId, "crashed", NOW, 1); assert.ok(c); assert.equal((await store.reclaimExpired("2026-01-01T00:00:01.000Z")), 1); const final = await store.get(a.attemptId); assert.equal(final?.lifecycle, "FAILED"); assert.equal(final?.authorityGranted, false); assert.equal(final?.deactivationAuthorityGranted, false); } finally { await disposeTrustedContexts(root); } });

test("durable response recovery never re-executes provider", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const created = await create(w, contexts[0]); const claim = await store.claim(created.attemptId, "old", NOW, 1); assert.ok(claim); const obs = observation(contexts[0], "UNKNOWN"); const p = interpretOpenSeaExactOrderObservation({ context: contexts[0], observation: obs }); const saved = { ...claim.record, lifecycle: "RESPONSE_OBSERVED" as const, providerObservedAt: obs.observedAt, httpStatus: obs.httpStatus, transportOutcome: obs.transportOutcome, responseBodySha256: obs.responseBodySha256, rawResponseArtifactHash: obs.rawResponseArtifactHash, normalizedProviderStatus: p.providerStatus, providerResultStatus: p.status, providerReasonCodes: p.reasonCodes, normalizedOrder: p.normalizedOrder, providerResultReasonCodes: p.reasonCodes, reasonCodes: p.reasonCodes }; assert.equal(await store.saveResponse(created.attemptId, claim.leaseToken, saved, NOW), true); await store.reclaimExpired("2026-01-01T00:00:02.000Z"); let executions = 0; const resumed = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "new", now: () => "2026-01-01T00:00:02.000Z", nowMs: () => 2000, credentialProvider: async () => { throw new Error("CREDENTIAL_MUST_NOT_BE_READ"); }, execute: async () => { executions++; return obs; }, postFence: async () => fence() }); const run = await resumed.runOnce(created.attemptId); assert.equal(executions, 0); assert.notEqual(run.outcome, "STALE_LEASE"); } finally { await disposeTrustedContexts(root); } });

test("lease CAS expiry and generation-bound idempotency are enforced", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN"), { policy: { maxAttempts: 3 } }); const a = await create(w, contexts[0]); const c = await store.claim(a.attemptId, "owner", NOW, 1); assert.ok(c); assert.equal(await store.fail(a.attemptId, "wrong", { ...c.record, lifecycle: "FAILED" as const }, NOW), false); assert.equal(await store.fail(a.attemptId, c.leaseToken, { ...c.record, lifecycle: "FAILED" as const }, "2026-01-01T00:00:02.000Z"), false); const changed = { ...contexts[0], generationRootHash: "e".repeat(64) } as TargetedVerifierContext; assert.notEqual(operationalIdempotencyKey(contexts[0]), operationalIdempotencyKey(changed)); } finally { await disposeTrustedContexts(root); } });
test("fresh cadence denial occurs before claim and leaves NOT_STARTED", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); let claims = 0, credentials = 0, executions = 0; store.claim = async (...args) => { claims++; return InMemoryTargetedVerifierAttemptStore.prototype.claim.apply(store, args); }; store.acquirePermit = async () => null; const w = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "blocked", now: () => NOW, nowMs: () => 0, credentialProvider: async () => { credentials++; return "x"; }, execute: async () => { executions++; return observation(contexts[0], "UNKNOWN"); }, postFence: async () => fence() }); const a = await create(w, contexts[0]); const run = await w.runOnce(a.attemptId); assert.equal(run.outcome, "CADENCE_BLOCKED"); assert.equal(claims, 0); assert.equal(credentials, 0); assert.equal(executions, 0); assert.deepEqual(await store.get(a.attemptId), a); } finally { await disposeTrustedContexts(root); } });
test("fresh execution orders permit before claim before credential before executor", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const events: string[] = []; const acquire = store.acquirePermit.bind(store); const claim = store.claim.bind(store); store.acquirePermit = async (...args) => { events.push("permit"); return acquire(...args); }; store.claim = async (...args) => { events.push("claim"); return claim(...args); }; const w = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "ordered", now: () => NOW, nowMs: () => 0, credentialProvider: async () => { events.push("credential"); return "x"; }, execute: async () => { events.push("execute"); return observation(contexts[0], "UNKNOWN"); }, postFence: async () => fence() }); const a = await create(w, contexts[0]); await w.runOnce(a.attemptId); assert.deepEqual(events.slice(0, 4), ["permit", "claim", "credential", "execute"]); } finally { await disposeTrustedContexts(root); } });
test("permit acquired then claim lost releases exactly once without provider", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); let releases = 0, credentials = 0, executions = 0; const acquire = store.acquirePermit.bind(store); store.acquirePermit = (...args) => acquire(...args); store.claim = async () => null; const release = store.releasePermit.bind(store); store.releasePermit = async id => { releases++; return release(id); }; const w = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "race", now: () => NOW, nowMs: () => 0, credentialProvider: async () => { credentials++; return "x"; }, execute: async () => { executions++; return observation(contexts[0], "UNKNOWN"); }, postFence: async () => fence() }); const a = await create(w, contexts[0]); const run = await w.runOnce(a.attemptId); assert.equal(run.outcome, "STALE_LEASE"); assert.equal(releases, 1); assert.equal(credentials, 0); assert.equal(executions, 0); } finally { await disposeTrustedContexts(root); } });
test("REQUEST_PENDING active lease is not replayed", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const a = await create(w, contexts[0]); const c = await store.claim(a.attemptId, "owner", NOW, 10000); assert.ok(c); let permits = 0, credentials = 0, executions = 0; store.acquirePermit = async () => { permits++; return null; }; const resumed = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "other", now: () => NOW, nowMs: () => 0, credentialProvider: async () => { credentials++; return "x"; }, execute: async () => { executions++; return observation(contexts[0], "UNKNOWN"); }, postFence: async () => fence() }); const run = await resumed.runOnce(a.attemptId); assert.equal(run.outcome, "STALE_LEASE"); assert.equal(permits, 0); assert.equal(credentials, 0); assert.equal(executions, 0); } finally { await disposeTrustedContexts(root); } });
test("pre-provider credential failure releases the permit once", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); let releases = 0, executions = 0; const release = store.releasePermit.bind(store); store.releasePermit = async id => { releases++; return release(id); }; const w = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "credential-failure", now: () => NOW, nowMs: () => 0, credentialProvider: async () => { throw new Error("CREDENTIAL_FAILURE"); }, execute: async () => { executions++; return observation(contexts[0], "UNKNOWN"); }, postFence: async () => fence() }); const a = await create(w, contexts[0]); await w.runOnce(a.attemptId); assert.equal(releases, 1); assert.equal(executions, 0); } finally { await disposeTrustedContexts(root); } });
test("valid credential containing r and n is accepted", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); let executions = 0; const w = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "valid-key", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "normal-provider-key", execute: async () => { executions++; return observation(contexts[0], "UNKNOWN"); }, postFence: async () => fence() }); const a = await create(w, contexts[0]); await w.runOnce(a.attemptId); assert.equal(executions, 1); } finally { await disposeTrustedContexts(root); } });
test("CR/LF credentials fail closed and release the provider permit", async () => { const { root, contexts } = await setup(); try { for (const [label,key] of [["lf","abc"+String.fromCharCode(10)+"def"],["cr","abc"+String.fromCharCode(13)+"def"],["crlf","abc"+String.fromCharCode(13,10)+"def"]] as const) { const store = new InMemoryTargetedVerifierAttemptStore(); let executions = 0, releases = 0; const release = store.releasePermit.bind(store); store.releasePermit = async id => { releases++; return release(id); }; const w = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: label, now: () => NOW, nowMs: () => 0, credentialProvider: async () => key, execute: async () => { executions++; return observation(contexts[0], "UNKNOWN"); }, postFence: async () => fence() }); const a = await create(w, contexts[0]); const run = await w.runOnce(a.attemptId); assert.equal(run.outcome, "FAILED"); assert.equal(executions, 0); assert.equal(releases, 1); } } finally { await disposeTrustedContexts(root); } });
test("PENDING_FENCE restart recovery performs zero provider-side work", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const created = await create(w, contexts[0]); const claim = await store.claim(created.attemptId, "old", NOW, 10000); assert.ok(claim); const obs = observation(contexts[0], "UNKNOWN"); const p = interpretOpenSeaExactOrderObservation({ context: contexts[0], observation: obs }); const observed = { ...claim.record, lifecycle: "RESPONSE_OBSERVED" as const, providerObservedAt: obs.observedAt, httpStatus: obs.httpStatus, transportOutcome: obs.transportOutcome, responseBodySha256: obs.responseBodySha256, rawResponseArtifactHash: obs.rawResponseArtifactHash, normalizedProviderStatus: p.providerStatus, providerResultStatus: p.status, providerResultReasonCodes: p.reasonCodes, normalizedOrder: p.normalizedOrder, providerResultReasonCodes: p.reasonCodes, reasonCodes: p.reasonCodes, retry: p.retry }; assert.equal(await store.saveResponse(created.attemptId, claim.leaseToken, observed, NOW), true); assert.equal(await store.saveResponse(created.attemptId, claim.leaseToken, { ...observed, lifecycle: "PENDING_FENCE" as const }, NOW), true); await store.reclaimExpired("2026-01-01T00:00:20.000Z"); let permits = 0, credentials = 0, executions = 0; const originalPermit = store.acquirePermit.bind(store); store.acquirePermit = async (...args) => { permits++; return originalPermit(...args); }; const restarted = __createTargetedVerifierOperationalWorkerForTest({ store, workerId: "pending-restart", now: () => "2026-01-01T00:00:20.000Z", nowMs: () => 20000, credentialProvider: async () => { credentials++; return "must-not-read"; }, execute: async () => { executions++; return obs; }, postFence: async () => fence(), contextResolver: async () => contexts[0] }); const run = await restarted.runOnce(created.attemptId); assert.notEqual(run.outcome, "STALE_LEASE"); assert.equal(permits, 0); assert.equal(credentials, 0); assert.equal(executions, 0); assert.notEqual((await store.get(created.attemptId))?.lifecycle, "NOT_STARTED"); } finally { await disposeTrustedContexts(root); } });
test("production factory binds the accepted journal fence bridge", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); let reads = 0; const reader = { readSnapshot: async (identity: { orderHash: string; chain: string; contractAddress: string; tokenId: string }) => { reads++; assert.deepEqual(identity, { orderHash: contexts[0].orderHash, chain: contexts[0].chain, contractAddress: contexts[0].contractAddress, tokenId: contexts[0].expectedIdentity.tokenId }); return contexts[0].preVerification; } }; const w = createTargetedVerifierOperationalWorker({ store, snapshotReader: reader, workerId: "production", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "production-key", execute: async () => observation(contexts[0], "UNKNOWN") }); const a = await w.createAttempt({ context: contexts[0], preVerification: contexts[0].preVerification, createdAt: NOW }); const run = await w.runOnce(a.attemptId); assert.equal(reads, 1); assert.equal(run.outcome, "COMPLETE"); assert.equal(run.record?.authorityGranted, false); assert.equal(run.record?.deactivationAuthorityGranted, false); } finally { await disposeTrustedContexts(root); } });
