import assert from "node:assert/strict";
import test from "node:test";
import { makeTrustedContexts, disposeTrustedContexts } from "./helpers/trustedVerifierContexts.js";
import {
  InMemoryTargetedVerifierAttemptStore, TargetedVerifierOperationalWorker,
  operationalSemanticEvidenceHash, type OperationalAttemptRecord
} from "../src/reconciliation/verifier/targetedVerifierOperationalWorker.js";
import type { ProviderResult, TargetedVerifierContext } from "../src/reconciliation/verifier/targetedVerifierTypes.js";

const NOW = "2026-01-01T00:00:00.000Z";
const retryNone = { retryable: false, retryReason: "NONE", recommendedPolicyClass: "NONE" as const };
const retryRate = { retryable: true, retryReason: "RATE_LIMITED", recommendedPolicyClass: "RATE_LIMITED" as const };
const retryTransient = { retryable: true, retryReason: "TRANSIENT_TRANSPORT", recommendedPolicyClass: "TRANSIENT_TRANSPORT" as const };

function result(status: ProviderResult["status"], retry = retryNone, providerStatus: ProviderResult["providerStatus"] = null): ProviderResult {
  return { status, reasonCodes: status === "RATE_LIMITED" ? ["HTTP_429"] : status === "TRANSPORT_FAILED" ? ["REQUEST_TIMEOUT"] : [], providerStatus, normalizedOrder: null, observedAt: NOW, responseBodySha256: null, rawResponseArtifactHash: null, httpStatus: status === "RATE_LIMITED" ? 429 : status === "TRANSPORT_FAILED" ? null : 200, retry, authorityGranted: false, deactivationAuthorityGranted: false } as ProviderResult;
}
function fence(valid = true, status: "STABLE" | "STALE" | "RECONCILIATION_REQUIRED" = "STABLE") { return { valid, status, postVerification: { watermark: { eventId: "100", receivedAt: NOW }, relevantOrderFingerprint: { orderHash: "0x" + "a".repeat(64), eventIds: [], digest: "0".repeat(64), orderingAmbiguous: false } }, reasonCodes: valid ? [] : [status === "STALE" ? "HTTP_STATUS_OR_BODY_UNPROVEN" : "RECONCILIATION_REQUIRED"] }; }
async function setup() { const x = await makeTrustedContexts(); return x; }
function worker(store: InMemoryTargetedVerifierAttemptStore, context: TargetedVerifierContext, execution: ProviderResult, options: Partial<ConstructorParameters<typeof TargetedVerifierOperationalWorker>[0]> = {}) {
  return new TargetedVerifierOperationalWorker({ store, workerId: options.workerId ?? "w1", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "TEST_ONLY_FAKE_OPENSEA_KEY", execute: async () => ({ observation: {} as never, providerResult: execution }), postFence: async () => fence(), ...options });
}
async function create(w: TargetedVerifierOperationalWorker, c: TargetedVerifierContext) { return w.createAttempt({ context: c, preVerification: c.preVerification, createdAt: NOW }); }

test("confirmed provider status families remain read-only", async () => { const { root, contexts } = await setup(); try { for (const [status, provider] of [["ACTIVE_CONFIRMED", "ACTIVE"], ["INACTIVE_CONFIRMED", "INACTIVE"], ["EXPIRED_CONFIRMED", "EXPIRED"], ["TERMINAL_CONFIRMED", "FULFILLED"]] as const) { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result(status, retryNone, provider)); const a = await create(w, contexts[0]); const r = await w.runOnce(a.attemptId); assert.equal(r.outcome, "COMPLETE"); assert.equal(r.record?.authorityGranted, false); assert.equal(r.record?.deactivationAuthorityGranted, false); } } finally { await disposeTrustedContexts(root); } });

test("idempotent attempts, lifecycle completion and authority invariants", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("INACTIVE_CONFIRMED", retryNone, "INACTIVE")); const a = await create(w, contexts[0]); const b = await create(w, contexts[0]); assert.equal(a.attemptId, b.attemptId); const run = await w.runOnce(a.attemptId); assert.equal(run.outcome, "COMPLETE"); assert.equal(run.record?.lifecycle, "COMPLETE"); assert.equal(run.record?.authorityGranted, false); assert.equal(run.record?.deactivationAuthorityGranted, false); } finally { await disposeTrustedContexts(root); } });

test("exclusive claim and stale lease completion", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const a = await create(w, contexts[0]); const [x, y] = await Promise.all([store.claim(a.attemptId, "a", NOW, 1000), store.claim(a.attemptId, "b", NOW, 1000)]); assert.equal(Boolean(x) !== Boolean(y), true); const owner = x ?? y!; assert.equal(await store.complete(a.attemptId, "stale", owner.record), false); } finally { await disposeTrustedContexts(root); } });

test("expired lease is reclaimed fail-closed", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const a = await create(w, contexts[0]); await store.claim(a.attemptId, "a", NOW, 1); assert.equal(await store.reclaimExpired("2026-01-01T00:00:01.000Z"), 1); assert.equal((await store.get(a.attemptId))?.failureClassification, "REQUEST_OUTCOME_UNCERTAIN"); } finally { await disposeTrustedContexts(root); } });

test("retryable results are delayed and bounded", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("RATE_LIMITED", retryRate), { policy: { maxAttempts: 2, rateLimitedDelayMs: 60_000 } }); const a = await create(w, contexts[0]); const run = await w.runOnce(a.attemptId); assert.equal(run.outcome, "RETRY_SCHEDULED"); assert.notEqual(run.attemptId, a.attemptId); assert.ok(run.record?.nextAttemptAt); assert.equal((await store.get(a.attemptId))?.failureClassification, "RETRY_SCHEDULED"); } finally { await disposeTrustedContexts(root); } });

test("transient timeout is retryable but malformed is terminal", async () => { const { root, contexts } = await setup(); try { const s1 = new InMemoryTargetedVerifierAttemptStore(); const w1 = worker(s1, contexts[0], result("TRANSPORT_FAILED", retryTransient), { policy: { maxAttempts: 1 } }); const a1 = await create(w1, contexts[0]); assert.equal((await w1.runOnce(a1.attemptId)).outcome, "COMPLETE"); const s2 = new InMemoryTargetedVerifierAttemptStore(); const w2 = worker(s2, contexts[0], result("MALFORMED_RESPONSE")); const a2 = await create(w2, contexts[0]); assert.equal((await w2.runOnce(a2.attemptId)).outcome, "COMPLETE"); } finally { await disposeTrustedContexts(root); } });

test("post-fence invalidation and context reconstruction fail closed", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("ACTIVE_CONFIRMED", retryNone, "ACTIVE"), { postFence: async () => fence(false, "STALE") }); const a = await create(w, contexts[0]); const r = await w.runOnce(a.attemptId); assert.equal(r.outcome, "FAILED"); assert.equal(r.record?.failureClassification, "STALE"); const store2 = new InMemoryTargetedVerifierAttemptStore(); const w2 = worker(store2, contexts[0], result("UNKNOWN")); const a2 = await create(w2, contexts[0]); const restarted = new TargetedVerifierOperationalWorker({ store: store2, workerId: "restart", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "x", execute: async () => ({ observation: {} as never, providerResult: result("UNKNOWN") }), postFence: async () => fence() }); assert.equal((await restarted.runOnce(a2.attemptId)).outcome, "FAILED"); } finally { await disposeTrustedContexts(root); } });

test("new generation has distinct idempotency identity and semantic hashes bind fields", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const a = await create(w, contexts[0]); const b = await create(w, contexts[1]); assert.notEqual(a.idempotencyKey, b.idempotencyKey); assert.notEqual(a.attemptId, b.attemptId); assert.notEqual(operationalSemanticEvidenceHash(a), operationalSemanticEvidenceHash({ ...a, responseBodySha256: "a".repeat(64) })); } finally { await disposeTrustedContexts(root); } });

test("eligibility blocks execution and cadence/concurrency are bounded", async () => { const { root, contexts } = await setup(); try { const blocked = { ...contexts[0], targetedVerifierEligible: false } as TargetedVerifierContext; const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); await assert.rejects(() => create(w, blocked), /VERIFIER_NOT_ELIGIBLE/); let calls = 0; let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const store2 = new InMemoryTargetedVerifierAttemptStore(); const w2 = new TargetedVerifierOperationalWorker({ store: store2, workerId: "bound", now: () => NOW, nowMs: () => 0, credentialProvider: async () => "x", execute: async () => { calls++; await gate; return { observation: {} as never, providerResult: result("UNKNOWN") }; }, postFence: async () => fence(), policy: { maxConcurrent: 1 } }); const a = await create(w2, contexts[0]); const b = await create(w2, contexts[1]); const first = w2.runOnce(a.attemptId); await new Promise((resolve) => setImmediate(resolve)); const second = await w2.runOnce(b.attemptId); assert.equal(second.outcome, "CADENCE_BLOCKED"); release(); await first; assert.equal(calls, 1); } finally { await disposeTrustedContexts(root); } });

test("crash recovery stages preserve durable lifecycle without mutation authority", async () => { const { root, contexts } = await setup(); try { const store = new InMemoryTargetedVerifierAttemptStore(); const w = worker(store, contexts[0], result("UNKNOWN")); const a = await create(w, contexts[0]); assert.equal((await store.get(a.attemptId))?.lifecycle, "NOT_STARTED"); const c = await store.claim(a.attemptId, "crashed", NOW, 1); assert.ok(c); assert.equal((await store.reclaimExpired("2026-01-01T00:00:01.000Z")), 1); const final = await store.get(a.attemptId); assert.equal(final?.lifecycle, "FAILED"); assert.equal(final?.authorityGranted, false); assert.equal(final?.deactivationAuthorityGranted, false); } finally { await disposeTrustedContexts(root); } });
