import { createHash } from "node:crypto";
import { deepFreeze } from "../evidence/canonicalEvidence.js";
import { isTrustedTargetedVerifierContext } from "./targetedVerifierContext.js";
import { isCanonicalAddress, isCanonicalHash, isCanonicalOrderHash } from "./targetedVerifierPolicy.js";
import { OPENSEA_ORDER_CONTRACT_VERSION, type TargetedVerifierContext, type TransportOutcome } from "./targetedVerifierTypes.js";
import { OPENAPI_DOCUMENT_SHA256, GET_ORDER_SCHEMA_SHA256 } from "./openSeaExactOrderContract.js";
import { isJsonObject, jsonString, parseLosslessJson, type LosslessJsonValue } from "./losslessJson.js";
import { officialJsonInt32Value, officialJsonInt64Value, validateOfficialListingRequired } from "./openSeaSchemaAdmission.js";
export const OPENSEA_EXACT_ORDER_ADAPTER_VERSION = "opensea-exact-order-adapter-v6-2026-09" as const;
export type OpenSeaTemporalProof = "ACTIVE_WINDOW_CONFIRMED" | "EXPIRED_WINDOW_CONFIRMED" | "TRUSTED_OBSERVATION" | "UNTRUSTED";
export interface OpenSeaTimingEvidence { readonly requestStartedAt:string; readonly responseHeadersAt:string; readonly responseCompletedAt:string; readonly elapsedMs:number; readonly overallDeadlineMs:number; readonly deadlineExceeded:boolean; }
export interface OpenSeaExactOrderRawInput { readonly context:TargetedVerifierContext; readonly httpStatus:number|null; readonly body:Uint8Array|null; readonly responseBodySha256?:string|null; readonly rawResponseArtifactHash?:string|null; readonly headers?:readonly {readonly name:string;readonly value:string}[]; readonly timing?:OpenSeaTimingEvidence; readonly transportOutcome?:TransportOutcome; }
export interface OpenSeaExactOrderObservationV1 { readonly adapterVersion:typeof OPENSEA_EXACT_ORDER_ADAPTER_VERSION; readonly providerContractVersion:string; readonly openApiDocumentSha256:string; readonly getOrderSchemaSha256:string; readonly requestIdentity:{readonly method:"GET";readonly endpointPath:string;readonly chain:string;readonly protocolAddress:string;readonly orderHash:string}; readonly outcome:"VALID"|"UNKNOWN"|"MALFORMED"|"UNSUPPORTED"|"TRANSPORT_FAILED"|"AMBIGUOUS"|"RATE_LIMITED"; readonly reasonCodes:readonly string[]; readonly providerStatus:string|null; readonly orderHash:string|null; readonly chain:string|null; readonly protocolAddress:string|null; readonly contractAddress:string|null; readonly assetIdentifier:string|null; readonly offerIdentifier:string|null; readonly remainingQuantity:string|null; readonly startTime:string|null; readonly endTime:string|null; readonly itemType:number|null; readonly orderType:number|null; readonly observedAt:string|null; readonly observationLowerBound:string|null; readonly observationUpperBound:string|null; readonly responseBodySha256:string|null; readonly rawResponseArtifactHash:string|null; readonly httpStatus:number|null; readonly transportOutcome:TransportOutcome; readonly supportedListing:boolean; readonly temporalProof:OpenSeaTemporalProof; readonly timing:OpenSeaTimingEvidence|null; readonly authorityGranted:false; readonly deactivationAuthorityGranted:false; }
const TRUSTED=new WeakSet<object>(); const OBS_CONTEXT=new WeakMap<object,TargetedVerifierContext>();
export function isTrustedOpenSeaExactOrderObservation(v:unknown):v is OpenSeaExactOrderObservationV1{return !!v&&typeof v==="object"&&TRUSTED.has(v);}
export function isObservationBoundToContext(v:unknown,c:TargetedVerifierContext){return isTrustedOpenSeaExactOrderObservation(v)&&OBS_CONTEXT.get(v)===c;}
const endpoint="/api/v2/orders/chain/{chain}/protocol/{protocol_address}/{order_hash}"; const sha=(b:Uint8Array)=>createHash("sha256").update(b).digest("hex");
const hs=(h:OpenSeaExactOrderRawInput["headers"],n:string)=>(h??[]).filter(x=>x.name.toLowerCase()===n).map(x=>x.value); const field=(o:Record<string,LosslessJsonValue>,k:string)=>o[k];
const validName=(x:string)=>/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/.test(x); const iso=(x:unknown):x is string=>typeof x==="string"&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(x)&&!Number.isNaN(Date.parse(x))&&new Date(Date.parse(x)).toISOString()===x;
const timingOk=(t:OpenSeaTimingEvidence|undefined)=>!!t&&iso(t.requestStartedAt)&&iso(t.responseHeadersAt)&&iso(t.responseCompletedAt)&&Date.parse(t.requestStartedAt)<=Date.parse(t.responseHeadersAt)&&Date.parse(t.responseHeadersAt)<=Date.parse(t.responseCompletedAt)&&typeof t.elapsedMs==="number"&&typeof t.overallDeadlineMs==="number"&&Number.isSafeInteger(t.elapsedMs)&&t.elapsedMs>=0&&Number.isSafeInteger(t.overallDeadlineMs)&&t.overallDeadlineMs>0&&t.deadlineExceeded===false&&t.elapsedMs<=t.overallDeadlineMs;
function failure(i:OpenSeaExactOrderRawInput,o:OpenSeaExactOrderObservationV1["outcome"],reasons:string[],f:Partial<OpenSeaExactOrderObservationV1>={}):OpenSeaExactOrderObservationV1{const r=deepFreeze({adapterVersion:OPENSEA_EXACT_ORDER_ADAPTER_VERSION,providerContractVersion:OPENSEA_ORDER_CONTRACT_VERSION,openApiDocumentSha256:OPENAPI_DOCUMENT_SHA256,getOrderSchemaSha256:GET_ORDER_SCHEMA_SHA256,requestIdentity:{method:"GET" as const,endpointPath:endpoint,chain:i.context.chain,protocolAddress:i.context.protocolAddress,orderHash:i.context.orderHash},outcome:o,reasonCodes:[...new Set(reasons)].sort(),providerStatus:null,orderHash:null,chain:null,protocolAddress:null,contractAddress:null,assetIdentifier:null,offerIdentifier:null,remainingQuantity:null,startTime:null,endTime:null,itemType:null,orderType:null,observedAt:null,observationLowerBound:null,observationUpperBound:null,responseBodySha256:i.body?sha(i.body):null,rawResponseArtifactHash:i.rawResponseArtifactHash??null,httpStatus:i.httpStatus,transportOutcome:i.transportOutcome??"HTTP",supportedListing:false,temporalProof:"UNTRUSTED" as const,timing:i.timing??null,authorityGranted:false as const,deactivationAuthorityGranted:false as const,...f});TRUSTED.add(r);OBS_CONTEXT.set(r,i.context);return r;}
export function adaptOpenSeaExactOrder(i:OpenSeaExactOrderRawInput):OpenSeaExactOrderObservationV1{
 if(!isTrustedTargetedVerifierContext(i.context))throw new Error("UNTRUSTED_TARGETED_VERIFIER_CONTEXT"); const tr=i.transportOutcome??"HTTP"; if(tr!=="HTTP")return failure(i,"TRANSPORT_FAILED",[tr==="TIMEOUT"?"REQUEST_TIMEOUT":"CONNECTION_RESET"]); const s=i.httpStatus;
 if(s===429)return failure(i,"RATE_LIMITED",["HTTP_429"]); if(s!==null&&s>=500){const r=s===500?"HTTP_500":s===502?"HTTP_502":s===503?"HTTP_503":s===504?"HTTP_504":"HTTP_5XX_PROVIDER_FAILURE";return failure(i,"TRANSPORT_FAILED",[r]);} if(s===409)return failure(i,"AMBIGUOUS",["HTTP_409_PROVIDER_CONFLICT"]); if(s===400)return failure(i,"UNSUPPORTED",["HTTP_400_UNSUPPORTED_OR_INVALID_REQUEST"]); if(s===401||s===403)return failure(i,"UNKNOWN",[`HTTP_${s}_ACCESS_FAILURE`]); if(s===404)return failure(i,"UNKNOWN",["HTTP_404_NOT_STATE_PROOF"]); if(s!==200)return failure(i,"UNKNOWN",["HTTP_STATUS_OR_BODY_UNPROVEN"]);
 if(!i.body)return failure(i,"UNKNOWN",["HTTP_STATUS_OR_BODY_UNPROVEN"]); const b=new Uint8Array(i.body),actual=sha(b); if(b.length>1048576)return failure(i,"MALFORMED",["BODY_TOO_LARGE"]); if(b[0]===0xef&&b[1]===0xbb&&b[2]===0xbf)return failure(i,"MALFORMED",["MALFORMED_JSON"]); const headers=i.headers??[]; if(headers.some(x=>!validName(x.name)||/[\r\n]/.test(x.value)))return failure(i,"MALFORMED",["HEADER_INVALID"]);
 const enc=hs(headers,"content-encoding"); if(enc.length>1||enc.some(x=>x.toLowerCase()!=="identity"))return failure(i,"UNSUPPORTED",["UNSUPPORTED_CONTENT_ENCODING"]); if(hs(headers,"age").length)return failure(i,"UNKNOWN",["OBSERVATION_TIME_INVALID"]); const ct=hs(headers,"content-type"); if(ct.length!==1||!/^application\/json(?:; charset=utf-8)?$/i.test(ct[0]))return failure(i,"MALFORMED",["CONTENT_TYPE_UNSUPPORTED"]); const cl=hs(headers,"content-length"); if(cl.length>1||(cl.length===1&&(!/^(0|[1-9][0-9]*)$/.test(cl[0])||BigInt(cl[0])>1048576n||BigInt(cl[0])!==BigInt(b.length))))return failure(i,"MALFORMED",["CONTENT_LENGTH_INVALID"]); if(i.responseBodySha256!=null&&i.responseBodySha256!==actual)return failure(i,"MALFORMED",["RAW_RESPONSE_HASH_MISMATCH"]); if(i.rawResponseArtifactHash!=null&&!isCanonicalHash(i.rawResponseArtifactHash))return failure(i,"MALFORMED",["RAW_RESPONSE_ARTIFACT_HASH_INVALID"]);
 let root:LosslessJsonValue;try{root=parseLosslessJson(new TextDecoder("utf-8",{fatal:true}).decode(b));}catch{return failure(i,"MALFORMED",["MALFORMED_JSON"]);}if(!isJsonObject(root)||!isJsonObject((root as Record<string,LosslessJsonValue>).order))return failure(i,"MALFORMED",["RESPONSE_OBJECT_REQUIRED"]); const o=(root as Record<string,LosslessJsonValue>).order as Record<string,LosslessJsonValue>; if(!validateOfficialListingRequired(o))return failure(i,"MALFORMED",["OFFICIAL_SCHEMA_INVALID"]); const pd=field(o,"protocol_data"); const params=isJsonObject(pd)&&isJsonObject(field(pd,"parameters"))?field(pd,"parameters") as Record<string,LosslessJsonValue>:null; const asset=isJsonObject(field(o,"asset"))?field(o,"asset") as Record<string,LosslessJsonValue>:null; const offer=params&&Array.isArray(field(params,"offer"))?field(params,"offer") as LosslessJsonValue[]:null;
 const orderHash=jsonString(field(o,"order_hash")),chain=jsonString(field(o,"chain")),protocol=jsonString(field(o,"protocol_address")),contract=asset?jsonString(field(asset,"contract")):null;if(!orderHash||!chain||!protocol||!contract||!isCanonicalOrderHash(orderHash)||!isCanonicalAddress(protocol)||!isCanonicalAddress(contract))return failure(i,"MALFORMED",["IDENTITY_MISMATCH"]);if(orderHash!==i.context.orderHash||chain!==i.context.chain||protocol!==i.context.protocolAddress||contract!==i.context.contractAddress)return failure(i,"AMBIGUOUS",["IDENTITY_MISMATCH"]);
 const status=jsonString(field(o,"status")),statuses=new Set(["ACTIVE","INACTIVE","FULFILLED","EXPIRED","CANCELLED"]);if(!status||!statuses.has(status))return failure(i,"UNKNOWN",["UNKNOWN_PROVIDER_STATUS"]);const qty=officialJsonInt64Value(field(o,"remaining_quantity"));if(qty===null||qty<0n)return failure(i,"MALFORMED",["REMAINING_QUANTITY_INVALID"]);
 if(field(o,"is_private")===true||field(o,"private_listing")===true||field(o,"restricted")===true||field(o,"criteria")!==undefined||field(asset??{},"criteria")!==undefined||field(params??{},"criteria")!==undefined||field(o,"order_type")!==undefined||field(o,"item_type")!==undefined||field(params??{},"order_type")!==undefined||field(params??{},"start_time")!==undefined||field(params??{},"end_time")!==undefined)return failure(i,"UNSUPPORTED",["UNSUPPORTED_ORDER_SHAPE"]);
 const item=offer&&offer.length===1&&isJsonObject(offer[0])?offer[0] as Record<string,LosslessJsonValue>:null,assetId=asset?jsonString(field(asset,"identifier")):null,offerId=item?jsonString(field(item,"identifierOrCriteria")):null,itemToken=item?jsonString(field(item,"token")):null,itemType=item?officialJsonInt32Value(field(item,"itemType")):null,orderType=params?officialJsonInt32Value(field(params,"orderType")):null,startTime=params?jsonString(field(params,"startTime")):null,endTime=params?jsonString(field(params,"endTime")):null;if(!assetId||!offerId||assetId!==offerId||assetId!==i.context.expectedIdentity.tokenId)return failure(i,"UNSUPPORTED",["IDENTITY_MISMATCH"]);
 const dv=hs(headers,"date");let dm=NaN;if(dv.length===1&&/^[A-Z][a-z]{2}, [0-9]{2} [A-Z][a-z]{2} [0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2} GMT$/.test(dv[0])){const n=Date.parse(dv[0]);if(!Number.isNaN(n)&&new Date(n).toUTCString()===dv[0])dm=n;}const tk=timingOk(i.timing),sk=tk&&Number.isFinite(dm)&&dm>=Date.parse(i.timing!.requestStartedAt)-300000&&dm<=Date.parse(i.timing!.responseCompletedAt)+300000,observedAt=sk?new Date(dm).toISOString():null,lower=observedAt?new Date(dm-1000).toISOString():null,upper=observedAt?new Date(dm+1000).toISOString():null,start=startTime&&/^\d+$/.test(startTime)?BigInt(startTime):null,end=endTime&&/^\d+$/.test(endTime)?BigInt(endTime):null;let proof:OpenSeaTemporalProof="UNTRUSTED";if(observedAt&&start!==null&&end!==null){if(status==="ACTIVE"&&dm-1000>=Number(start)*1000&&dm+1000<Number(end)*1000)proof="ACTIVE_WINDOW_CONFIRMED";else if(status==="EXPIRED"&&dm-1000>=Number(end)*1000)proof="EXPIRED_WINDOW_CONFIRMED";else if(status!=="ACTIVE"&&status!=="EXPIRED")proof="TRUSTED_OBSERVATION";}
 const listing=itemType===2&&itemToken===i.context.contractAddress&&jsonString(field(item!,"startAmount"))==="1"&&jsonString(field(item!,"endAmount"))==="1"&&orderType===0&&start!==null&&end!==null&&start<=end;const temporalValid=status==="ACTIVE"?proof==="ACTIVE_WINDOW_CONFIRMED"&&qty!==null&&qty>0n:status==="EXPIRED"?proof==="EXPIRED_WINDOW_CONFIRMED":proof==="TRUSTED_OBSERVATION";const valid=listing&&temporalValid;return failure(i,valid?"VALID":listing?"UNKNOWN":"UNSUPPORTED",valid?[]:[status==="ACTIVE"&&(!qty||qty<=0n)?"ACTIVE_QUANTITY_UNPROVEN":proof==="UNTRUSTED"?"OBSERVATION_TIME_INVALID":"UNSUPPORTED_ORDER_SHAPE"],{providerStatus:status,orderHash,chain,protocolAddress:protocol,contractAddress:contract,assetIdentifier:assetId,offerIdentifier:offerId,remainingQuantity:qty?.toString()??null,startTime,endTime,itemType,orderType,observedAt,observationLowerBound:lower,observationUpperBound:upper,supportedListing:listing,temporalProof:proof,timing:i.timing??null});
}
