import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { classifyOfflineCandidates, type OfflineSweepManifest } from "../../src/reconciliation/offlineCandidateModel.js";
import { evaluateOfflineGeneration } from "../../src/reconciliation/offlineGenerationBarrierModel.js";
import { createGenerationEvidenceWriter } from "../../src/reconciliation/evidence/fileEvidenceStore.js";
import { persistIntegratedEvidence, reconstructIntegratedEvidence } from "../../src/reconciliation/evidence/reconciliationEvidenceIntegration.js";
import { deriveTargetedVerifierContext } from "../../src/reconciliation/verifier/targetedVerifierContext.js";
import { eventFingerprint } from "../../src/reconciliation/verifier/targetedVerifierPolicy.js";
const CONTRACT="0x9ed98e159be43a8d42b64053831fcae5e4d7d271", PROTOCOL="0x"+"1".repeat(40), START="2026-01-01T00:00:00.000Z", END="2026-01-01T00:01:00.000Z", PROVENANCE=Object.freeze({adapter:"a".repeat(64)}), WATERMARK={eventId:"100",receivedAt:END};
export async function makeTrustedContexts(options: { tokenId?: string; protocolAddress?: string } = {}) { const root=await mkdtemp(path.join(os.tmpdir(),"adapter-context-")), sweep="123e4567-e89b-12d3-a456-426614174000"; const manifest:OfflineSweepManifest={sweepId:sweep,generationState:"TRANSPORT_COMPLETE",transportResult:"COMPLETE",snapshotStartedAt:START,snapshotCompletedAt:END,paginationExhausted:true,nextCursor:null,truncatedByPageLimit:false,truncatedByListingLimit:false,malformedCount:0,unsupportedCount:0,conflictCount:0,cursorCycleDetected:false,repeatedPageDetected:false,sourceProvenance:PROVENANCE}; const writer=await createGenerationEvidenceWriter(root,{sweepId:sweep,modelVersion:"generation-v2",scope:{chain:"gunzilla",collection:"off-the-grid",contract:CONTRACT,endpoint:"https://api.opensea.io/api/v2/orders"},snapshotStartedAt:START,sourceProvenance:PROVENANCE,policyHash:"d".repeat(64)}); const orders=["0x"+"a".repeat(64),"0x"+"b".repeat(64)].map((orderHash,i)=>({orderHash,identity:{orderHash,chain:"gunzilla" as const,contractAddress:CONTRACT,tokenId:options.tokenId ?? String(i+1),collectionSlug:"off-the-grid" as const,protocolAddress:options.protocolAddress ?? PROTOCOL},status:"active",isActive:true,needsReconciliation:false,lastOrderEventTimestamp:null,lastOrderEventVersion:null})); const candidate=classifyOfflineCandidates({manifest,seenOrders:[],localOrders:orders,journalEvents:[]}); const generation=evaluateOfflineGeneration({sweepId:sweep,snapshotStartedAt:START,snapshotCompletedAt:END,sourceProvenance:PROVENANCE,startBarrier:{sweepId:sweep,snapshotStartedAt:START,eventHighWaterBefore:WATERMARK},endBarrier:{snapshotCompletedAt:END,eventHighWaterAfter:WATERMARK},transport:{transportResult:"COMPLETE",snapshotStartedAt:START,snapshotCompletedAt:END,paginationExhausted:true,nextCursor:null,truncatedByPageLimit:false,truncatedByListingLimit:false,malformedCount:0,unsupportedCount:0,conflictCount:0,cursorCycleDetected:false,repeatedPageDetected:false,warnings:[],errors:[],sourceProvenance:PROVENANCE,pageAttempts:2,pagesFetched:2,httpAttempts:2,retryAttempts:0,rawPagesCount:2,responseHashesCount:2,observedCount:2,normalizedCount:2,pageAttemptDetailsCount:2,successfulPageAttempts:2},catchUpRounds:[{roundNumber:1,observedHighWater:WATERMARK,pendingCount:0,processingCount:0,failedCount:0,reconciliationRequiredCount:0,unknownStatusCount:0},{roundNumber:2,observedHighWater:WATERMARK,pendingCount:0,processingCount:0,failedCount:0,reconciliationRequiredCount:0,unknownStatusCount:0}],maxCatchUpRounds:4,candidateBundle:candidate}); await persistIntegratedEvidence(writer,{candidateBundle:candidate,generationResult:generation,sourceProvenance:PROVENANCE}); const evidence=await reconstructIntegratedEvidence(writer,sweep,PROVENANCE); const contexts=orders.map((o)=>deriveTargetedVerifierContext(evidence,o.orderHash,{preVerification:{watermark:WATERMARK,relevantOrderFingerprint:eventFingerprint([],o.orderHash)}})); return {root,contexts}; }
export async function disposeTrustedContexts(root:string){await rm(root,{recursive:true,force:true});}

